import { useMemo, useState } from 'react';
import { Bar, BarChart, CartesianGrid, Cell, ComposedChart, Legend, Line, Pie, PieChart, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { ArrowDownRight, ArrowUpRight, ChevronRight, CircleAlert, TrendingUp } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useFinancialData } from './useFinancialData';
import { dashboardSeries, money, shortMoney, monthlyTrend, trendPeriods, type FinancialAnalysis } from './financialCharts';
import type { CalculatedService, Filters, FinanceSettings } from './financialModel';
import type { DirectoryEntry } from './financialSource';

const panel = 'min-w-0 rounded-2xl border border-violet-100 bg-white p-5 shadow-sm sm:p-6';
const note = 'text-sm leading-relaxed text-slate-500';
type Props = { result: FinancialAnalysis; names: DirectoryEntry[]; onClient: (id: string) => void; onServices: () => void; onIncomes: () => void; onEdit: (service: CalculatedService) => void };

export function FinancialDashboard({ result, names, onClient, onServices, onIncomes, onEdit }: Props) {
  const series = useMemo(() => dashboardSeries(result), [result]);
  const [metric, setMetric] = useState<'result' | 'margin'>('result');
  const clients = [...result.clients].map(client => ({ ...client, name: names.find(entry => entry.id === client.id)?.name || client.name })).sort((a, b) => (b[metric] ?? -Infinity) - (a[metric] ?? -Infinity));
  const maxClient = Math.max(1, ...clients.map(client => Math.abs(client[metric] ?? 0)));
  const low = result.services.filter(service => service.revenue! > 0 && (service.result ?? 0) / service.revenue! < .1);
  const pending = result.services.filter(service => service.pending.length);
  const [reviewMode, setReviewMode] = useState<'low' | 'pending' | 'excluded'>('low');
  const reviewRows = reviewMode === 'low' ? low : pending;
  return <>
    <section className={panel} aria-label="Del ingreso al resultado">
      <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold text-[#310984]">Del ingreso al resultado</h2><p className={note}>Así se transforma la actividad del periodo en resultado provisional.</p></div><span className={`rounded-full px-3 py-1 text-sm font-medium ${result.total.result < 0 ? 'bg-rose-50 text-rose-800' : 'bg-emerald-50 text-emerald-800'}`}>{result.total.result < 0 ? 'Resultado negativo' : 'Resultado incluido'} · {money(result.total.result)}</span></div>
      {result.total.revenue || result.total.expense ? <div className="mt-5 h-72" aria-hidden="true"><ResponsiveContainer width="100%" height="100%"><BarChart data={series.waterfall} margin={{ left: 0, right: 8, top: 12, bottom: 8 }}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#ede9fe" /><XAxis dataKey="name" tick={{ fontSize: 10 }} tickFormatter={name => ({ "Amenities y consumibles": "Amenities", "Salario dirección turismo": "Dirección", "Productos de limpieza": "Productos", "Otros gastos": "Otros" }[name] || name)} interval={0} angle={-30} textAnchor="end" height={55} axisLine={false} tickLine={false} /><YAxis tickFormatter={shortMoney} width={65} tick={{ fontSize: 11 }} axisLine={false} tickLine={false} /><Tooltip formatter={(_value, _name, item) => [money(item.payload.value), item.payload.name]} cursor={{ fill: '#f5f3ff' }} /><ReferenceLine y={0} stroke="#94a3b8" /><Bar dataKey="range" radius={4} isAnimationActive={false}>{series.waterfall.map(row => <Cell key={row.name} fill={row.color} />)}</Bar></BarChart></ResponsiveContainer></div> : <p className="py-10 text-center text-slate-500">Sin movimientos incluidos en este periodo.</p>}
      <ol className="grid grid-cols-2 gap-3 text-sm sm:grid-cols-4">{series.waterfall.map(row => <li key={row.name} className="rounded-xl bg-slate-50 p-3"><span className="mb-1 flex items-center gap-2 text-xs text-slate-600"><span className="h-2 w-2 shrink-0 rounded-full" style={{ background: row.color }} />{row.name}</span><strong className="tabular-nums">{money(row.value)}</strong></li>)}</ol>
      <p className="mt-4 text-xs text-slate-500">Gastos generales incluidos: <strong>{money(result.general.expense)}</strong>. Se cuentan una vez y no se reparten entre clientes.</p>
    </section>
    <div className="grid gap-5 xl:grid-cols-2">
      <section className={panel} aria-label="Distribución de gastos"><h2 className="text-lg font-semibold text-[#310984]">Distribución de gastos</h2><p className={note}>Peso de cada categoría sobre los gastos incluidos.</p>
        {result.total.expense > 0 ? <div className="relative mx-auto h-60 max-w-xs" aria-hidden="true"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={series.costs.filter(row => row.value > 0)} dataKey="value" nameKey="name" innerRadius="65%" outerRadius="85%" paddingAngle={2} stroke="none" isAnimationActive={false}>{series.costs.filter(row => row.value > 0).map(row => <Cell key={row.id} fill={row.color} />)}</Pie><Tooltip formatter={value => money(Number(value))} /></PieChart></ResponsiveContainer><div className="pointer-events-none absolute inset-0 flex flex-col items-center justify-center"><span className="text-xs text-slate-500">Gastos incluidos</span><strong className="text-xl text-[#310984]">{money(result.total.expense)}</strong></div></div> : <p className="py-10 text-center text-slate-500">Sin gastos incluidos en este periodo.</p>}
        <ul className="space-y-3">{series.costs.map(row => <li key={row.id} className="flex items-center justify-between gap-3 text-sm"><span className="flex items-center gap-2"><span className="h-2.5 w-2.5 shrink-0 rounded-full" style={{ background: row.color }} />{row.name}</span><span className="shrink-0 tabular-nums"><strong>{money(row.value)}</strong><span className="ml-2 text-xs text-slate-500">{result.total.expense ? (row.value / result.total.expense * 100).toFixed(1) : '0'} %</span></span></li>)}</ul>
      </section>
      <section className={panel} aria-label="Origen de los ingresos"><h2 className="text-lg font-semibold text-[#310984]">Origen de los ingresos</h2><p className={note}>Tarifas, suplementos y cada concepto externo, sin duplicarlos.</p>
        <div className="mt-5 space-y-5">{series.incomes.map(row => <button key={row.id} className="block w-full rounded-lg text-left focus-visible:outline focus-visible:outline-2 focus-visible:outline-violet-600" onClick={row.source === 'services' ? onServices : onIncomes}><span className="flex items-start justify-between gap-3 text-sm"><span className="min-w-0 break-words font-medium">{row.name}</span><strong className="shrink-0 tabular-nums">{money(row.value)}</strong></span><span className="mt-2 block h-2 overflow-hidden rounded-full bg-violet-50"><span className={`block h-full rounded-full ${row.source === 'services' ? 'bg-violet-700' : 'bg-violet-400'}`} style={{ width: `${result.total.revenue ? row.value / result.total.revenue * 100 : 0}%` }} /></span><span className="mt-1 flex justify-between text-xs text-slate-500"><span>{result.total.revenue ? (row.value / result.total.revenue * 100).toFixed(1) : 0} % del ingreso</span><span>Ver origen →</span></span></button>)}{!series.incomes.length && <p className="py-10 text-center text-slate-500">Sin ingresos contabilizados en este periodo.</p>}</div>
        <div className="mt-6 flex items-center justify-between border-t border-violet-100 pt-4 text-sm font-semibold text-[#310984]"><span>Total de ingresos</span><span>{money(result.total.revenue)}</span></div>
      </section>
    </div>
    <section className={panel} aria-label="Rentabilidad por cliente"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold text-[#310984]">Rentabilidad por cliente</h2><p className={note}>Pulsa un cliente para consultar sus propiedades, servicios e ingresos externos.</p></div><div className="flex gap-2"><Button size="sm" variant={metric === 'result' ? 'default' : 'outline'} aria-pressed={metric === 'result'} onClick={() => setMetric('result')}>Beneficio €</Button><Button size="sm" variant={metric === 'margin' ? 'default' : 'outline'} aria-pressed={metric === 'margin'} onClick={() => setMetric('margin')}>Margen %</Button></div></div>
      <div className="mt-5 max-h-[480px] space-y-2 overflow-y-auto pr-1">{clients.map(client => { const value = client[metric]; return <button key={client.id} aria-label={`Ver detalle de ${client.name}`} onClick={() => onClient(client.id)} className="grid w-full grid-cols-[1fr_auto] items-center gap-x-4 rounded-xl p-3 text-left hover:bg-violet-50 focus-visible:outline-violet-600 sm:grid-cols-[minmax(120px,1fr)_2fr_110px]"><span className="min-w-0 break-words text-sm font-medium">{client.name}{client.pending > 0 && <span className="block text-xs font-normal text-amber-800">Datos pendientes</span>}</span><span className="relative col-span-2 row-start-2 mt-2 h-4 rounded bg-slate-50 sm:col-span-1 sm:row-start-auto sm:mt-0" aria-hidden="true"><span className="absolute inset-y-0 left-1/2 border-l border-slate-300" /><span className={`absolute inset-y-0 rounded ${value !== null && value < 0 ? 'bg-rose-600' : 'bg-violet-600'}`} style={{ width: `${Math.abs(value ?? 0) / maxClient * 50}%`, left: value !== null && value < 0 ? `${50 - Math.abs(value) / maxClient * 50}%` : '50%' }} /></span><strong className={`text-right text-sm tabular-nums ${value !== null && value < 0 ? 'text-rose-700' : 'text-[#310984]'}`}>{value === null ? '—' : metric === 'result' ? money(value) : `${value.toFixed(1)} %`}</strong></button>; })}{!clients.length && <p className="py-6 text-center text-slate-500">No hay actividad vinculada a clientes en este periodo.</p>}</div>
      <p className="mt-4 border-t pt-3 text-xs text-slate-500">Actividad general sin repartir: {money(result.general.revenue)} de ingresos · {money(result.general.expense)} de gastos · {money(result.general.result)} de resultado.</p>
    </section>
    <section className={panel} aria-label="Revisar"><h2 className="flex items-center gap-2 text-lg font-semibold text-[#310984]"><CircleAlert className="h-5 w-5" />Revisar</h2><p className={note}>El resultado es provisional mientras falten costes. Los avisos pueden coincidir en un servicio.</p>
      <div className="my-4 flex flex-wrap gap-2">{([['low', `Margen bajo o negativo · ${low.length}`], ['pending', `Costes pendientes · ${pending.length + result.incomes.filter(i => i.pending.length).length}`], ['excluded', `Fuera del balance · ${result.excludedIncomeServices.length}`]] as const).map(([id, label]) => <Button key={id} variant={reviewMode === id ? 'default' : 'outline'} aria-pressed={reviewMode === id} onClick={() => setReviewMode(id)}>{label}</Button>)}</div>
      <div className="max-h-80 space-y-2 overflow-y-auto">{reviewMode === 'excluded' ? <><p className="text-sm text-slate-500">Estas tareas no suman ingresos ni gastos automáticos.</p>{result.excludedIncomeServices.map(row => <div key={row.id} className="flex flex-wrap justify-between gap-2 rounded-xl bg-slate-50 p-3 text-sm"><span>{row.propertyName} · {row.date.split('-').reverse().join('/')}</span><strong>{row.revenue === null ? 'Precio pendiente' : 'Sin ingreso'}</strong></div>)}{!result.excludedIncomeServices.length && <p className={note}>No hay servicios excluidos por falta de ingresos.</p>}</> : <>{reviewRows.map(row => <button key={row.id} onClick={() => onEdit(row)} className="flex w-full items-center justify-between gap-3 rounded-xl bg-slate-50 p-3 text-left text-sm hover:bg-violet-50"><span className="min-w-0"><strong>{row.propertyName}</strong><span className="block text-xs text-slate-500">{row.date.split('-').reverse().join('/')} · {row.clientName}</span>{reviewMode === 'pending' && <span className="block text-xs text-amber-800">{row.pending.join(' · ')}</span>}</span><span className="shrink-0 text-right"><strong className={(row.result ?? 0) < 0 ? 'text-rose-700' : 'text-amber-800'}>{money(row.result ?? 0)}</strong><span className="block text-xs">{((row.result ?? 0) / row.revenue! * 100).toFixed(1)} % · Revisar →</span></span></button>)}{reviewMode === 'pending' && result.incomes.filter(i => i.pending.length).map(row => <button key={row.id} onClick={onIncomes} className="block w-full rounded-xl bg-amber-50 p-3 text-left text-sm">{row.propertyName} · Coste externo pendiente →</button>)}{!reviewRows.length && !(reviewMode === 'pending' && result.incomes.some(i => i.pending.length)) && <p className="py-4 text-sm text-slate-500">{reviewMode === 'low' ? 'No hay servicios con pérdidas o margen inferior al 10 % entre los costes incluidos.' : 'No hay costes pendientes identificados en los registros incluidos.'}</p>}</>}</div>
    </section>
  </>;
}

export function FinancialTrend({ sedeId, settings, filters }: { sedeId: string; settings: FinanceSettings; filters: Filters }) {
  const [open, setOpen] = useState(false);
  const [matchingDays, setMatchingDays] = useState(true);
  const periods = trendPeriods(filters.end, matchingDays);
  const query = useFinancialData(open ? sedeId : undefined, periods[0]?.start || '', periods.at(-1)?.end || '');
  const rows = useMemo(() => monthlyTrend(query.data?.services || [], settings, filters, matchingDays), [query.data, settings, filters, matchingDays]);
  const current = rows.at(-1), previous = rows.at(-2);
  return <section className={panel} aria-label="Evolución mensual"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="flex items-center gap-2 text-lg font-semibold text-[#310984]"><TrendingUp className="h-5 w-5" />Evolución mensual</h2><p className={note}>Seis meses hasta el mes seleccionado, con los mismos filtros de cliente, propiedad y trabajador.</p></div><Button variant="outline" aria-expanded={open} onClick={() => setOpen(!open)}>{open ? 'Ocultar evolución' : 'Ver evolución mensual'}</Button></div>
      {open && <div className="mt-5 space-y-4"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={matchingDays} onChange={event => setMatchingDays(event.target.checked)} />Comparar del día 1 al {Number(filters.end.slice(8))} en cada mes</label><p className="text-xs text-slate-500">{matchingDays ? 'Los meses más cortos terminan en su último día.' : 'Comparación de meses completos; el mes en curso puede incluir tareas futuras.'} Esta vista utiliza meses propios, aunque arriba hayas elegido un intervalo personalizado.</p>
        {query.isPending ? <p role="status">Cargando evolución…</p> : query.error ? <div role="alert">No se pudo cargar la evolución. No se muestran comparaciones parciales. <Button variant="outline" onClick={() => query.refetch()}>Reintentar evolución</Button></div> : <>
          <div className="rounded-xl bg-amber-50 p-3 text-sm text-amber-900">Comparación provisional con tarifas actuales de las propiedades. Los ingresos puntuales solo cuentan si están registrados en ese mes; su ausencia no confirma ingreso cero. Revisa costes pendientes y registros manuales antes de comparar.</div>
          <div className="h-72" aria-hidden="true"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={rows} margin={{ left: 0, right: 8, top: 10 }}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#ede9fe" /><XAxis dataKey="name" tick={{ fontSize: 11 }} /><YAxis tickFormatter={shortMoney} width={65} tick={{ fontSize: 11 }} /><Tooltip formatter={value => money(Number(value))} /><Legend /><ReferenceLine y={0} stroke="#94a3b8" /><Bar name="Ingresos" dataKey="revenue" fill="#310984" radius={[4, 4, 0, 0]} isAnimationActive={false} /><Bar name="Gastos" dataKey="expense" fill="#c4b5fd" radius={[4, 4, 0, 0]} isAnimationActive={false} /><Line name="Resultado" dataKey="result" stroke="#047857" strokeWidth={3} isAnimationActive={false} /></ComposedChart></ResponsiveContainer></div>
          {current && previous && <div className="grid gap-3 sm:grid-cols-3">{(['revenue', 'expense', 'result'] as const).map((key, index) => { const delta = current[key] - previous[key]; return <div key={key} className="rounded-xl bg-violet-50 p-3 text-sm"><p>{['Ingresos', 'Gastos', 'Resultado'][index]} · {current.name} frente a {previous.name}</p><strong className="mt-1 flex items-center gap-1 text-[#310984]">{delta < 0 ? <ArrowDownRight className="h-4 w-4" /> : <ArrowUpRight className="h-4 w-4" />}{delta > 0 ? '+' : ''}{money(delta)}</strong></div>; })}</div>}
          <div className="overflow-x-auto"><table className="w-full text-sm"><caption className="sr-only">Detalle de evolución mensual sin IVA</caption><thead><tr>{['Periodo', 'Ingresos', 'Gastos', 'Resultado', 'Costes / precios pendientes', 'Ingresos puntuales'].map(label => <th className="p-2 text-left" key={label}>{label}</th>)}</tr></thead><tbody>{rows.map(row => <tr key={row.start} className="border-t"><th className="whitespace-nowrap p-2 text-left font-normal">{row.start.split('-').reverse().join('/')} – {row.end.split('-').reverse().join('/')}</th><td className="p-2">{money(row.revenue)}</td><td className="p-2">{money(row.expense)}</td><td className="p-2">{money(row.result)}</td><td className="p-2">{row.pending} / {row.excludedPrices}</td><td className="p-2">{row.manualCount || 'Ninguno registrado'}</td></tr>)}</tbody></table></div>
          <Button variant="outline" disabled={query.isFetching} onClick={() => query.refetch()}>{query.isFetching ? 'Actualizando evolución…' : 'Actualizar evolución'}</Button>
        </>}
      </div>}
  </section>;
}

export function ExternalIncomeDetail({ result, onManage }: { result: FinancialAnalysis; onManage: () => void }) {
  if (!result.incomes.length) return null;
  return <section className={panel}><div className="mb-4 flex flex-wrap items-center justify-between gap-2"><h2 className="font-semibold text-[#310984]">Ingresos externos de esta selección</h2><Button variant="outline" onClick={onManage}>Gestionar ingresos<ChevronRight className="ml-1 h-4 w-4" /></Button></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr>{['Concepto', 'Ingresos', 'Gastos', 'Resultado provisional'].map(label => <th key={label} className="p-2 text-left">{label}</th>)}</tr></thead><tbody>{result.incomes.map(row => <tr key={row.id} className="border-t"><th className="p-2 text-left font-normal">{row.propertyName}<span className="block text-xs text-slate-500">{row.date.slice(0, 7)}{row.pending.length > 0 && ' · Coste pendiente'}</span></th><td className="p-2">{money(row.revenue ?? 0)}</td><td className="p-2">{money(row.expense)}</td><td className="p-2">{money(row.result ?? 0)}</td></tr>)}</tbody></table></div><p className="mt-3 text-xs text-slate-500">Los fijos mensuales se prorratean por los días seleccionados. Estos importes ya están incluidos en las tarjetas superiores.</p></section>;
}
