import { useMemo, useState } from 'react';
import { ChevronRight, CircleAlert } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { dashboardSeries, money, balanceColumns, periodColumns, type FinancialAnalysis } from './financialCharts';
import type { CalculatedService } from './financialModel';
import type { DirectoryEntry } from './financialSource';
import { FinancialColumns } from './FinancialColumns';
import { financialName, percent } from './financialFormat';
import { FinancialClientChart } from './FinancialClientChart';
import { FinancialExpenseShare } from './FinancialExpenseShare';
import { FinancialHelp } from './FinancialHelp';
import type { Allocation } from './financialAnalytics';
export { FinancialTrend, type FinancialTrendView } from './FinancialEvolution';

const panel = 'min-w-0 rounded-2xl border border-violet-100 bg-white p-5 shadow-sm sm:p-6';
const note = 'text-sm leading-relaxed text-slate-500';
type Props = { result: FinancialAnalysis; names: DirectoryEntry[]; onClient: (id: string) => void; onServices: () => void; onIncomes: () => void; onEdit: (service: CalculatedService) => void; onDetails: (id: string) => void; allocation?: Allocation; assigned?: number };

export function FinancialDashboard({ result, names, onClient, onServices, onIncomes, onEdit, onDetails, allocation = 'none', assigned = 0 }: Props) {
  const series = useMemo(() => dashboardSeries(result), [result]);
  const comparison = useMemo(() => periodColumns(result.total), [result.total]);
  const [metric, setMetric] = useState<'result' | 'margin'>('result');
  const clients = [...result.clients].map(client => ({ ...client, name: names.find(entry => entry.id === client.id)?.name || client.name })).sort((a, b) => (b[metric] ?? -Infinity) - (a[metric] ?? -Infinity));
  const low = result.services.filter(service => service.revenue! > 0 && (service.result ?? 0) / service.revenue! < .1);
  const pending = result.services.filter(service => service.pending.length);
  const [reviewMode, setReviewMode] = useState<'low' | 'pending' | 'excluded'>('low');
  const reviewRows = reviewMode === 'low' ? low : pending;
  return <>
    <section className={panel} aria-label="Comparativa del periodo">
      <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold text-[#310984]">Comparativa del periodo</h2></div><span className={`rounded-full px-3 py-1 text-sm font-medium ${result.total.result < 0 ? 'bg-rose-50 text-rose-800' : 'bg-emerald-50 text-emerald-800'}`}>{result.total.result < 0 ? 'Resultado negativo' : 'Resultado provisional'} · {money(result.total.result)}</span><FinancialHelp section="Comparativa del periodo"><p>Ingresos y gastos adyacentes en la misma escala y sin IVA. Pulsa una barra o la leyenda para abrir su desglose; en móvil puedes deslizar el gráfico.</p><p aria-label="Desglose de Personal">Personal incluye <strong>{money(result.total.costs.personal)}</strong> de actividad y otros costes de personal, más <strong>{money(result.total.costs.salary)}</strong> de dirección y estructura.</p><p>Gastos generales incluidos una vez, según la opción de reparto seleccionada.</p></FinancialHelp></div>
      <FinancialColumns label="Ingresos y gastos del periodo" series={comparison.series} groups={[{ name: 'Periodo seleccionado', values: comparison.values }]} onSelect={onDetails} />
      <ol className="mt-5 grid gap-3 text-sm sm:grid-cols-3">{balanceColumns.map(column => <li key={column.id} className="rounded-xl bg-slate-50 p-3"><span className="mb-1 flex items-center gap-2 text-xs text-slate-600"><span className="h-2 w-2 shrink-0 rounded-full" style={{ background: column.color }} />{column.name}</span><strong className="tabular-nums">{money(result.total[column.id])}</strong></li>)}</ol>
      <p className="mt-4 text-xs text-slate-500">{allocation === 'none' ? <>Gastos generales incluidos: <strong>{money(result.general.expense)}</strong>. Se cuentan una vez y no se reparten entre clientes.</> : <>Gastos generales repartidos en esta selección: <strong>{money(assigned)}</strong> · Actividad general restante: <strong>{money(result.general.expense)}</strong>. El balance de toda la sede se conserva.</>}</p>
    </section>
    <div className="grid gap-5 xl:grid-cols-2">
      <section className={panel} aria-label="Distribución de gastos"><div className="flex flex-wrap items-start justify-between gap-2"><h2 className="text-lg font-semibold text-[#310984]">Distribución de gastos</h2><FinancialHelp section="Distribución de gastos"><p>Peso porcentual de cada categoría sobre el gasto total sin IVA. Personal incluye dirección y estructura.</p><p>Pulsa una categoría o un segmento para abrir su desglose. Los importes proceden del mismo análisis que la comparativa.</p></FinancialHelp></div>
        <FinancialExpenseShare rows={series.costs} total={result.total.expense} onDetails={onDetails} />
      </section>
      <section className={panel} aria-label="Origen de los ingresos"><div className="flex flex-wrap items-start justify-between gap-2"><h2 className="text-lg font-semibold text-[#310984]">Origen de los ingresos</h2><FinancialHelp section="Origen de los ingresos"><p>Tarifas base, suplementos, paños y conceptos externos, sin duplicarlos y sin IVA.</p><p>Una columna por concepto, en la misma escala. Pulsa la barra o leyenda para abrir el desglose; «Ver origen» abre servicios o ingresos externos.</p></FinancialHelp></div>
        <FinancialColumns label="Tipos de ingreso del periodo" series={series.incomes} groups={[{ name: 'Periodo seleccionado', values: Object.fromEntries(series.incomes.map(row => [row.id, row.value])) }]} onSelect={onDetails} />
        <div className="mt-5 space-y-5">{series.incomes.map(row => <button key={row.id} className="block w-full rounded-lg text-left focus-visible:outline focus-visible:outline-2 focus-visible:outline-violet-600" onClick={row.source === 'services' ? onServices : onIncomes}><span className="flex items-start justify-between gap-3 text-sm"><span className="flex min-w-0 items-center gap-2 break-words font-medium"><span className="h-2.5 w-2.5 shrink-0 rounded-sm" style={{ background: row.color }} />{row.name}</span><strong className="shrink-0 tabular-nums">{money(row.value)}</strong></span><span className="mt-1 flex justify-between text-xs text-slate-500"><span>{percent(result.total.revenue ? row.value / result.total.revenue * 100 : 0)} del ingreso</span><span>Ver origen →</span></span></button>)}{!series.incomes.length && <p className="py-10 text-center text-slate-500">Sin ingresos contabilizados en este periodo.</p>}</div>
        <div className="mt-6 flex items-center justify-between border-t border-violet-100 pt-4 text-sm font-semibold text-[#310984]"><span>Total de ingresos</span><span>{money(result.total.revenue)}</span></div>
      </section>
    </div>
    <section className={panel} aria-label="Rentabilidad por cliente"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold text-[#310984]">Rentabilidad por cliente</h2><FinancialHelp section="Rentabilidad por cliente"><p>Resultado incluido en euros o margen sobre ingresos. Verde indica resultado positivo; rojo, negativo. El cero es el origen de todas las barras.</p><p>Pulsa un cliente para consultar sus servicios e ingresos externos. Los gastos generales siguen la opción de reparto seleccionada. El remanente se muestra aparte. Todos los resultados son provisionales.</p></FinancialHelp></div><div className="flex gap-2"><Button size="sm" variant={metric === 'result' ? 'default' : 'outline'} aria-pressed={metric === 'result'} onClick={() => setMetric('result')}>Beneficio €</Button><Button size="sm" variant={metric === 'margin' ? 'default' : 'outline'} aria-pressed={metric === 'margin'} onClick={() => setMetric('margin')}>Margen %</Button></div></div>
      {clients.length ? <FinancialClientChart clients={clients} metric={metric} onClient={onClient} /> : <p className="py-6 text-center text-slate-500">No hay actividad vinculada a clientes en este periodo.</p>}
      <p className="mt-4 border-t pt-3 text-xs text-slate-500">Actividad general sin repartir: {money(result.general.revenue)} de ingresos · {money(result.general.expense)} de gastos · {money(result.general.result)} de resultado.</p>
    </section>
    <section className={panel} aria-label="Revisar"><h2 className="flex items-center gap-2 text-lg font-semibold text-[#310984]"><CircleAlert className="h-5 w-5" />Revisar</h2><p className={note}>El resultado es provisional mientras falten costes. Los avisos pueden coincidir en un servicio.</p>
      <div className="my-4 flex flex-wrap gap-2">{([['low', `Margen bajo o negativo · ${low.length}`], ['pending', `Costes pendientes · ${pending.length + result.incomes.filter(i => i.pending.length).length}`], ['excluded', `Fuera del balance · ${result.excludedIncomeServices.length}`]] as const).map(([id, label]) => <Button key={id} variant={reviewMode === id ? 'default' : 'outline'} aria-pressed={reviewMode === id} onClick={() => setReviewMode(id)}>{label}</Button>)}</div>
      <div className="max-h-80 space-y-2 overflow-y-auto">{reviewMode === 'excluded' ? <><p className="text-sm text-slate-500">Estas tareas no suman ingresos ni gastos automáticos.</p>{result.excludedIncomeServices.map(row => <div key={row.id} className="flex flex-wrap justify-between gap-2 rounded-xl bg-slate-50 p-3 text-sm"><span>{financialName(row.propertyName)} · {row.date.split('-').reverse().join('/')}</span><strong>{row.revenue === null ? 'Precio pendiente' : 'Sin ingreso'}</strong></div>)}{!result.excludedIncomeServices.length && <p className={note}>No hay servicios excluidos por falta de ingresos.</p>}</> : <>{reviewRows.map(row => <button key={row.id} onClick={() => onEdit(row)} className="flex w-full items-center justify-between gap-3 rounded-xl bg-slate-50 p-3 text-left text-sm hover:bg-violet-50"><span className="min-w-0"><strong>{financialName(row.propertyName)}</strong><span className="block text-xs text-slate-500">{row.date.split('-').reverse().join('/')} · {financialName(row.clientName)}</span>{reviewMode === 'pending' && <span className="block text-xs text-amber-800">{row.pending.join(' · ')}</span>}</span><span className="shrink-0 text-right"><strong className={(row.result ?? 0) < 0 ? 'text-rose-700' : 'text-amber-800'}>{money(row.result ?? 0)}</strong><span className="block text-xs">{percent((row.result ?? 0) / row.revenue! * 100)} · Revisar →</span></span></button>)}{reviewMode === 'pending' && result.incomes.filter(i => i.pending.length).map(row => <button key={row.id} onClick={onIncomes} className="block w-full rounded-xl bg-amber-50 p-3 text-left text-sm">{financialName(row.propertyName)} · Coste externo pendiente →</button>)}{!reviewRows.length && !(reviewMode === 'pending' && result.incomes.some(i => i.pending.length)) && <p className="py-4 text-sm text-slate-500">{reviewMode === 'low' ? 'No hay servicios con pérdidas o margen inferior al 10 % entre los costes incluidos.' : 'No hay costes pendientes identificados en los registros incluidos.'}</p>}</>}</div>
    </section>
  </>;
}

export function ExternalIncomeDetail({ result, onManage }: { result: FinancialAnalysis; onManage: () => void }) {
  if (!result.incomes.length) return null;
  return <section className={panel}><div className="mb-4 flex flex-wrap items-center justify-between gap-2"><h2 className="font-semibold text-[#310984]">Ingresos externos de esta selección</h2><Button variant="outline" onClick={onManage}>Gestionar ingresos<ChevronRight className="ml-1 h-4 w-4" /></Button></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr>{['Concepto', 'Ingresos', 'Gastos', 'Resultado provisional'].map(label => <th key={label} className="p-2 text-left">{label}</th>)}</tr></thead><tbody>{result.incomes.map(row => <tr key={row.id} className="border-t"><th className="p-2 text-left font-normal">{financialName(row.propertyName)}<span className="block text-xs text-slate-500">{row.date.slice(0, 7)}{row.pending.length > 0 && ' · Coste pendiente'}</span></th><td className="p-2 tabular-nums">{money(row.revenue ?? 0)}</td><td className="p-2 tabular-nums">{money(row.expense)}</td><td className="p-2 tabular-nums">{money(row.result ?? 0)}</td></tr>)}</tbody></table></div><p className="mt-3 text-xs text-slate-500">Los fijos mensuales se prorratean por los días seleccionados. Estos importes ya están incluidos en las tarjetas superiores.</p></section>;
}
