import { useMemo, useState } from 'react';
import { Button } from '@/components/ui/button';
import { FinancialClientChart } from './FinancialClientChart';
import { FinancialHelp } from './FinancialHelp';
import { financialName, money, percent } from './financialFormat';
import { sortFinancialClients, type ClientSort } from './financialClientSorting';
import { operationalKpis, propertyResults } from './financialAnalytics';
import type { FinancialAnalysis } from './financialCharts';
import type { DirectoryEntry } from './financialSource';

const panel = 'min-w-0 rounded-2xl border border-violet-100 bg-white p-5 shadow-sm';
export function FinancialPropertyAnalysis({ result, properties, onProperty }: { result: FinancialAnalysis; properties: DirectoryEntry[]; onProperty: (id: string) => void }) {
  const rows = useMemo(() => propertyResults(result, properties), [result, properties]);
  const kpis = operationalKpis(result, rows);
  const [sort, setSort] = useState<{ key: ClientSort; descending: boolean }>({ key: 'margin', descending: false });
  const [page, setPage] = useState(1);
  const ordered = sortFinancialClients(rows, sort.key, sort.descending), current = Math.min(page, Math.max(1, Math.ceil(rows.length / 10)));
  const ranked = sortFinancialClients(rows.filter(row => row.margin !== null), 'margin', true);
  const cards = [
    ['Ingreso medio por propiedad', kpis.revenuePerProperty === null ? '—' : money(kpis.revenuePerProperty), `${rows.length} propiedades con actividad`],
    ['Coste directo medio de limpieza', kpis.cleaningCost === null ? '—' : money(kpis.cleaningCost), 'Solo limpiezas contabilizadas'],
    ['Margen de las propiedades', percent(kpis.propertyMargin), 'Ponderado por sus ingresos'],
    ['Personal sobre ingresos', percent(kpis.personnelShare), 'Incluye dirección y estructura'],
    ['Lavandería por servicio', kpis.laundryPerService === null ? '—' : money(kpis.laundryPerService), 'Coste directo · sin lavandería externa'],
  ];
  const headings: { key: ClientSort; label: string }[] = [{ key: 'name', label: 'Propiedad' }, { key: 'revenue', label: 'Ingresos' }, { key: 'expense', label: 'Gastos' }, { key: 'result', label: 'Resultado' }, { key: 'margin', label: 'Margen' }];
  return <section className="space-y-5" aria-label="Análisis por propiedad">
    <div className="flex flex-wrap items-center justify-between gap-2"><h2 className="text-xl font-semibold text-[#310984]">Actividad y rentabilidad por propiedad</h2><FinancialHelp section="Propiedades"><p>Ingreso medio: ingresos vinculados a propiedades con actividad, dividido entre esas propiedades. El margen es ponderado por ingresos; no es una media de porcentajes.</p><p>Coste de limpieza y lavandería por servicio usan costes directos de tareas contabilizadas. Excluyen ingresos externos y gastos generales. Personal sobre ingresos sí incluye estructura y dirección según los filtros.</p><p>La tabla incluye los gastos adicionales vinculados a cada propiedad y su reparto cuando esté seleccionado. Los importes sin propiedad permanecen en el balance general. Rankings provisionales, ordenados por porcentaje de margen.</p></FinancialHelp></div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{cards.map(([label, value, note]) => <article key={label} className={panel}><h3 className="text-xs font-medium text-slate-600">{label}</h3><p className="mt-3 text-xl font-semibold text-[#310984] tabular-nums">{value}</p><p className="mt-2 text-xs text-slate-500">{note}</p></article>)}</div>
    <div className="grid gap-5 xl:grid-cols-2">{[{ title: '5 mejores márgenes', list: ranked.slice(0, 5) }, { title: '5 menores márgenes', list: [...ranked].reverse().slice(0, 5) }].map(({ title, list }) => <div key={title} className={panel}><h3 className="text-base font-semibold text-[#310984]">{title}</h3>{list.length ? <FinancialClientChart label={`Gráfico de propiedades · ${title}`} clients={list} metric="margin" onClient={onProperty} /> : <p className="py-8 text-sm text-slate-500">Sin propiedades con ingreso para comparar.</p>}</div>)}</div>
    <div className={panel}><div className="overflow-x-auto"><table className="w-full text-sm"><caption className="mb-3 text-left font-semibold text-[#310984]">Resultados por propiedad · sin IVA</caption><thead className="bg-violet-50 text-[#310984]"><tr>{headings.map(column => <th key={column.key} scope="col" className="p-3 text-left" aria-sort={sort.key === column.key ? sort.descending ? 'descending' : 'ascending' : 'none'}><button className="whitespace-nowrap hover:underline" onClick={() => { setSort({ key: column.key, descending: sort.key === column.key ? !sort.descending : false }); setPage(1); }} aria-label={`Ordenar propiedades por ${column.label}`}>{column.label}{sort.key === column.key && (sort.descending ? ' ↓' : ' ↑')}</button></th>)}<th scope="col" className="p-3">Servicios</th><th scope="col" className="p-3">Gasto repartido</th></tr></thead><tbody>{ordered.slice((current - 1) * 10, current * 10).map(row => <tr key={row.id} className="border-b border-violet-50"><th className="p-3 text-left font-medium" scope="row"><button className="text-[#310984] hover:underline" onClick={() => onProperty(row.id)}>{financialName(row.name)}</button>{row.pending > 0 && <span className="block text-xs text-amber-700">{row.pending} registros incompletos</span>}</th>{[row.revenue, row.expense, row.result].map((value, index) => <td key={index} className={`whitespace-nowrap p-3 text-right tabular-nums ${index === 2 ? value < 0 ? 'text-rose-700' : 'text-emerald-700' : ''}`}>{money(value)}</td>)}<td className={`p-3 text-right tabular-nums ${row.margin !== null && row.margin < 0 ? 'text-rose-700' : 'text-emerald-700'}`}>{percent(row.margin)}</td><td className="p-3 text-right tabular-nums">{row.services}</td><td className="whitespace-nowrap p-3 text-right tabular-nums">{money(row.allocated)}</td></tr>)}{!rows.length && <tr><td colSpan={7} className="p-8 text-center text-slate-500">Sin actividad vinculada a propiedades con estos filtros.</td></tr>}</tbody><tfoot className="bg-violet-50 font-semibold"><tr><th className="p-3 text-left">Total de propiedades</th>{['revenue', 'expense', 'result'].map(key => <td key={key} className="whitespace-nowrap p-3 text-right tabular-nums">{money(rows.reduce((sum, row) => sum + row[key], 0))}</td>)}<td className="p-3 text-right tabular-nums">{percent(kpis.propertyMargin)}</td><td className="p-3 text-right">{rows.reduce((sum, row) => sum + row.services, 0)}</td><td className="p-3 text-right tabular-nums">{money(rows.reduce((sum, row) => sum + row.allocated, 0))}</td></tr></tfoot></table></div>
      <div className="mt-4 flex flex-wrap items-center justify-between gap-3 text-xs text-slate-500"><span>{rows.length} propiedades · Totales de todas las páginas</span><div className="flex items-center gap-2"><Button size="sm" variant="outline" aria-label="Página anterior de propiedades" disabled={current <= 1} onClick={() => setPage(current - 1)}>Anterior</Button><span>{current} / {Math.max(1, Math.ceil(rows.length / 10))}</span><Button size="sm" variant="outline" aria-label="Página siguiente de propiedades" disabled={current * 10 >= rows.length} onClick={() => setPage(current + 1)}>Siguiente</Button></div></div>
      <p className="mt-3 text-xs text-slate-500">Ingresos sin propiedad: {money(result.total.revenue - rows.reduce((sum, row) => sum + row.revenue, 0))} · Gastos sin propiedad: {money(result.total.expense - rows.reduce((sum, row) => sum + row.expense, 0))}. Incluidos en el balance general.</p>
    </div>
  </section>;
}
