import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { FinancialHelp } from './FinancialHelp';
import { financialAlerts, type AlertRules } from './financialAnalytics';
import { financialName, money, percent } from './financialFormat';
import type { FinancialAnalysis } from './financialCharts';
import type { CalculatedService, FinancialService } from './financialModel';
import type { DirectoryEntry } from './financialSource';

export function FinancialAlerts({ result, rules, today, clients, onRules, onClient, onEdit, onIncomes, onExcluded }: { result: FinancialAnalysis; rules: AlertRules; today: string; clients: DirectoryEntry[]; onRules: (rules: AlertRules) => void; onClient: (id: string) => void; onEdit: (service: CalculatedService) => void; onIncomes: () => void; onExcluded: (service: FinancialService) => void }) {
  const alerts = financialAlerts(result, rules, today);
  return <section className="min-w-0 space-y-4 rounded-2xl border border-violet-100 bg-white p-5 shadow-sm" aria-label="Alertas financieras">
    <div className="flex flex-wrap items-center justify-between gap-2"><h2 className="text-lg font-semibold text-[#310984]">Alertas financieras</h2><FinancialHelp section="Alertas"><p>Avisos locales del análisis y de sus filtros. Los umbrales se conservan para esta cuenta y sede en esta pestaña; no envían notificaciones.</p><p>Antigüedad desde la fecha del servicio, en días naturales de Madrid. Solo se avisa si supera el límite; las tareas futuras no se consideran antiguas. Los avisos de margen se calculan con los costes incluidos y el reparto seleccionado.</p><p>Los ingresos cero se muestran para revisar, pero siguen fuera del balance sin generar gastos automáticos.</p></FinancialHelp></div>
    <div className="grid items-end gap-3 sm:grid-cols-3"><label className="text-sm">Avisar si el margen del cliente es inferior a (%)<Input type="number" min="-100" max="100" step="0.1" value={rules.margin} onChange={event => { const margin = Number(event.target.value); if (event.target.value !== '' && Number.isFinite(margin) && margin >= -100 && margin <= 100) onRules({ ...rules, margin }); }} /></label><label className="text-sm">Costes pendientes con más de (días)<Input type="number" min="0" max="3650" step="1" value={rules.days} onChange={event => { const days = Number(event.target.value); if (event.target.value !== '' && Number.isInteger(days) && days >= 0 && days <= 3650) onRules({ ...rules, days }); }} /></label><label className="flex min-h-10 items-center gap-2 text-sm"><input type="checkbox" checked={rules.zero} onChange={event => onRules({ ...rules, zero: event.target.checked })} />Avisar de servicios con ingreso cero</label></div>
    <div className="grid gap-4 lg:grid-cols-3">
      <div className="rounded-xl bg-rose-50 p-4"><h3 className="text-sm font-semibold text-rose-900">Clientes con margen bajo · {alerts.clients.length}</h3><ul className="mt-3 max-h-64 space-y-2 overflow-auto">{alerts.clients.map(row => <li key={row.id}><button className="flex w-full justify-between gap-2 rounded-md p-1 text-left text-sm text-rose-900 hover:bg-rose-100" onClick={() => onClient(row.id)}><span>{financialName(clients.find(client => client.id === row.id)?.name || row.name)}</span><strong className="tabular-nums">{percent(row.margin)}</strong></button></li>)}</ul>{!alerts.clients.length && <p className="mt-3 text-xs text-slate-600">Sin clientes bajo este umbral.</p>}</div>
      <div className="rounded-xl bg-amber-50 p-4"><h3 className="text-sm font-semibold text-amber-900">Costes pendientes antiguos · {alerts.pending.length}</h3><ul className="mt-3 max-h-64 space-y-2 overflow-auto">{alerts.pending.map(row => <li key={row.id}><Button variant="ghost" className="h-auto w-full whitespace-normal justify-start p-1 text-left" onClick={row.type === 'external-income' ? onIncomes : () => onEdit(row)}><span>{financialName(row.propertyName)}<span className="block text-xs font-normal">{row.date} · {row.age} días · {row.pending.join(' · ')}</span></span></Button></li>)}</ul>{!alerts.pending.length && <p className="mt-3 text-xs text-slate-600">Sin costes pendientes que superen el límite.</p>}</div>
      <div className="rounded-xl bg-slate-50 p-4"><h3 className="text-sm font-semibold text-slate-700">Servicios con ingreso cero · {alerts.zero.length}</h3><ul className="mt-3 max-h-64 space-y-2 overflow-auto">{alerts.zero.map(row => <li key={row.id}><button className="block w-full rounded-md p-1 text-left text-sm hover:bg-violet-50" onClick={() => onExcluded(row)}>{financialName(row.propertyName)}<span className="block text-xs text-slate-500">{row.date} · {money(0)} · fuera del balance</span></button></li>)}</ul>{!alerts.zero.length && <p className="mt-3 text-xs text-slate-600">{rules.zero ? 'Sin servicios con ingreso cero.' : 'Aviso desactivado.'}</p>}</div>
    </div>
  </section>;
}
