import { useMemo } from 'react';
import { TrendingUp } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { FinancialColumns } from './FinancialColumns';
import { FinancialLines } from './FinancialLines';
import { FinancialHelp } from './FinancialHelp';
import { monthlyTrend, monthlyColumns, type ComparisonView } from './financialCharts';
import { money } from './financialFormat';
import type { Filters, FinanceSettings, FinancialService } from './financialModel';

export interface FinancialTrendView { open: boolean; matchingDays: boolean; comparison: ComparisonView; chart: 'lines' | 'columns' }
export function FinancialTrend({ services, settings, filters, view, onViewChange, onDetails }: {
  services: FinancialService[]; settings: FinanceSettings; filters: Filters; view: FinancialTrendView;
  onViewChange: (patch: Partial<FinancialTrendView>) => void; onDetails: (id: string, period: Pick<Filters, 'start' | 'end'>) => void;
}) {
  const { open, matchingDays, comparison, chart } = view;
  const rows = useMemo(() => monthlyTrend(services, settings, filters, matchingDays, 12), [services, settings, filters, matchingDays]);
  const columns = useMemo(() => monthlyColumns(rows, comparison), [rows, comparison]);
  return <section className="min-w-0 rounded-2xl border border-violet-100 bg-white p-5 shadow-sm sm:p-6" aria-label="Evolución mensual">
    <div className="flex flex-wrap items-start justify-between gap-3"><h2 className="flex items-center gap-2 text-lg font-semibold text-[#310984]"><TrendingUp aria-hidden className="h-5 w-5" />Evolución mensual</h2><div className="flex flex-wrap items-center gap-2"><FinancialHelp section="Evolución mensual"><p>Doce meses hasta el mes seleccionado, con los mismos filtros. Importes sin IVA y tarifas actuales de las propiedades.</p><p>{matchingDays ? `Del día 1 al ${Number(filters.end.slice(8))} de cada mes, limitado al último día de los meses cortos.` : 'Comparación de meses completos; el mes en curso puede incluir tareas futuras.'} Esta evolución utiliza sus propios meses aunque el periodo superior sea personalizado.</p><p>Personal incluye dirección y estructura. En columnas, cada barra abre ese concepto y mes; la leyenda abre el último mes. En líneas, la leyenda permite mostrar u ocultar series. En móvil se puede deslizar el gráfico.</p><p>Comparación provisional: los ingresos puntuales solo cuentan si están registrados; su ausencia no confirma ingreso real cero. Revisa los costes pendientes y las entradas manuales.</p></FinancialHelp><Button variant="outline" size="sm" aria-expanded={open} onClick={() => onViewChange({ open: !open })}>{open ? 'Ocultar evolución' : 'Ver evolución mensual'}</Button></div></div>
    {open && <div className="mt-5 space-y-4">
      <div className="flex flex-wrap items-center justify-between gap-3"><div className="flex gap-2"><Button size="sm" variant={chart === 'lines' ? 'default' : 'outline'} aria-pressed={chart === 'lines'} onClick={() => onViewChange({ chart: 'lines' })}>Líneas</Button><Button size="sm" variant={chart === 'columns' ? 'default' : 'outline'} aria-pressed={chart === 'columns'} onClick={() => onViewChange({ chart: 'columns' })}>Columnas</Button></div><label className="flex items-center gap-2 text-xs text-slate-600"><input type="checkbox" checked={matchingDays} onChange={event => onViewChange({ matchingDays: event.target.checked })} />Comparar del día 1 al {Number(filters.end.slice(8))} en cada mes</label></div>
      {chart === 'lines' ? <FinancialLines rows={rows} /> : <><div className="flex flex-wrap gap-2" aria-label="Conceptos de la evolución">{([['balance', 'Balance'], ['costs', 'Tipos de gasto'], ['incomes', 'Origen de ingresos']] as const).map(([id, label]) => <Button size="sm" key={id} variant={comparison === id ? 'default' : 'outline'} aria-pressed={comparison === id} onClick={() => onViewChange({ comparison: id })}>{label}</Button>)}</div><FinancialColumns label="Comparación mensual por conceptos" series={columns.series} groups={columns.groups} onSelect={(id, index) => { const period = rows[index ?? rows.length - 1]; if (period) onDetails(id, { start: period.start, end: period.end }); }} /></>}
      <details className="border-t border-violet-100 pt-3"><summary className="cursor-pointer text-sm font-medium text-[#310984]">Datos de la evolución · 12 meses</summary><div className="mt-3 overflow-x-auto"><table className="w-full text-sm"><caption className="sr-only">Detalle de evolución mensual sin IVA</caption><thead className="bg-violet-50 text-[#310984]"><tr>{['Periodo', 'Ingresos', 'Gastos', 'Resultado', 'Costes / precios pendientes', 'Ingresos puntuales'].map(label => <th scope="col" className="whitespace-nowrap p-2 text-left" key={label}>{label}</th>)}</tr></thead><tbody>{rows.map(row => <tr key={row.start} className="border-b border-violet-50"><th scope="row" className="whitespace-nowrap p-2 text-left font-normal"><button className="text-[#310984] hover:underline focus-visible:outline-violet-600" onClick={() => onDetails('revenue', { start: row.start, end: row.end })}>{row.start.split('-').reverse().join('/')} – {row.end.split('-').reverse().join('/')}</button></th><td className="p-2 text-right tabular-nums">{money(row.revenue)}</td><td className="p-2 text-right tabular-nums">{money(row.expense)}</td><td className={`p-2 text-right tabular-nums ${row.result < 0 ? 'text-rose-700' : 'text-emerald-700'}`}>{money(row.result)}</td><td className="p-2 tabular-nums">{row.pending} / {row.excludedPrices}</td><td className="whitespace-nowrap p-2">{row.manualCount || 'Ninguno registrado'}</td></tr>)}</tbody></table></div></details>
    </div>}
  </section>;
}
