import * as z from 'zod';

export const propertySchema = z.object({
  codigo: z.string().optional().default(''),
  nombre: z.string().min(1, 'El nombre es obligatorio'),
  direccion: z.string().min(1, 'La direccion es obligatoria'),
  numeroCamas: z.number().min(0, 'El numero de camas debe ser positivo'),
  numeroCamasPequenas: z.number().min(0, 'El numero de camas pequenas debe ser positivo'),
  numeroCamasSuite: z.number().min(0, 'El numero de camas suite debe ser positivo'),
  numeroSofasCama: z.number().min(0, 'El numero de sofas cama debe ser positivo'),
  numeroBanos: z.number().min(1, 'Debe tener al menos 1 bano'),
  numeroCocinas: z.number().min(0, 'El numero de cocinas debe ser positivo'),
  duracionServicio: z.number().min(15, 'La duracion minima es 15 minutos'),
  costeServicio: z.number().min(0, 'El coste debe ser positivo'),
  checkInPredeterminado: z.string().min(1, 'El check-in es obligatorio'),
  checkOutPredeterminado: z.string().min(1, 'El check-out es obligatorio'),
  numeroSabanas: z.number().min(0, 'El numero de sabanas debe ser positivo'),
  numeroSabanasRequenas: z.number().min(0, 'El numero de sabanas pequenas debe ser positivo'),
  numeroSabanasSuite: z.number().min(0, 'El numero de sabanas suite debe ser positivo'),
  numeroToallasGrandes: z.number().min(0, 'El numero de toallas grandes debe ser positivo'),
  numeroTotallasPequenas: z.number().min(0, 'El numero de toallas pequenas debe ser positivo'),
  numeroAlfombrines: z.number().min(0, 'El numero de alfombrines debe ser positivo'),
  numeroFundasAlmohada: z.number().min(0, 'El numero de fundas de almohada debe ser positivo'),
  kitAlimentario: z.number().min(0, 'El numero de kits alimentarios debe ser positivo'),
  amenitiesBano: z.number().min(0, 'El numero de amenities de bano debe ser positivo'),
  amenitiesCocina: z.number().min(0, 'El numero de amenities de cocina debe ser positivo'),
  cantidadRollosPapelHigienico: z.number().min(0, 'La cantidad de rollos de papel higienico debe ser positiva'),
  cantidadRollosPapelCocina: z.number().min(0, 'La cantidad de rollos de papel de cocina debe ser positiva'),
  bayetasCocina: z.number().min(0, 'La cantidad de panos de cocina debe ser positiva').optional().default(0),
  bolsasBasura: z.number().min(0, 'La cantidad de bolsas de basura debe ser positiva').optional().default(0),
  stockConsumptions: z.record(z.number().min(0, 'La cantidad debe ser positiva')).optional().default({}),
  notas: z.string().optional(),
  clienteId: z.string().min(1, 'Debe seleccionar un cliente'),
  linenControlEnabled: z.boolean().nullable().optional(),
  isActive: z.boolean().nullable().optional(),
  excludeFromExport: z.boolean().optional(),
});

export type PropertyFormData = z.infer<typeof propertySchema>;
