import { useQuery } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { Task } from '@/types/calendar';
import { useSede } from '@/contexts/SedeContext';
import { useAuth } from '@/hooks/useAuth';
import { useMemo } from 'react';

interface UseRecurringTaskInstancesProps {
  dateFrom: string;
  dateTo: string;
  cleanerId?: string | null; // For cleaner role filtering
}

/**
 * Generates virtual Task instances from active recurring tasks
 * for the given date range. Excludes dates that already have
 * a generated task (via recurring_task_executions).
 */
export const useRecurringTaskInstances = ({ dateFrom, dateTo, cleanerId }: UseRecurringTaskInstancesProps) => {
  const { activeSede } = useSede();
  const { userRole } = useAuth();

  // Fetch active recurring tasks
  const { data: recurringTasks = [] } = useQuery({
    queryKey: ['recurring-tasks-for-calendar', activeSede?.id, cleanerId],
    queryFn: async () => {
      let query = supabase
        .from('recurring_tasks')
        .select('*, properties:propiedad_id(nombre, direccion, codigo)')
        .eq('is_active', true);

      if (activeSede?.id) {
        query = query.eq('sede_id', activeSede.id);
      }

      if (cleanerId) {
        query = query.eq('cleaner_id', cleanerId);
      }

      const { data, error } = await query;
      if (error) throw error;
      return data || [];
    },
    enabled: !!activeSede?.id,
    staleTime: 5 * 60 * 1000,
  });

  // Fetch already-executed dates to avoid duplicates
  const recurringTaskIds = useMemo(() => recurringTasks.map(rt => rt.id), [recurringTasks]);

  const { data: executedDates = [] } = useQuery({
    queryKey: ['recurring-task-executions', recurringTaskIds, dateFrom, dateTo],
    queryFn: async () => {
      if (recurringTaskIds.length === 0) return [];
      const { data, error } = await supabase
        .from('recurring_task_executions')
        .select('recurring_task_id, execution_date')
        .in('recurring_task_id', recurringTaskIds)
        .gte('execution_date', dateFrom)
        .lte('execution_date', dateTo)
        .eq('success', true);
      if (error) throw error;
      return data || [];
    },
    enabled: recurringTaskIds.length > 0,
    staleTime: 5 * 60 * 1000,
  });

  // Build set of already-executed (taskId, date) pairs
  const executedSet = useMemo(() => {
    const set = new Set<string>();
    executedDates.forEach(e => set.add(`${e.recurring_task_id}_${e.execution_date}`));
    return set;
  }, [executedDates]);

  // Generate virtual task instances
  const virtualTasks = useMemo(() => {
    if (recurringTasks.length === 0) return [];

    const fromDate = new Date(dateFrom);
    const toDate = new Date(dateTo);
    const instances: Task[] = [];

    for (const rt of recurringTasks) {
      const occurrences = calculateOccurrences(rt, fromDate, toDate);

      for (const date of occurrences) {
        const dateStr = date.toISOString().split('T')[0];

        // Skip if already generated by cron
        if (executedSet.has(`${rt.id}_${dateStr}`)) continue;

        const propertyName = rt.properties?.nombre || rt.name;
        const propertyAddress = rt.properties?.direccion || '';
        const propertyCode = rt.properties?.codigo || '';

        instances.push({
          id: `recurring_${rt.id}_${dateStr}`, // Virtual ID
          property: propertyName,
          propertyCode,
          address: propertyAddress,
          date: dateStr,
          startTime: rt.start_time,
          endTime: rt.end_time,
          duration: rt.duracion || undefined,
          checkIn: rt.check_in,
          checkOut: rt.check_out,
          type: rt.type,
          status: 'pending',
          cleaner: rt.cleaner || undefined,
          cleanerId: rt.cleaner_id || undefined,
          clienteId: rt.cliente_id || undefined,
          propertyId: rt.propiedad_id || undefined,
          cost: rt.coste || undefined,
          paymentMethod: rt.metodo_pago || undefined,
          supervisor: rt.supervisor || undefined,
          backgroundColor: '#3B82F6',
          notes: `🔄 Tarea recurrente: ${rt.name}`,
          created_at: rt.created_at,
          updated_at: rt.updated_at,
          // Mark as recurring for visual distinction
          isRecurringInstance: true,
          recurringTaskId: rt.id,
        } as Task & { isRecurringInstance: boolean; recurringTaskId: string });
      }
    }

    return instances;
  }, [recurringTasks, executedSet, dateFrom, dateTo]);

  return { virtualTasks };
};

/**
 * Calculate all occurrence dates of a recurring task within a date range.
 */
function calculateOccurrences(rt: any, fromDate: Date, toDate: Date): Date[] {
  const dates: Date[] = [];
  const startDate = new Date(rt.start_date);
  const endDate = rt.end_date ? new Date(rt.end_date) : toDate;
  const effectiveEnd = endDate < toDate ? endDate : toDate;
  const effectiveStart = startDate > fromDate ? startDate : fromDate;

  if (effectiveStart > effectiveEnd) return dates;

  // Start from the recurring task's start_date or next_execution
  let current = new Date(rt.start_date);
  const interval = rt.interval_days || 1;

  // For efficiency, advance to near the fromDate first
  switch (rt.frequency) {
    case 'daily': {
      // Advance current to near fromDate
      if (current < fromDate) {
        const daysDiff = Math.floor((fromDate.getTime() - current.getTime()) / (1000 * 60 * 60 * 24));
        const intervalsToSkip = Math.floor(daysDiff / interval);
        current.setDate(current.getDate() + intervalsToSkip * interval);
      }
      
      while (current <= effectiveEnd) {
        if (current >= effectiveStart) {
          dates.push(new Date(current));
        }
        current.setDate(current.getDate() + interval);
      }
      break;
    }
    case 'weekly': {
      if (rt.days_of_week && rt.days_of_week.length > 0) {
        // Advance to near fromDate
        if (current < fromDate) {
          const daysDiff = Math.floor((fromDate.getTime() - current.getTime()) / (1000 * 60 * 60 * 24));
          current.setDate(current.getDate() + daysDiff - 7); // Go back a week to be safe
        }
        
        while (current <= effectiveEnd) {
          if (current >= effectiveStart && rt.days_of_week.includes(current.getDay())) {
            dates.push(new Date(current));
          }
          current.setDate(current.getDate() + 1);
        }
      } else {
        if (current < fromDate) {
          const daysDiff = Math.floor((fromDate.getTime() - current.getTime()) / (1000 * 60 * 60 * 24));
          const weeksToSkip = Math.floor(daysDiff / (7 * interval));
          current.setDate(current.getDate() + weeksToSkip * 7 * interval);
        }
        
        while (current <= effectiveEnd) {
          if (current >= effectiveStart) {
            dates.push(new Date(current));
          }
          current.setDate(current.getDate() + 7 * interval);
        }
      }
      break;
    }
    case 'monthly': {
      if (current < fromDate) {
        const monthsDiff = (fromDate.getFullYear() - current.getFullYear()) * 12 + (fromDate.getMonth() - current.getMonth());
        const intervalsToSkip = Math.floor(monthsDiff / interval);
        current.setMonth(current.getMonth() + intervalsToSkip * interval);
      }
      
      while (current <= effectiveEnd) {
        if (current >= effectiveStart) {
          dates.push(new Date(current));
        }
        current.setMonth(current.getMonth() + interval);
        if (rt.day_of_month) {
          const lastDay = new Date(current.getFullYear(), current.getMonth() + 1, 0).getDate();
          current.setDate(Math.min(rt.day_of_month, lastDay));
        }
      }
      break;
    }
  }

  return dates;
}
