import { useQuery } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { Task } from '@/types/calendar';
import { useSede } from '@/contexts/SedeContext';
import { useMemo } from 'react';
import { calculateOccurrences } from '../../supabase/functions/_shared/recurringSchedule';

interface UseRecurringTaskInstancesProps {
  dateFrom: string;
  dateTo: string;
  cleanerId?: string | null; // For cleaner role filtering
}


/**
 * Generates virtual Task instances from active recurring tasks
 * for the given date range. Excludes dates that already have
 * a generated task (via recurring_task_executions).
 */
export const useRecurringTaskInstances = ({ dateFrom, dateTo, cleanerId }: UseRecurringTaskInstancesProps) => {
  const { activeSede } = useSede();

  // Fetch active recurring tasks
  const {
    data: recurringTasks = [],
    isLoading: recurringTasksLoading,
    isError: recurringTasksError,
    error: recurringTasksQueryError,
  } = useQuery({
    queryKey: ['recurring-tasks-for-calendar', activeSede?.id, cleanerId],
    queryFn: async () => {
      let query = supabase
        .from('recurring_tasks')
        .select('*, properties:propiedad_id(nombre, direccion, codigo, duracion_servicio)')
        .eq('is_active', true);

      if (activeSede?.id) {
        query = query.eq('sede_id', activeSede.id);
      }

      if (cleanerId) {
        query = query.eq('cleaner_id', cleanerId);
      }

      const { data, error } = await query;
      if (error) throw error;
      return data || [];
    },
    enabled: !!activeSede?.id,
    staleTime: 5 * 60 * 1000,
  });

  // Fetch already-executed dates to avoid duplicates
  const recurringTaskIds = useMemo(() => recurringTasks.map(rt => rt.id), [recurringTasks]);

  const {
    data: executedDates = [],
    isLoading: executedDatesLoading,
    isError: executedDatesError,
    error: executedDatesQueryError,
  } = useQuery({
    queryKey: ['recurring-task-executions', recurringTaskIds, dateFrom, dateTo],
    queryFn: async () => {
      if (recurringTaskIds.length === 0) return [];
      const { data, error } = await supabase
        .from('recurring_task_executions')
        .select('recurring_task_id, execution_date')
        .in('recurring_task_id', recurringTaskIds)
        .gte('execution_date', dateFrom)
        .lte('execution_date', dateTo)
        .eq('success', true);
      if (error) throw error;
      return data || [];
    },
    enabled: recurringTaskIds.length > 0,
    staleTime: 5 * 60 * 1000,
  });

  // Build set of already-executed (taskId, date) pairs
  const executedSet = useMemo(() => {
    const set = new Set<string>();
    executedDates.forEach(e => {
      const executionDate = typeof e.execution_date === 'string'
        ? e.execution_date.slice(0, 10)
        : e.execution_date;
      set.add(`${e.recurring_task_id}_${executionDate}`);
    });
    return set;
  }, [executedDates]);

  // Generate virtual task instances
  const virtualTasks = useMemo(() => {
    if (recurringTasks.length === 0) return [];

    const instances: Task[] = [];

    for (const rt of recurringTasks) {
      const occurrences = calculateOccurrences(rt, dateFrom, dateTo);

      for (const dateStr of occurrences) {
        // Skip if already generated by cron
        if (executedSet.has(`${rt.id}_${dateStr}`)) continue;

        const propertyName = rt.properties?.nombre || rt.name;
        const propertyAddress = rt.properties?.direccion || '';
        const propertyCode = rt.properties?.codigo || '';

        instances.push({
          id: `recurring_${rt.id}_${dateStr}`, // Virtual ID
          property: propertyName,
          propertyCode,
          propertyDurationMinutes: rt.properties?.duracion_servicio || rt.duracion || undefined,
          address: propertyAddress,
          date: dateStr,
          startTime: rt.start_time,
          endTime: rt.end_time,
          duration: rt.duracion || undefined,
          checkIn: rt.check_in,
          checkOut: rt.check_out,
          type: rt.type,
          status: 'pending',
          cleaner: rt.cleaner || undefined,
          cleanerId: rt.cleaner_id || undefined,
          clienteId: rt.cliente_id || undefined,
          propertyId: rt.propiedad_id || undefined,
          sedeId: rt.sede_id || undefined,
          cost: rt.coste || undefined,
          paymentMethod: rt.metodo_pago || undefined,
          supervisor: rt.supervisor || undefined,
          backgroundColor: '#3B82F6',
          notes: `🔄 Tarea recurrente: ${rt.name}`,
          created_at: rt.created_at,
          updated_at: rt.updated_at,
          // Mark as recurring for visual distinction
          isRecurringInstance: true,
          recurringTaskId: rt.id,
        } as Task & { isRecurringInstance: boolean; recurringTaskId: string });
      }
    }

    return instances;
  }, [recurringTasks, executedSet, dateFrom, dateTo]);

  return {
    virtualTasks,
    isLoading: recurringTasksLoading || (recurringTaskIds.length > 0 && executedDatesLoading),
    isError: recurringTasksError || executedDatesError,
    error: recurringTasksQueryError || executedDatesQueryError,
  };
};
