import type { Property } from '@/types/property';
import type { PropertyFormData } from './forms/PropertyFormSchema';

export const propertyEditValues = (property: Property): PropertyFormData => ({
      codigo: property.codigo,
      nombre: property.nombre,
      direccion: property.direccion,
      numeroCamas: property.numeroCamas,
      numeroCamasPequenas: property.numeroCamasPequenas || 0,
      numeroCamasSuite: property.numeroCamasSuite || 0,
      numeroSofasCama: property.numeroSofasCama || 0,
      numeroBanos: property.numeroBanos,
      numeroCocinas: property.numeroCocinas ?? 1,
      duracionServicio: property.duracionServicio,
      costeServicio: property.costeServicio,
      checkInPredeterminado: property.checkInPredeterminado,
      checkOutPredeterminado: property.checkOutPredeterminado,
      numeroSabanas: property.numeroSabanas,
      numeroSabanasRequenas: property.numeroSabanasRequenas || 0,
      numeroSabanasSuite: property.numeroSabanasSuite || 0,
      numeroToallasGrandes: property.numeroToallasGrandes,
      numeroTotallasPequenas: property.numeroTotallasPequenas,
      numeroAlfombrines: property.numeroAlfombrines,
        numeroFundasAlmohada: property.numeroFundasAlmohada,
        kitAlimentario: property.kitAlimentario || 0,
        amenitiesBano: property.amenitiesBano || 0,
        amenitiesCocina: property.amenitiesCocina || 0,
        cantidadRollosPapelHigienico: property.cantidadRollosPapelHigienico || 0,
        cantidadRollosPapelCocina: property.cantidadRollosPapelCocina || 0,
        bayetasCocina: property.bayetasCocina || 0,
        bolsasBasura: property.bolsasBasura || 0,
        stockConsumptions: {},
        notas: property.notas || '',
        clienteId: property.clienteId,
        linenControlEnabled: property.linenControlEnabled ?? null,
        amenitiesControlEnabled: property.amenitiesControlEnabled ?? null,
        isActive: property.isActive ?? null,
        excludeFromExport: property.excludeFromExport ?? false,
    });
