import { useState } from 'react';
import { Link } from 'react-router-dom';
import { addCivilDays } from './monthly';
import { candidateTier } from './forecastModel';
import { clock, hours, monthLabel, monday, weekday, type ForecastTask } from './forecastContract';
import { centerKind, centerLabel, countLabel, coverageLabel, dayNames, duration, focusMonth, fullDate, ledgerLabel, normalize, personName, scopedTasks, sumComplete, teamSummary, viewScope, within, workerWeek } from './forecastPresentation';
import { Badge, Empty, Metric, Panel, TaskList, type ScreenProps } from './ForecastUi';

export function Team(props: ScreenProps) {
  const { dataset, model, to, params, change, screen } = props;
  const month = focusMonth(model.context, params), filter = params.get('filter') || 'included', query = params.get('q') ?? '';
  const team = teamSummary(model, month);
  const rows = model.ledgers.filter(l => l.month === month && model.visibleWorkerIds.includes(l.workerId)).map(l => ({ ...l, worker: dataset.workers.find(w => w.id === l.workerId)! })).filter(l => l.worker && normalize(l.worker.name).includes(normalize(query)) && (filter === 'excluded' ? l.status === 'Excluido' : filter === 'risk' ? l.status === 'Faltan horas' : filter === 'unknown' ? l.status === 'No verificable' : filter === 'all' || l.status !== 'Excluido')).sort((a, b) => {
    if (params.get('order') === 'name') return a.worker.name.localeCompare(b.worker.name, 'es');
    if (params.get('order') === 'unknown') { const priority = Number(b.status === 'No verificable') - Number(a.status === 'No verificable'); if (priority) return priority; }
    const rank = (status: string) => status === 'Faltan horas' ? 0 : status === 'No verificable' ? 1 : 2;
    return rank(a.status) - rank(b.status) || (a.status === 'Faltan horas' && b.status === 'Faltan horas' ? b.missing - a.missing : 0) || a.worker.name.localeCompare(b.worker.name, 'es');
  });
  return <><div className="sf-metrics sf-three"><Metric label="Personas incluidas" value={team.rows.length} note={`${countLabel(team.excluded, 'persona excluida', 'personas excluidas')} · ver filtro de exclusiones`} /><Metric label="Con horas pendientes" value={team.risk.length} to={to('team', { filter: 'risk' })} note={monthLabel(month)} /><Metric label="Por verificar" value={team.unknown.length} to={to('team', { filter: 'unknown' })} note="No cuentan como cumplimiento confirmado" /></div><Panel title={`Equipo · ${monthLabel(month)}`}><div className="sf-toolbar"><label>Buscar persona<input type="search" value={query} onChange={e => change({ q: e.target.value })} /></label><label>Mostrar<select value={filter} onChange={e => change({ filter: e.target.value })}><option value="included">Plantilla incluida</option><option value="risk">Horas pendientes</option><option value="unknown">Por verificar</option><option value="all">Todo el equipo</option><option value="excluded">Personas excluidas</option></select></label><label>Ordenar equipo<select value={params.get('order') ?? 'priority'} onChange={e => change({ order: e.target.value })}><option value="priority">Prioridad y horas pendientes</option><option value="unknown">Por verificar primero</option><option value="name">Nombre</option></select></label><label>Semana de referencia<select value={model.context.week} onChange={e => change({ week: e.target.value, focusMonth: month })}>{model.weeks.map(w => <option key={w.key} value={w.key}>{fullDate(w.key)} – {fullDate(addCivilDays(w.key, 6))}</option>)}</select></label>{(filter !== 'included' || query) && <button onClick={() => change({ filter: '', q: '' })}>Limpiar filtros</button>}</div><p className="sf-caption">{countLabel(rows.length, 'persona')}. Computadas: horas cuyo fin registrado ya pasó; no equivalen a ejecución confirmada. El margen semanal no es un objetivo mínimo.</p><div className="sf-team-list">{rows.map(l => {
    const weekly = workerWeek(dataset, model, l.worker, model.context.week);
    const verified = !['No verificable', 'Sin jornada', 'Excluido'].includes(l.status);
    const used = verified && l.target > 0 ? Math.min(100, l.computed / l.target * 100) : 0;
    const future = verified && l.target > 0 ? Math.min(100 - used, l.future / l.target * 100) : 0;
    return <article className="sf-team-row" key={l.workerId}><div><Link className="sf-person" to={to(screen, { person: l.workerId, personTab: '', focusMonth: month })}>{personName(l.worker.name)}</Link><Badge>{ledgerLabel(l.status)}</Badge></div><div className="sf-progress-cell"><small>Progreso de {monthLabel(month)}</small><strong>{hours(l.computed)} computadas · {hours(l.future)} futuras</strong>{verified && <div className="sf-progress" role="img" aria-label={`${hours(l.computed)} computadas y ${hours(l.future)} futuras sobre ${hours(l.target)} de objetivo`}><span style={{ width: `${used}%` }} /><span style={{ width: `${future}%` }} /></div>}<small>Objetivo: {verified ? hours(l.target) : l.status === 'No verificable' ? 'Por verificar' : ledgerLabel(l.status)}</small></div><div><small>Por completar</small><strong>{verified ? hours(l.missing) : '—'}</strong></div><div><small>Margen semanal</small><strong>{l.worker.excluded || !l.worker.weeklyMinutes ? 'No participa' : hours(weekly.margin)}</strong><small>Del {fullDate(model.context.week)}</small></div><Link className="sf-button" to={to(screen, { person: l.workerId, personTab: '', focusMonth: month })}>Ver detalle</Link></article>;
  })}</div>{!rows.length && <Empty reset={() => change({ filter: '', q: '' })}>No hay personas con estos filtros.</Empty>}</Panel></>;
}

export function Shifts(props: ScreenProps & { onSimulate: () => void }) {
  const { model, dataset, params, change, to, onSimulate } = props;
  const scope = viewScope(model.context, params, 'week'), filter = params.get('filter') ?? '';
  const tasks = scopedTasks(model, scope, filter);
  const [fullDay, setFullDay] = useState(false);
  const group = params.get('group') ?? 'center';
  const date = scope.mode === 'day' ? scope.from : model.context.week;
  const days = model.days.filter(d => within(d.date, scope));
  const grouped = new Map<string, ForecastTask[]>();
  for (const task of tasks) {
    const id = group === 'person' ? task.workerId ?? 'unassigned' : task.centerId;
    grouped.set(id, [...(grouped.get(id) ?? []), task]);
  }
  const times = tasks.flatMap(t => [t.start, t.end, t.windowStart, t.windowEnd]).filter(v => Number.isFinite(v) && v >= 0 && v <= 1440);
  const axisStart = fullDay || !times.length ? 0 : Math.max(0, Math.floor(Math.min(...times) / 60) * 60);
  const axisEnd = fullDay || !times.length ? 1440 : Math.min(1440, Math.max(axisStart + 60, Math.ceil(Math.max(...times) / 60) * 60));
  const axis = axisEnd - axisStart;
  const dayLink = (value: string) => to('shifts', { date: value, view: 'day', focusMonth: value.slice(0, 7), week: monday(value) });
  return <><div className="sf-toolbar"><label>Vista de cobertura<select value={scope.mode} onChange={e => change({ view: e.target.value, date: e.target.value === 'day' ? model.context.week : '', focusMonth: focusMonth(model.context, params) })}><option value="day">Día</option><option value="week">Semana</option><option value="month">Mes</option><option value="horizon">Todo el horizonte</option></select></label>{scope.mode === 'day' && <><button disabled={date <= dataset.from} onClick={() => change({ date: addCivilDays(date, -1), week: monday(addCivilDays(date, -1)), focusMonth: addCivilDays(date, -1).slice(0, 7) })}>Día anterior</button><label>Fecha<input type="date" min={dataset.from} max={dataset.to} value={date} onChange={e => { if (e.target.value) change({ date: e.target.value, week: monday(e.target.value), focusMonth: e.target.value.slice(0, 7) }); }} /></label><button disabled={date >= dataset.to} onClick={() => change({ date: addCivilDays(date, 1), week: monday(addCivilDays(date, 1)), focusMonth: addCivilDays(date, 1).slice(0, 7) })}>Día siguiente</button></>}{scope.mode === 'week' && <label>Semana de cobertura<select value={model.context.week} onChange={e => change({ week: e.target.value, focusMonth: '', date: '' })}>{model.weeks.map(w => <option key={w.key} value={w.key}>{fullDate(w.key)} – {fullDate(addCivilDays(w.key, 6))}</option>)}</select></label>}<label>Filtro de tareas<select value={filter} onChange={e => change({ filter: e.target.value })}><option value="">Todas las tareas</option><option value="pending">Sin asignar</option><option value="uncovered">Tareas por revisar</option></select></label>{filter && <button onClick={() => change({ filter: '' })}>Limpiar filtros</button>}<button onClick={onSimulate}>Simular refuerzo</button></div><div className="sf-context-line"><strong>{scope.label} · {countLabel(tasks.length, 'tarea')}</strong><Badge>{coverageLabel(model, scope)}</Badge></div>
    {scope.mode === 'day' ? <><div className="sf-toolbar"><div className="sf-segment"><button aria-pressed={group === 'center'} onClick={() => change({ group: 'center' })}>Por centro</button><button aria-pressed={group === 'person'} onClick={() => change({ group: 'person' })}>Por persona</button></div><button aria-pressed={fullDay} onClick={() => setFullDay(!fullDay)}>{fullDay ? 'Ajustar al tramo operativo' : 'Ver 24 h'}</button></div><Panel title="Tareas y ventanas del día"><p className="sf-caption">Desplaza solo la agenda para recorrer las horas. Las filas separan tareas coincidentes. Los otros compromisos se consultan en la disponibilidad de cada persona.</p><div className="sf-timeline-scroll" tabIndex={0} role="region" aria-label="Agenda horaria con desplazamiento horizontal"><div className="sf-timeline"><div className="sf-time-axis"><span>Propiedad · duración</span><div>{Array.from({ length: 7 }, (_, i) => <span key={i} style={{ left: `${i / 6 * 100}%` }}>{clock(axisStart + axis * i / 6)}</span>)}</div></div>{[...grouped].map(([id, rows]) => <section key={id}><h3 className="sf-timeline-group">{group === 'person' ? id === 'unassigned' ? 'Sin asignar' : personName(dataset.workers.find(w => w.id === id)?.name ?? 'Persona por verificar') : dataset.centers.find(c => c.id === id)?.name ?? 'Centro por revisar'}{group === 'person' && id !== 'unassigned' && <Link to={to('shifts', { person: id, personTab: 'availability', focusMonth: date.slice(0, 7) })}>Ver disponibilidad y otros compromisos</Link>}</h3>{rows.map(t => {
      const hasTime = Number.isFinite(t.start) && t.end > t.start;
      return <div className="sf-time-row" key={t.id}><div><Link to={to('shifts', { task: t.id, focusMonth: t.date.slice(0, 7) })}>{t.name}</Link><small>{duration(t.minutes)} · {t.workerId ? 'Asignada' : 'Sin asignar'}</small><small>Ventana {clock(t.windowStart)}–{clock(t.windowEnd)}</small><small>Registro {clock(t.start)}–{clock(t.end)}</small></div><div className="sf-track">{t.windowEnd > t.windowStart && <div className="sf-window" style={{ left: `${(t.windowStart - axisStart) / axis * 100}%`, width: `${(t.windowEnd - t.windowStart) / axis * 100}%` }} />}{hasTime ? <Link className={`sf-shift ${t.workerId ? '' : 'sf-unassigned'}`} style={{ left: `${(t.start - axisStart) / axis * 100}%`, width: `${(t.end - t.start) / axis * 100}%` }} aria-label={`${t.name}, horario registrado ${clock(t.start)}–${clock(t.end)}, ${t.workerId ? 'asignada' : 'sin asignar'}`} to={to('shifts', { task: t.id, focusMonth: t.date.slice(0, 7) })} /> : <span className="sf-no-time">Sin horario registrado</span>}</div></div>;
    })}</section>)}</div></div>{!tasks.length && <Empty reset={filter ? () => change({ filter: '' }) : undefined} />}<div className="sf-legend"><span>Fondo claro: ventana del cliente</span><span>Barra continua: asignación registrada</span><span>Borde discontinuo: registro sin asignar</span></div></Panel><Panel title="Detalle de las tareas"><TaskList {...props} tasks={tasks} /></Panel></> : <Panel title={scope.mode === 'week' ? 'Semana agrupada por días' : scope.mode === 'month' ? 'Calendario mensual' : 'Días del horizonte'}><div className={scope.mode === 'month' ? 'sf-month-grid' : 'sf-day-list'}>{days.map((day, i) => {
      const dayTasks = tasks.filter(t => t.date === day.date);
      return <Link className="sf-day-cell" key={day.date} to={dayLink(day.date)} style={scope.mode === 'month' && i === 0 ? { gridColumnStart: (weekday(day.date) + 6) % 7 + 1 } : undefined}><strong>{dayNames[weekday(day.date)]} {Number(day.date.slice(8))}{scope.mode !== 'month' && ` · ${monthLabel(day.date.slice(0, 7))}`}</strong><span>{countLabel(dayTasks.length, 'tarea')} · {hours(sumComplete(dayTasks, t => t.minutes))}</span><small>{dayTasks.filter(t => !t.workerId).length} sin asignar{filter ? ' · filtro activo' : ''}</small><Badge>{coverageLabel(model, { ...scope, from: day.date, to: day.date })}</Badge><span>Ver día →</span></Link>;
    })}</div>{!days.length && <Empty />}</Panel>}
  </>;
}

export function Centers(props: ScreenProps) {
  const { dataset, model, params, change, to } = props;
  const query = params.get('q') ?? '', filter = params.get('filter') ?? '', cards = params.get('layout') === 'cards';
  const scope = viewScope(model.context, new URLSearchParams({ focusMonth: focusMonth(model.context, params) }));
  const centers = dataset.centers.map(center => {
    const tasks = scopedTasks(model, scope).filter(t => t.centerId === center.id);
    const primary = dataset.workers.filter(w => !w.excluded && candidateTier(w, center.id) === 0);
    const substitutes = dataset.workers.filter(w => !w.excluded && candidateTier(w, center.id) === 1);
    const issues = model.issues.filter(i => i.centerId === center.id || i.ids.includes(center.id) || tasks.some(t => i.ids.includes(t.id)) || [...primary, ...substitutes].some(w => i.ids.includes(w.id)));
    return { center, tasks, primary, substitutes, issues };
  }).filter(({ center, tasks, primary, issues }) => (!model.context.center || center.id === model.context.center) && normalize(centerLabel(center)).includes(normalize(query)) && (filter !== 'pending' || tasks.some(t => !t.workerId)) && (filter !== 'primary' || !primary.length) && (filter !== 'issues' || issues.length)).sort((a, b) => centerLabel(a.center).localeCompare(centerLabel(b.center), 'es'));
  return <><div className="sf-toolbar"><label>Buscar centro<input type="search" value={query} onChange={e => change({ q: e.target.value })} /></label><label>Mostrar centros<select value={filter} onChange={e => change({ filter: e.target.value })}><option value="">Todos</option><option value="pending">Con tareas sin asignar</option><option value="primary">Sin titular registrado</option><option value="issues">Datos por revisar</option></select></label><button aria-pressed={cards} onClick={() => change({ layout: cards ? '' : 'cards' })}>{cards ? 'Ver lista compacta' : 'Ver tarjetas'}</button>{(query || filter) && <button onClick={() => change({ q: '', filter: '' })}>Limpiar filtros</button>}<span>{countLabel(centers.length, 'centro')}</span></div><p className="sf-caption">Equipo registrado en el centro. La elegibilidad se verifica al abrir los candidatos de una tarea concreta.</p><div className={cards ? 'sf-centers' : 'sf-center-list'}>{centers.map(({ center, tasks, primary, substitutes, issues }) => <article className="sf-panel sf-center-item" key={center.id}><div><h2><Link to={to('centers', { detail: center.id })}>{centerLabel(center)}</Link></h2><small>{centerKind(center.id)} · {countLabel(center.propertyCount, 'propiedad', 'propiedades')}</small></div><div><small>Titular registrado</small><p>{primary.map(w => personName(w.name)).join(', ') || 'Sin titular registrado'}</p></div><div><small>Suplentes registrados</small><p>{substitutes.map(w => personName(w.name)).join(', ') || 'Sin suplentes registrados'}</p></div><div><Badge>{issues.length ? 'Datos por revisar' : 'Sin incidencias identificadas'}</Badge><Link to={to('shifts', { center: center.id, filter: 'pending', view: 'month', focusMonth: scope.from.slice(0, 7) })}>{tasks.filter(t => !t.workerId).length} sin asignar</Link></div><Link className="sf-button" to={to('centers', { detail: center.id })}>Ver centro</Link></article>)}</div>{!centers.length && <Empty reset={() => change({ q: '', filter: '' })}>No hay centros con estos filtros.</Empty>}</>;
}
