import { Link } from 'react-router-dom';
import { findCandidates, candidateTier } from './forecastModel';
import { addCivilDays, monthEnd } from './monthly';
import { hours, clock, dates, monthLabel, weekday } from './forecastContract';
import { absenceName, calendarTaskHref, centerKind, centerLabel, dayNames, duration, focusMonth, fullDate, ledgerLabel, personName, scopedTasks, taskConflicts, tiers, viewScope, weekScope, within, workerWeek } from './forecastPresentation';
import { Badge, Empty, ForecastDialog, Metric, TaskList, type ScreenProps } from './ForecastUi';

export function ForecastDetails(props: ScreenProps & { close: () => void }) {
  const { dataset, model, params, change, to, screen, close } = props;
  const personId = params.get('person'), taskId = params.get('task'), detail = params.get('detail');
  const person = dataset.workers.find(w => w.id === personId), task = dataset.tasks.find(t => t.id === taskId), center = dataset.centers.find(c => c.id === detail);
  const candidatesView = detail === 'candidates';
  if (!personId && !taskId && !detail) return null;
  const month = focusMonth(model.context, params);
  const ledger = model.ledgers.find(l => l.workerId === personId && l.month === month);
  const title = personId ? person ? personName(person.name) : 'Persona no disponible' : candidatesView ? task ? `Candidatos para ${task.name}` : 'Tareas pendientes · candidatos' : taskId ? task?.name ?? 'Tarea no disponible' : center ? centerLabel(center) : 'Detalle';
  const keepDetail = (values: Record<string, string>) => change({ task: taskId ?? '', person: personId ?? '', detail: detail ?? '', ...values });
  const tab = params.get('personTab') ?? 'balance';
  const candidates = task && !task.workerId && !task.ambiguous ? findCandidates(dataset, task, model.placements.filter(p => p.taskId !== task.id), model.rests, model.ledgers, model.context.asOf) : [];
  const scope = viewScope(model.context, params, screen === 'shifts' ? 'week' : 'month');
  return <ForecastDialog title={title} description={`${task && !personId ? fullDate(task.date) : monthLabel(month)} · consulta y propuestas sin guardar`} close={close} wide>
    {personId && taskId && <button onClick={() => keepDetail({ person: '', personTab: '', focusMonth: task?.date.slice(0, 7) ?? month })}>Volver a {candidatesView ? 'candidatos' : 'la tarea'}</button>}
    {personId && center && <button onClick={() => keepDetail({ person: '', personTab: '' })}>Volver al centro</button>}
    {person && <><div className="sf-toolbar"><label>Mes del balance<select value={month} onChange={e => keepDetail({ focusMonth: e.target.value })}>{[...new Set([...model.months.map(m => m.key), model.context.week.slice(0, 7), addCivilDays(model.context.week, 6).slice(0, 7), month])].sort().map(m => <option key={m} value={m}>{monthLabel(m)}</option>)}</select></label><Badge>{ledger ? ledgerLabel(ledger.status) : 'Mes fuera del horizonte calculado'}</Badge></div><div className="sf-toolbar sf-segment">{[['balance', 'Balance mensual'], ['week', 'Esta semana'], ['availability', 'Disponibilidad'], ['tasks', 'Tareas']].map(([value, label]) => <button key={value} aria-pressed={tab === value} onClick={() => keepDetail({ personTab: value })}>{label}</button>)}</div>
      {!ledger && <div className="sf-empty"><p>Este mes no se ha calculado. Amplía el periodo para verificar el objetivo completo; no se deduce de la semana parcial.</p><Link className="sf-button" to={to(screen, { month, horizon: '1', focusMonth: month, person: person.id, task: '', detail: '', week: `${month}-01`, refuerzo: '', simFrom: '', simTo: '' })}>Consultar este mes completo</Link></div>}
      {tab === 'balance' && ledger && <><div className="sf-metrics sf-three"><Metric label="Objetivo ajustado" value={ledger.status === 'No verificable' ? 'Por verificar' : hours(ledger.target)} /><Metric label="Horas computadas" value={hours(ledger.computed)} /><Metric label="Futuras asignadas" value={hours(ledger.future)} /></div><dl className="sf-detail-list"><div><dt>Objetivo base (jornada × 4,345)</dt><dd>{person.contractKnown ? hours(person.weeklyMinutes * 4.345) : 'Por verificar'}</dd></div><div><dt>Reducción por ausencias</dt><dd>{hours(ledger.adjustment)}{ledger.status === 'No verificable' && ' · cálculo parcial'}</dd></div><div><dt>Otros servicios ya incluidos</dt><dd>{hours(ledger.other)} · dentro de computadas y futuras, sin volver a sumar</dd></div><div><dt>Horas por completar</dt><dd>{ledger.status === 'No verificable' ? 'Por verificar' : hours(ledger.missing)}</dd></div><div><dt>Propuestas separadas</dt><dd>{hours(ledger.proposed)} · no completan el objetivo registrado</dd></div></dl><p>El balance incluye todos los centros de esta persona. Computadas significa que pasó el fin registrado; no confirma la ejecución.</p>{ledger.status === 'No verificable' && <div className="sf-notice"><div><strong>Falta información para cerrar el balance</strong><ul>{!person.contractKnown && <li>Jornada contractual pendiente de revisar.</li>}{model.issues.filter(i => i.impact !== 'information' && (!i.ids.length || i.ids.includes(person.id) || i.workerId === person.id || dataset.tasks.some(t => t.workerId === person.id && i.ids.includes(t.id)))).map((i, index) => <li key={index}>{i.message}</li>)}{person.activeFrom && person.activeFrom > `${month}-01` && <li>La incorporación dentro del mes requiere un criterio de prorrateo confirmado.</li>}</ul><Link to={to('settings', { tab: 'data' })}>Revisar datos</Link></div></div>}<Link className="sf-button" to={to('shifts', { view: 'month', focusMonth: month, filter: 'pending', task: '', person: '', detail: '' })}>Consultar tareas turísticas sin asignar</Link></>}
      {tab === 'week' && (() => { const weekly = workerWeek(dataset, model, person, model.context.week); return <><h3>{weekScope(model.context.week).label}</h3><div className="sf-metrics sf-three"><Metric label="Compromisos registrados" value={hours(weekly.committed)} /><Metric label="Máximo semanal" value={person.contractKnown ? hours(weekly.maximum) : 'Por verificar'} /><Metric label="Margen de horas" value={person.excluded || person.weeklyMinutes === 0 ? 'No participa' : hours(weekly.margin)} /></div><p>Contrato: {person.contractKnown ? hours(person.weeklyMinutes) : 'por verificar'}/semana. El margen necesita además una ventana compatible; no significa disponibilidad para cualquier tarea. El objetivo mínimo se revisa por mes.</p><h3>Libranza propuesta · recomendación</h3><ul>{model.rests.filter(r => r.workerId === person.id && within(r.date, weekScope(model.context.week))).map(r => <li key={r.date}>{fullDate(r.date)} · {r.date < model.context.asOf.slice(0, 10) ? 'fecha pasada, no es una instrucción actual' : 'recomendación revisable para reducir el mayor déficit diario'}</li>)}</ul>{!model.rests.some(r => r.workerId === person.id && within(r.date, weekScope(model.context.week))) && <p>No hay propuestas de libranza en esta semana.</p>}</>; })()}
      {tab === 'availability' && ledger && <><h3>Libranzas registradas</h3><p>{person.restDays.map(d => dayNames[d]).join(', ') || 'Sin días fijos registrados'}</p><h3>Ausencias · {monthLabel(month)}</h3>{dataset.sources.some(s => s.name === 'worker_absences' && s.status !== 'ready') ? <Empty>No se pudo cargar la información de ausencias.</Empty> : <><ul>{dataset.absences.filter(a => a.workerId === person.id && a.type !== 'external_work' && a.from <= monthEnd(`${month}-01`) && a.to >= `${month}-01`).map(a => <li key={a.id}>{absenceName(a.type)}: {fullDate(a.from)} – {fullDate(a.to)}{a.start !== undefined && ` · ${clock(a.start)}–${clock(a.end ?? NaN)} · ajuste parcial por verificar`}</li>)}</ul>{!dataset.absences.some(a => a.workerId === person.id && a.type !== 'external_work' && a.from <= monthEnd(`${month}-01`) && a.to >= `${month}-01`) && <p>No hay ausencias registradas en este mes.</p>}</>}<h3>Otros compromisos que ocupan disponibilidad</h3><ul>{(person.blockedSlots ?? []).map((slot, index) => <li key={index}>{slot.date ? fullDate(slot.date) : dayNames[slot.day ?? 0]} · {clock(slot.startMinute)}–{clock(slot.endMinute)} · {slot.consumesContract ? 'Mantenimiento computable' : 'Indisponibilidad registrada'}</li>)}{dataset.absences.filter(a => a.workerId === person.id && a.type === 'external_work' && a.from <= monthEnd(`${month}-01`) && a.to >= `${month}-01`).map(a => <li key={a.id}>Otro servicio: {fullDate(a.from)} – {fullDate(a.to)} · {clock(a.start ?? NaN)}–{clock(a.end ?? NaN)}</li>)}</ul>{!person.blockedSlots?.length && !dataset.absences.some(a => a.workerId === person.id && a.type === 'external_work' && a.from <= monthEnd(`${month}-01`) && a.to >= `${month}-01`) && <p>No hay otros servicios registrados en este mes.</p>}<p>Movilidad: {person.canMove ? 'Permitida por la regla de sede, respetando los centros excluidos' : 'No verificada fuera de sus centros'}.</p></>}
      {tab === 'tasks' && ledger && <><h3>Asignaciones registradas · {monthLabel(month)}</h3><TaskList {...props} tasks={dataset.tasks.filter(t => t.workerId === person.id && t.date.startsWith(month)).sort((a, b) => a.date.localeCompare(b.date) || a.start - b.start)} /><details className="sf-detail-block"><summary>Propuestas de tareas · sin guardar</summary><TaskList {...props} tasks={dataset.tasks.filter(t => t.date.startsWith(month) && model.placements.some(p => p.taskId === t.id && p.workerId === person.id && !p.real))} /></details></>}
      <div className="sf-panel-actions"><Link className="sf-button" to={`/workers/${encodeURIComponent(person.id)}`} target="_blank" rel="noopener noreferrer">Abrir ficha de gestión · otra pestaña</Link></div>
    </>}
    {!personId && task && <><dl className="sf-detail-list"><div><dt>Propiedad / centro</dt><dd>{task.name} · {dataset.centers.find(c => c.id === task.centerId)?.name}</dd></div><div><dt>Duración completa</dt><dd>{duration(task.minutes)}</dd></div><div><dt>Ventana permitida del cliente</dt><dd>{clock(task.windowStart)}–{clock(task.windowEnd)}</dd></div><div><dt>Responsable registrado</dt><dd>{task.ambiguous ? 'Asignación contradictoria' : dataset.workers.find(w => w.id === task.workerId)?.name ?? (task.workerId ? 'Persona por verificar' : 'Sin asignar')}</dd></div><div><dt>Horario registrado</dt><dd>{clock(task.start)}–{clock(task.end)}{!task.workerId && ' · no tiene responsable y no es una cita confirmada'}</dd></div><div><dt>Ejecución confirmada</dt><dd>{['completed', 'completada', 'completado'].includes(task.status) ? 'Sí, según estado de la tarea' : 'No consta'}</dd></div></dl>
      {taskConflicts(task, model).length > 0 && <div className="sf-notice sf-red"><ul>{taskConflicts(task, model).map(message => <li key={message}>{message}</li>)}</ul></div>}
      {model.placements.filter(p => p.taskId === task.id && !p.real).map(p => <div className="sf-proposal" key={p.taskId}><Badge>Propuesta · sin guardar</Badge><p>{personName(model.workers.find(w => w.id === p.workerId)?.name ?? 'Persona por verificar')} · {clock(p.start)}–{clock(p.end)}.</p>{task.workerId && <p>Recomendación de cambio; la asignación registrada se conserva.</p>}</div>)}
      <div className="sf-panel-actions"><Link className="sf-button sf-primary" to={calendarTaskHref(task)} target="_blank" rel="noopener noreferrer">Abrir en calendario diario · otra pestaña</Link>{!candidatesView && !task.workerId && !task.ambiguous && <button onClick={() => keepDetail({ detail: 'candidates', focusMonth: task.date.slice(0, 7) })}>Ver candidatos</button>}</div><p>La asignación se decide y guarda en el calendario. Este previsor conserva tu consulta abierta.</p>
      {candidatesView && <section><h3>{candidates.length ? `${tiers[candidates[0].tier]} · ${monthLabel(task.date.slice(0, 7))}` : 'Sin candidatos elegibles'}</h3>{candidates.map(c => {
        const candidateLedger = model.ledgers.find(l => l.workerId === c.worker.id && l.month === task.date.slice(0, 7));
        return <article key={c.worker.id} className="sf-candidate"><div><strong>{personName(c.worker.name)}</strong><small>{!candidateLedger || candidateLedger.status === 'No verificable' ? 'Saldo mensual por verificar' : `${hours(candidateLedger.missing)} por completar en ${monthLabel(candidateLedger.month)}`}</small></div><Badge>{clock(c.start)}–{clock(c.end)}</Badge><Link to={to(screen, { person: c.worker.id, task: task.id, detail: 'candidates', focusMonth: task.date.slice(0, 7), personTab: 'balance' })}>Ver perfil</Link></article>;
      })}{!candidates.length && <Empty>{task.workerId ? 'Esta tarea ya tiene responsable. Abre una tarea sin asignar para consultar candidatos.' : 'No hay candidatos elegibles con una franja verificada suficiente. Revisa disponibilidad o simula refuerzo desde la cobertura del día.'}</Empty>}<p>Solo el primer nivel elegible. Se respetan compromisos y propuestas de otros centros. Las propuestas no completan el saldo registrado.</p></section>}
    </>}
    {!personId && candidatesView && !taskId && <TaskList {...props} tasks={scopedTasks(model, scope, 'pending')} />}
    {center && !personId && (() => {
      const properties = dataset.properties?.filter(p => p.centerId === center.id) ?? [...new Map(dataset.tasks.filter(t => t.centerId === center.id).map(t => [t.propertyId, { id: t.propertyId, name: t.name, minutes: t.minutes, windowStart: t.windowStart, windowEnd: t.windowEnd }])).values()];
      const tasks = dataset.tasks.filter(t => t.centerId === center.id && t.date.startsWith(month));
      const windows = new Set([...properties, ...tasks].map(p => `${clock(p.windowStart)}–${clock(p.windowEnd)}`));
      return <><p>{centerKind(center.id)} · {center.propertyCount} {center.propertyCount === 1 ? 'propiedad' : 'propiedades'}. {windows.size > 1 ? 'Varias franjas de cliente; consulta el desglose.' : windows.size ? `Ventana registrada: ${[...windows][0]}` : 'Franjas pendientes de verificar.'}</p><div className="sf-panel-actions"><Link className="sf-button" to={to('forecast', { center: center.id, detail: '' })}>Consultar previsión del centro</Link><Link className="sf-button" to={to('shifts', { center: center.id, detail: '', view: 'month', focusMonth: month, filter: 'pending' })}>Ver tareas sin asignar</Link>{!center.id.includes(':') && <Link className="sf-button" to={`/planning/buildings/${encodeURIComponent(center.id)}`} target="_blank" rel="noopener noreferrer">Abrir ficha de gestión · otra pestaña</Link>}</div><h3>Equipo registrado y prioridades</h3><dl className="sf-detail-list">{[0, 1, 2].map(tier => <div key={tier}><dt>{tiers[tier]}</dt><dd>{dataset.workers.filter(w => candidateTier(w, center.id) === tier).map(w => <Link key={w.id} to={to(screen, { person: w.id, detail: center.id, focusMonth: month })}>{personName(w.name)}{w.excluded ? ' · excluido del previsor' : ''}<br /></Link>)}{!dataset.workers.some(w => candidateTier(w, center.id) === tier) && 'Sin registro'}</dd></div>)}</dl><p>Estar adscrito no demuestra disponibilidad para una tarea. Comprueba sus candidatos.</p><details className="sf-detail-block"><summary>Propiedades, duración y ventanas</summary>{!dataset.properties && <p>Se muestran las propiedades con tareas leídas; no es un inventario completo del centro.</p>}<ul>{properties.map(p => <li key={p.id}>{p.name} · {duration(p.minutes)} · {clock(p.windowStart)}–{clock(p.windowEnd)}</li>)}</ul></details><h3>Tareas de {monthLabel(month)}</h3><TaskList {...props} tasks={tasks.sort((a, b) => a.date.localeCompare(b.date))} /></>;
    })()}
    {(personId && !person || taskId && !task) && <Empty>El registro no está disponible en la sede y el periodo actuales.</Empty>}
  </ForecastDialog>;
}
