import { useState } from 'react';
import type { StaffingWorker } from './types';
import { clock, fieldClass, weekdays } from './presentation';

export function StaffingScenario({ workers, absence, onAbsence, onChange, onAdd, onReset, canAdd, balance, children }: { workers: StaffingWorker[]; absence: string; onAbsence: (id: string) => void; onChange: (id: string, change: Partial<StaffingWorker>) => void; onAdd: () => void; onReset: () => void; canAdd: boolean; balance?: React.ReactNode; children: React.ReactNode }) {
  const [search, setSearch] = useState('');
  return <><p className="text-sm text-stone-600">Solo en memoria. Horas y libranza afectan a todo el periodo; fin de actividad desde la fecha indicada. No cambia contratos ni servicios.</p>
    {balance}
    {children}
    <div className="flex flex-wrap gap-2"><button type="button" className={fieldClass} disabled={!canAdd} onClick={() => { setSearch(''); onAdd(); }}>Añadir refuerzo hipotético</button><button type="button" className={fieldClass} onClick={onReset}>Descartar cambios</button></div>
    <p className="text-xs text-stone-600">Refuerzo inicial: 15 h/semana, domingo libre, movilidad habilitada y ventana del centro seleccionado (o primero). Parámetros editables abajo; disponibilidad no confirmada.</p>
    <label className="grid gap-1 text-sm">Ausencia durante todo el horizonte<select className={fieldClass} aria-label="Simular ausencia" value={absence} onChange={event => onAbsence(event.target.value)}><option value="">Sin ausencia adicional</option>{workers.map(worker => <option key={worker.id} value={worker.id}>{worker.name}</option>)}</select></label>
    <label className="grid gap-1 text-sm">Buscar persona<input type="search" className={fieldClass} value={search} onChange={event => setSearch(event.target.value)} /></label>
    <div className="space-y-4">{workers.filter(worker => worker.name.toLocaleLowerCase('es').includes(search.toLocaleLowerCase('es'))).map(worker => <fieldset key={worker.id} className="min-w-0 rounded-lg border border-stone-200 p-3"><legend className="px-1 font-semibold">{worker.name}</legend><p className="mb-3 text-xs text-stone-600">Plantilla · horas de ficha</p><div className="grid gap-3 sm:grid-cols-2">
      <label className="grid gap-1 text-sm">Horas semanales<input className={fieldClass} aria-label={`Horas de ${worker.name}`} type="number" min="0" max="60" step="0.25" value={worker.weeklyMinutes / 60} onChange={event => onChange(worker.id, { weeklyMinutes: Math.max(0, Math.min(60, Number(event.target.value))) * 60 })} /></label>
      <label className="grid gap-1 text-sm">Día de libranza<select className={fieldClass} aria-label={`Libranza de ${worker.name}`} value={worker.restDay ?? ''} onChange={event => onChange(worker.id, { restDay: event.target.value === '' ? null : Number(event.target.value) })}><option value="">Sin confirmar</option>{weekdays.map((day, index) => <option key={day} value={index}>{day}</option>)}</select></label>
      <label className="flex min-h-11 items-center gap-2 text-sm"><input className="h-5 w-5" aria-label={`Libranza flexible de ${worker.name}`} type="checkbox" checked={worker.flexibleRest} onChange={event => onChange(worker.id, { flexibleRest: event.target.checked })} />Libranza flexible</label>
      <label className="flex min-h-11 items-center gap-2 text-sm"><input className="h-5 w-5" aria-label={`Movilidad de ${worker.name}`} type="checkbox" checked={worker.canMove} onChange={event => onChange(worker.id, { canMove: event.target.checked })} />Puede moverse</label>
      <label className="grid gap-1 text-sm">Último día activo<input className={fieldClass} aria-label={`Último día activo de ${worker.name}`} type="date" value={worker.activeTo || ''} onChange={event => onChange(worker.id, { activeTo: event.target.value || undefined })} /></label>
      {worker.engagement === 'collaborator' ? <p className="self-center text-xs text-stone-600">Precio de servicio pendiente · no nómina</p> : <label className="grid gap-1 text-sm">Coste plantilla €/h<input className={fieldClass} aria-label={`Coste de ${worker.name}`} type="number" min="0" max="500" step="0.01" placeholder="Sin dato" value={worker.costPerHour ?? ''} onChange={event => onChange(worker.id, { costPerHour: event.target.value === '' ? undefined : Math.max(0, Math.min(500, Number(event.target.value))) })} /></label>}
    </div><details className="mt-3 text-xs text-stone-600"><summary className="min-h-11 cursor-pointer py-3">Disponibilidad y restricciones</summary><ul>{worker.availability.map((slot, index) => <li key={index}>{weekdays[slot.day]} {clock(slot.startMinute)}–{clock(slot.endMinute)}</li>)}</ul><p>{worker.unavailableDates.length} días no disponibles · {worker.confirmedRestDates.length} descansos confirmados · {worker.blockedSlots?.length || 0} bloqueos registrados</p></details></fieldset>)}</div>
  </>;
}
