import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
if(!process.env.PGLITE_TEST_MODULE) throw new Error('Set PGLITE_TEST_MODULE to local PGlite. Never use Supabase for this test.');
const {PGlite}=await import(pathToFileURL(process.env.PGLITE_TEST_MODULE));
const db=new PGlite();
const sql=fs.readFileSync(path.resolve(import.meta.dirname,'../supabase/manual/20261005_operational_alert_reviews.sql'),'utf8');
const user='11111111-1111-4111-8111-111111111111', other='22222222-2222-4222-8222-222222222222';
const sede='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa', otherSede='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
const task='cccccccc-cccc-4ccc-8ccc-cccccccccccc', cleaner='dddddddd-dddd-4ddd-8ddd-dddddddddddd';
try{
  await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE SCHEMA auth;
    CREATE TABLE auth.users(id uuid PRIMARY KEY);
    CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('test.uid',true),'')::uuid $$;
    CREATE TYPE public.app_role AS ENUM ('admin','manager','cleaner');
    CREATE TABLE public.user_roles(user_id uuid, role public.app_role);
    CREATE TABLE public.user_sede_access(user_id uuid,sede_id uuid);
    CREATE FUNCTION public.has_role(u uuid,r public.app_role) RETURNS boolean LANGUAGE sql SECURITY DEFINER AS $$ SELECT EXISTS(SELECT 1 FROM public.user_roles WHERE user_id=u AND role=r) $$;
    CREATE FUNCTION public.user_has_sede_access(u uuid,s uuid) RETURNS boolean LANGUAGE sql SECURITY DEFINER AS $$ SELECT EXISTS(SELECT 1 FROM public.user_sede_access WHERE user_id=u AND sede_id=s) OR public.has_role(u,'admin') $$;
    CREATE TABLE public.profiles(id uuid,full_name text);
    CREATE TABLE public.sedes(id uuid PRIMARY KEY);
    CREATE TABLE public.tasks(id uuid PRIMARY KEY,sede_id uuid,date date,cleaner_id uuid);
    CREATE TABLE public.task_assignments(task_id uuid,cleaner_id uuid);
    INSERT INTO auth.users VALUES('${user}'),('${other}'); INSERT INTO public.profiles VALUES('${user}','Coordinadora de ejemplo');
    INSERT INTO public.user_roles VALUES('${user}','manager'),('${other}','cleaner');
    INSERT INTO public.user_sede_access VALUES('${user}','${sede}'),('${other}','${sede}');
    INSERT INTO public.sedes VALUES('${sede}'),('${otherSede}'); INSERT INTO public.tasks VALUES('${task}','${sede}','2026-10-05','${cleaner}');
    GRANT USAGE ON SCHEMA auth TO authenticated; GRANT EXECUTE ON FUNCTION auth.uid() TO authenticated;`);
  await db.exec(sql);
  await db.exec(`SET ROLE authenticated; SELECT set_config('test.uid','${user}',false);`);
  const snapshot={key:'occurrence-1',taskId:task,taskDate:'2026-10-05',sedeId:sede,kind:'late-start',cleanerId:cleaner,title:'No consta inicio',property:'Ejemplo'};
  const insert=(key='occurrence-1',s=sede,snap={...snapshot,key,sedeId:s})=>db.query(`INSERT INTO public.operational_alert_reviews(sede_id,task_id,task_date,alert_key,kind,snapshot) VALUES($1,$2,'2026-10-05',$3,'late-start',$4) RETURNING *`,[s,task,key,JSON.stringify(snap)]);
  const first=await insert(); assert.equal(first.rows[0].reviewed_by,user); assert.equal(first.rows[0].reviewed_by_name,'Coordinadora de ejemplo');
  const simultaneous=await Promise.allSettled([insert('occurrence-2'),insert('occurrence-2')]);
  assert.equal(simultaneous.filter(r=>r.status==='fulfilled').length,1);
  assert.equal(simultaneous.find(r=>r.status==='rejected').reason.code,'23505');
  await assert.rejects(()=>insert('other-sede',otherSede));
  await assert.rejects(()=>insert('wrong-worker',sede,{...snapshot,key:'wrong-worker',cleanerId:other}));
  await assert.rejects(()=>db.query(`UPDATE public.operational_alert_reviews SET reviewed_by=$1`,[other]));
  await assert.rejects(()=>db.query(`DELETE FROM public.operational_alert_reviews`));
  await db.exec(`SELECT set_config('test.uid','${other}',false);`);
  assert.equal((await db.query('SELECT * FROM public.operational_alert_reviews')).rows.length,0);
  await assert.rejects(()=>insert('cleaner-review'));
  await db.exec(`RESET ROLE; UPDATE public.user_roles SET role='manager' WHERE user_id='${other}'; DELETE FROM public.user_sede_access WHERE user_id='${other}'; INSERT INTO public.user_sede_access VALUES('${other}','${otherSede}'); SET ROLE authenticated;`);
  assert.equal((await db.query('SELECT * FROM public.operational_alert_reviews')).rows.length,0);
  await assert.rejects(()=>insert('manager-wrong-sede'));
  await db.exec(`RESET ROLE; DELETE FROM public.tasks WHERE id='${task}'; SET ROLE authenticated; SELECT set_config('test.uid','${user}',false);`);
  const archived=await db.query('SELECT * FROM public.operational_alert_reviews');
  assert.equal(archived.rows.length,2);assert(archived.rows.every(r=>r.task_id===null));assert.equal(archived.rows[0].snapshot.property,'Ejemplo');
  await db.exec('RESET ROLE; SET ROLE anon;');
  await assert.rejects(()=>db.query('SELECT * FROM public.operational_alert_reviews'));
  console.log('attention-reviews-sql: OK (exact SQL, RLS, sede/role boundaries, immutable snapshots, duplicate race, deletion retention; isolated WASM PostgreSQL)');
}finally{await db.close();}
