import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {build} from 'esbuild';
const repo=path.resolve(import.meta.dirname,'..');
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'limpatex-attention-'));
await build({entryPoints:[path.join(repo,'src/features/attention/domain.ts')],bundle:true,platform:'node',format:'esm',outfile:path.join(temp,'domain.mjs'),tsconfig:path.join(repo,'tsconfig.app.json')});
const {buildAttention,madridTimestamp}=await import(pathToFileURL(path.join(temp,'domain.mjs')));
const task={id:'t1',sedeId:'s1',date:'2026-10-05',startTime:'09:00',endTime:'10:00',propertyDurationMinutes:60,property:'Apartamento de ejemplo',client:'Cliente de ejemplo',cleanerId:'c1',cleaner:'Ana',status:'pending'};
const report={id:'r1',task_id:'t1',cleaner_id:'c1',overall_status:'in_progress',start_time:'2026-10-05T07:00:00Z',updated_at:'2026-10-05T07:00:00Z'};
const at=time=>new Date('2026-10-05T'+time+'+02:00');
const run=(time,reports=[],tasks=[task],keys=new Set())=>buildAttention(tasks,reports,'s1',at(time),keys);
const kind=result=>result.groups.flatMap(g=>g.alerts.map(a=>a.kind));
assert.deepEqual(kind(run('09:14:59')),[]);
assert.deepEqual(kind(run('09:15:00')),['late-start']);
assert.deepEqual(kind(run('10:14:59')),['late-start']);
assert.deepEqual(kind(run('10:15:00')),['missing-report']);
assert.deepEqual(kind(run('09:30:00',[report])),[]);
assert.deepEqual(kind(run('10:59:59',[report])),[]);
assert.deepEqual(kind(run('11:00:00',[report])),['unfinished']);
assert.deepEqual(kind(run('11:00:00',[report],[{...task,status:'completed'}])),['unfinished']);
for(const [minutes,expected] of [[40,true],[60,false],[70,false],[75,true],[80,true],[45,true],[46,false]]){
  const end=new Date(Date.parse(report.start_time)+minutes*60000).toISOString();
  const result=run('12:00:00',[{...report,overall_status:'completed',end_time:end}]);
  assert.equal(kind(result).includes('duration'),expected,`duration ${minutes}`);
}
const bad=run('12:00:00',[{...report,overall_status:'completed',end_time:report.start_time}]);
assert.equal(bad.groups.length,0); assert(bad.issues.length);
assert.equal(run('12:00:00',[{...report,overall_status:'completed',start_time:null,end_time:'2026-10-05T09:00:00Z'}]).groups.length,0);
const multi={...task,propertyDurationMinutes:120,endTime:'11:00',assignmentCount:2,assignments:[{cleaner_id:'c1',cleaner_name:'Ana'},{cleaner_id:'c2',cleaner_name:'Bea'}]};
const shared=run('11:00:00',[report],[multi]);
assert.equal(shared.groups.length,1);
assert.deepEqual(kind(shared),['unfinished','missing-report']);
assert.equal(shared.groups[0].alerts[0].cleanerName,'Ana');
assert(shared.groups[0].alerts[0].detail.includes('10:00'));
const occurrence=run('11:00:00',[report]).groups[0].alerts[0];
assert.equal(run('12:00:00',[report],[task],new Set([occurrence.key])).groups.length,0);
const closed=run('12:00:00',[{...report,overall_status:'completed',end_time:'2026-10-05T08:20:00Z'}],[task],new Set([occurrence.key]));
assert.deepEqual(kind(closed),['duration']);
assert.deepEqual(kind(run('12:00:00',[report],[{...task,endTime:'10:15'}],new Set([occurrence.key]))),['unfinished']);
assert.equal(run('12:00:00',[],[{...task,sedeId:'s2'}]).groups.length,0);
assert.equal(run('12:00:00',[],[{...task,cleanerId:undefined,cleaner:undefined}]).groups.length,0);
assert.equal(run('12:00:00',[],[{...task,isRecurringInstance:true}]).groups.length,0);
assert.equal(run('12:00:00',[],[{...task,date:'2026-10-04'}]).groups.length,0);
assert.equal(run('12:00:00',[report,{...report,id:'r2'}]).groups.length,0);
assert(run('12:00:00',[report,{...report,id:'r2'}]).issues.length);
assert.equal(madridTimestamp('2026-03-29','02:30'),null);
assert.equal(madridTimestamp('2026-99-99','09:00'),null);
assert.equal(madridTimestamp('2026-10-05','25:00'),null);
assert.equal(madridTimestamp('2026-01-05','09:00'),Date.parse('2026-01-05T08:00:00Z'));
assert.equal(madridTimestamp('2026-07-05','09:00'),Date.parse('2026-07-05T07:00:00Z'));
const snapshot=JSON.stringify({task,report});run('12:00:00',[report]);assert.equal(JSON.stringify({task,report}),snapshot);
const sorted=run('12:00:00',[report],[task,{...task,id:'t2'}]);assert.equal(sorted.groups[0].task.id,'t1');
console.log('attention-domain: OK (thresholds, +/- duration, shared assignments, review lifecycle, scope, invalid data, Madrid/DST, no writes)');
