import assert from 'node:assert/strict';
import { build } from 'esbuild';
const bundle = await build({ entryPoints: ['src/components/buildings/buildingDraft.ts'], bundle: true, write: false, platform: 'node', format: 'esm' });
const { createBuildingDraft, buildingChangeCount, saveBuildingDraft } = await import(`data:text/javascript;base64,${Buffer.from(bundle.outputFiles[0].text).toString('base64')}`);
const snapshot = { group: { id: 'g', name: 'Centro', supervisorName: 'Eva' }, team: [{ id: 'a', propertyGroupId: 'g', cleanerId: 'c', roleType: 'primary', priority: 17, knowledgeLevel: 4, maxTasksPerDay: 3, notes: 'Conservar', isActive: true }], properties: [{ id: 'p', propertyId: 'one', propertyGroupId: 'g' }] };
function storage(overrides = {}) {
  const writes = [];
  const api = { getPropertyGroups: async () => [snapshot.group], getCleanerAssignments: async () => snapshot.team, getAllPropertyAssignments: async () => snapshot.properties };
  for (const method of ['assignCleanerToGroup', 'updateCleanerAssignment', 'removeCleanerFromGroup', 'assignPropertyToGroup', 'removePropertyFromGroup', 'updatePropertyGroup']) api[method] = async (...args) => { writes.push([method, ...args]); };
  return { api: { ...api, ...overrides }, writes };
}
let draft = createBuildingDraft(snapshot);
assert.equal(buildingChangeCount(snapshot, draft), 0);
let fixture = storage();
await saveBuildingDraft(fixture.api, snapshot, draft);
assert.deepEqual(fixture.writes, [], 'Opening/no-op must never write');
draft.team[0].role = 'secondary';
assert.equal(snapshot.team[0].roleType, 'primary', 'Draft must not mutate saved state');
assert.equal(buildingChangeCount(snapshot, draft), 1);
await saveBuildingDraft(fixture.api, snapshot, draft);
assert.deepEqual(fixture.writes, [['updateCleanerAssignment', 'a', { roleType: 'secondary', priority: 20 }]], 'Changing role preserves limits, knowledge, notes and active state');
draft = createBuildingDraft(snapshot);
draft.team.push({ cleanerId: 'new', role: 'backup' });
draft.propertyIds = ['two']; draft.supervisorName = 'Nueva referencia';
fixture = storage(); await saveBuildingDraft(fixture.api, snapshot, draft);
assert.equal(fixture.writes[0][1].maxTasksPerDay, 8);
assert.deepEqual(fixture.writes.map(call => call[0]), ['assignCleanerToGroup', 'assignPropertyToGroup', 'removePropertyFromGroup', 'updatePropertyGroup']);
fixture = storage({ getCleanerAssignments: async () => [{ ...snapshot.team[0], priority: 55 }] });
await assert.rejects(saveBuildingDraft(fixture.api, snapshot, draft), /ha cambiado/);
assert.equal(fixture.writes.length, 0, 'Stale snapshot blocks all writes');
fixture = storage({ getAllPropertyAssignments: async () => [...snapshot.properties, { id: 'other', propertyGroupId: 'elsewhere', propertyId: 'two' }] });
await assert.rejects(saveBuildingDraft(fixture.api, snapshot, draft), /otro edificio/);
assert.equal(fixture.writes.length, 0);
fixture = storage({ assignPropertyToGroup: async () => { throw new Error('network'); } });
await assert.rejects(saveBuildingDraft(fixture.api, snapshot, draft), /network/);
assert.deepEqual(fixture.writes.map(call => call[0]), ['assignCleanerToGroup'], 'Stop after failure without replay or deleting remaining links');
draft = createBuildingDraft(snapshot); draft.team.push(draft.team[0]);
await assert.rejects(saveBuildingDraft(storage().api, snapshot, draft), /duplicados/);
console.log('Building draft: no-op, discard isolation, role preservation, linking, conflict, occupied property and partial failure passed.');
