import assert from 'node:assert/strict';
import { build } from 'esbuild';
import { chromium, expect } from '@playwright/test';
import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import postcss from 'postcss';
import tailwindcss from 'tailwindcss';
import autoprefixer from 'autoprefixer';

const properties = Array.from({ length: 26 }, (_, index) => ({ id: `p${index + 1}`, nombre: `Apartamento ${String(index + 1).padStart(2, '0')}`, cliente_id: index < 13 ? 'c1' : 'c2', coste_servicio: index < 13 ? 100 : 120, duracion_servicio: 60, amenities_control_enabled: false,
  property_group_assignments: [{ property_group_id: index < 13 ? 'g1' : 'g2', group: index === 0 ? [{ id: 'g1', name: 'Edificio Centro', is_active: true }] : { id: index < 13 ? 'g1' : 'g2', name: index < 13 ? 'Edificio Centro' : 'Edificio Mar', is_active: true } }] }));
const task = (property, date, prefix) => ({ id: `${prefix}-${property.id}`, type: 'limpieza-turistica', date, status: 'pending', coste: 0, cliente_id: property.cliente_id, propiedad_id: property.id, property: property.nombre, cleaner_id: property.cliente_id === 'c1' ? 'w1' : 'w2', cleaner: property.cliente_id === 'c1' ? 'Ana' : 'Bea', start_time: '10:00', end_time: '11:00', duracion: 60, task_assignments: [] });
const data = { properties: [...properties, { ...properties[0], id: 'pzero', nombre: 'Jornada sin factura', coste_servicio: 0 }], tasks: [...properties.map(property => task(property, '2026-09-10', 'sep')), ...properties.slice(0, 5).map(property => task(property, '2026-08-10', 'aug')), ...properties.slice(0, 7).map(property => task(property, '2025-09-10', 'old')), { ...task({ ...properties[0], id: 'pzero', nombre: 'Jornada sin factura' }, '2026-09-01', 'zero'), type: 'check in' }], clients: [{ id: 'c1', nombre: 'Cliente Centro' }, { id: 'c2', nombre: 'Cliente Mar' }], cleaners: [{ id: 'w1', name: 'Ana' }, { id: 'w2', name: 'Bea' }], stock_property_consumption_rules: [], tourist_budgets: [{ id: 'q1', title: 'Apartamento Centro', quote_number: 'Q-1', client_id: 'c1', status: 'accepted', current_version_number: 2 }], tourist_budget_versions: [{ id: 'v2', budget_id: 'q1', version_number: 2 }], tourist_budget_items: [{ id: 'i1', budget_version_id: 'v2', property_id: 'p1', result_snapshot: { monthly: { totalRevenue: 500, totalCost: 200 } } }] };
const settings = { version: 1, rates: [], adjustments: {}, expenses: [], policies: ['c1', 'c2'].map(clientId => ({ clientId, propertyId: '', laundry: false, kits: false, consumables: false })), incomes: [{ id: 'reception', label: 'Recepción de prueba', mode: 'monthly', start: '2026-09-01', end: '2026-09-30', income: 10000, cost: 3000, weeklyHours: 0, costCategory: 'personal', clientId: 'c2', propertyId: '', workerId: '', notes: '', overrides: {} }, { id: 'unknown', label: 'Ingreso con coste pendiente', mode: 'manual', start: '2026-09-01', end: '', income: 2000, cost: null, weeklyHours: 0, costCategory: 'other', clientId: 'c2', propertyId: '', workerId: '', notes: '', overrides: {} }] };
const modules = {
  '@/contexts/SedeContext': "export const useSede=()=>({activeSede:{id:'s',nombre:'Sede de prueba'}});",
  '@/hooks/useAuth': "export const useAuth=()=>({user:{id:'u'}});",
  '@/integrations/supabase/client': `const data=${JSON.stringify(data)},settings=${JSON.stringify(settings)};export const supabase={from(table){const calls=[];const q={select(...args){calls.push(['select',...args]);return q},eq(...args){calls.push(['eq',...args]);return q},gte(...args){calls.push(['gte',...args]);return q},lte(...args){calls.push(['lte',...args]);return q},order(...args){calls.push(['order',...args]);return q},insert(){window.writes++;throw new Error('Unexpected write')},update(){window.writes++;throw new Error('Unexpected write')},async maybeSingle(){return {data:{document:settings,revision:1},error:null}},async single(){if(window.failBudget)return {data:null,error:{message:'Budget read failed'}};return {data:data[table].find(row=>calls.every(([op,key,value])=>op!=='eq'||row[key]===value)),error:null}},async range(from,to){window.reads.push({table,calls,from,to});if(window.failSource && table==='tasks'||window.failBudget && table.startsWith('tourist_'))return {data:null,error:{message:'Read unavailable'}};const rows=data[table].filter(row=>calls.every(([op,key,value])=>key==='sede_id'||op==='eq'&&row[key]===value||op==='gte'&&row[key]>=value||op==='lte'&&row[key]<=value||!['eq','gte','lte'].includes(op)));return {data:rows.slice(from,to+1),error:null}}};return q}};`,
};
const built = await build({ stdin: { contents: "import React from 'react';import {createRoot} from 'react-dom/client';import {MemoryRouter} from 'react-router-dom';import {QueryClient,QueryClientProvider} from '@tanstack/react-query';import Page from './src/features/financial/FinancialAnalysisPage';const queryClient=new QueryClient({defaultOptions:{queries:{retry:false}}});window.financeTestClient=queryClient;createRoot(document.getElementById('root')).render(<MemoryRouter><QueryClientProvider client={queryClient}><Page/></QueryClientProvider></MemoryRouter>);", resolveDir: process.cwd(), loader: 'tsx' }, bundle: true, write: false, platform: 'browser', format: 'iife', jsx: 'automatic', metafile: true, outdir: join(tmpdir(), 'financial-p2-browser'), define: { 'process.env.NODE_ENV': '"production"' }, plugins: [{ name: 'financial-p2-fixture', setup(plugin) { plugin.onResolve({ filter: /.*/ }, args => Object.hasOwn(modules, args.path) ? { path: args.path, namespace: 'fixture' } : null); plugin.onLoad({ filter: /.*/, namespace: 'fixture' }, args => ({ contents: modules[args.path], loader: 'js' })); } }] });
assert.ok(!Object.keys(built.metafile.inputs).some(path => path.startsWith('src/integrations/supabase')), 'The production client must never be bundled');
const cssSource = readFileSync('src/index.css', 'utf8').replace(/^\s*@import\s+"@fontsource\/[^"\n]+";\s*$/gm, '');
const { css } = await postcss([tailwindcss('tailwind.config.ts'), autoprefixer]).process(cssSource + '\n' + built.outputFiles.filter(file => file.path.endsWith('.css')).map(file => file.text).join('\n'), { from: 'src/index.css' });
const html = `<html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>${css}</style></head><body><div id="root"></div><script>${built.outputFiles.find(file => file.path.endsWith('.js')).text.replaceAll('</script', '<\\/script')}</script></body></html>`;
const executablePath = process.platform === 'linux' && existsSync('/usr/bin/google-chrome') ? '/usr/bin/google-chrome' : undefined;
const browser = await chromium.launch({ headless: true, executablePath });
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1050 }, acceptDownloads: true });
  await context.addInitScript(() => { window.reads=[];window.writes=0; if (!sessionStorage.getItem('limpatex-financial-v1:u:s:view')) sessionStorage.setItem('limpatex-financial-v1:u:s:view', JSON.stringify({ filters:{start:'2026-09-01',end:'2026-09-30',clients:[],properties:[],workers:[]},tab:'general',profitFilter:'all' })); });
  const page = await context.newPage(), errors = [], unexpected = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.route('**/*', route => route.request().url() === 'https://financial.p2.local/' ? route.fulfill({ contentType: 'text/html', body: html }) : (unexpected.push(route.request().url()), route.abort()));
  await page.goto('https://financial.p2.local/');
  const indicators = page.getByRole('region', { name: 'Indicadores financieros' }), comparison = page.getByRole('region', { name: 'Comparativas financieras' }), props = page.getByRole('region', { name: 'Análisis por propiedad' });
  const filter = label => page.locator('details').filter({ has: page.locator('summary').filter({ hasText: `${label}:` }) });
  const open = async label => { const target = filter(label); if (!await target.evaluate(node=>node.open)) await target.locator('summary').click(); return target; };
  const clear = async label => { const target = await open(label); await target.getByRole('button', { name: 'Mostrar todos', exact: true }).click(); await target.locator('summary').click(); };
  await expect(indicators.getByRole('article', { name: 'Ingresos totales' })).toContainText('2.980,00');
  for (const label of ['Clientes', 'Propiedades', 'Edificios', 'Trabajadores', 'Tipos de servicio', 'Categorías de gasto']) await expect(filter(label).locator('summary')).toBeVisible();
  assert.equal(await page.locator('summary').filter({ hasText: 'Fechas personalizadas y filtros' }).evaluate(node=>node.parentElement.open), false, 'Data filters must be visible while custom dates remain collapsed');
  await expect(props).toContainText('26 propiedades con actividad');
  await expect(props.getByRole('table')).toContainText('2.860,00');
  await props.getByRole('button', { name: 'Página siguiente de propiedades' }).click(); await expect(props.getByRole('table')).toContainText('Apartamento 11'); await expect(props.getByRole('table')).toContainText('2.860,00');
  await (await open('Edificios')).getByLabel('Edificio Centro', { exact:true }).check(); await filter('Edificios').locator('summary').click();
  await expect(indicators.getByRole('article', { name:'Ingresos totales' })).toContainText('1.300,00'); await expect(props).toContainText('13 propiedades con actividad');
  await (await open('Clientes')).getByLabel('Cliente Mar',{exact:true}).check(); await filter('Clientes').locator('summary').click(); await expect(indicators.getByRole('article',{name:'Ingresos totales'})).toContainText('0,00');
  await clear('Clientes'); await clear('Edificios');
  await (await open('Categorías de gasto')).getByLabel('Personal · incluye dirección',{exact:true}).check(); await filter('Categorías de gasto').locator('summary').click();
  await expect(indicators.getByRole('article',{name:'Gastos incluidos'})).toContainText('2.724,00'); await expect(indicators.getByText('Parcial · provisional',{exact:true})).toHaveCount(4); await expect(page.getByText(/Vista parcial de gastos:/)).toBeVisible(); await clear('Categorías de gasto');
  await (await open('Tipos de servicio')).getByLabel('check-in',{exact:true}).check(); await filter('Tipos de servicio').locator('summary').click();
  await expect(indicators.getByRole('article',{name:'Ingresos totales'})).toContainText('0,00'); await expect(page.getByRole('region',{name:'Alertas financieras'})).toContainText('Servicios con ingreso cero · 1'); await clear('Tipos de servicio');
  const balanceBefore = await indicators.getByRole('article',{name:'Resultado',exact:true}).textContent();
  await page.getByLabel('Reparto de gastos generales',{exact:true}).selectOption('revenue');
  await expect(indicators.getByRole('article',{name:'Resultado',exact:true})).toHaveText(balanceBefore);
  await expect(page.getByRole('region',{name:'Alertas financieras'})).toContainText('Clientes con margen bajo · 2');
  await page.getByLabel('Avisar si el margen del cliente es inferior a (%)').fill('0'); await expect(page.getByRole('region',{name:'Alertas financieras'})).toContainText('Clientes con margen bajo · 0');
  await expect(page.getByRole('region',{name:'Alertas financieras'})).toContainText('Costes pendientes antiguos · 1'); await page.getByLabel('Costes pendientes con más de (días)').fill('90'); await expect(page.getByRole('region',{name:'Alertas financieras'})).toContainText('Costes pendientes antiguos · 0');
  await page.getByLabel('Avisar de servicios con ingreso cero').uncheck(); await expect(page.getByRole('region',{name:'Alertas financieras'})).toContainText('Aviso desactivado.');
  await comparison.getByRole('button',{name:'Mismo periodo año anterior',exact:true}).click(); await expect(comparison).toContainText('2025-09-01 – 2025-09-30');
  await expect.poll(()=>page.evaluate(()=>window.reads.filter(row=>row.table==='tasks').at(-1).calls.find(call=>call[0]==='gte')[2])).toBe('2025-09-01');
  const previousRevenue = comparison.getByRole('button',{name:/^Ingresos · Anterior ·/}); await previousRevenue.press('Enter'); await expect(page.getByRole('heading',{name:'Ingresos · desglose',exact:true})).toBeVisible(); await expect(page.getByLabel('Desde',{exact:true})).toHaveValue('2025-09-01'); await page.getByRole('button',{name:'Volver al gráfico',exact:true}).click(); await expect(previousRevenue).toBeFocused();
  await comparison.getByRole('button',{name:/^Resultado · Seleccionado ·/}).press('Enter'); await expect(page.getByRole('heading',{name:'Resultado · desglose',exact:true})).toBeVisible(); await page.getByRole('button',{name:'Volver al gráfico',exact:true}).click();
  await comparison.getByRole('button',{name:'Presupuesto',exact:true}).click(); await expect(page.getByLabel('Presupuesto para comparar')).toContainText('Q-1'); await page.getByLabel('Presupuesto para comparar').selectOption('q1'); await expect(comparison).toContainText('500,00'); await expect(comparison).toContainText('Versión 2'); await expect(comparison.getByRole('article').first()).toContainText('100,00');
  await (await open('Trabajadores')).getByLabel('Ana',{exact:true}).check(); await filter('Trabajadores').locator('summary').click(); await expect(comparison).toContainText('Quita esos filtros'); await clear('Trabajadores');
  await page.evaluate(()=>{window.failBudget=true;window.financeTestClient.invalidateQueries({queryKey:['financial-budget-projection']});}); await expect(comparison.getByRole('alert')).toContainText('No se pudo cargar'); await expect(comparison.getByRole('article')).toHaveCount(0); await page.evaluate(()=>{window.failBudget=false;}); await comparison.getByRole('button',{name:'Reintentar lectura',exact:true}).click(); await expect(comparison.getByRole('article')).toHaveCount(4);
  await comparison.getByRole('button',{name:'Mismo periodo año anterior',exact:true}).click();
  await page.reload(); await expect(page.getByLabel('Reparto de gastos generales',{exact:true})).toHaveValue('revenue'); await expect(page.getByLabel('Costes pendientes con más de (días)')).toHaveValue('90'); await expect(comparison.getByRole('button',{name:'Mismo periodo año anterior',exact:true})).toHaveAttribute('aria-pressed','true');
  await page.locator('summary').filter({hasText:'Informes y exportación'}).click();
  for (const [button, suffix] of [['CSV','.csv'],['Excel completo','.xlsx'],['Informe PDF','.pdf']]) { const download = page.waitForEvent('download'); await page.getByRole('button',{name:button,exact:true}).click(); const result = await download; assert.ok(result.suggestedFilename().endsWith(suffix)); assert.equal(await result.failure(), null); }
  await page.locator('summary').filter({hasText:'Informes y exportación'}).click();
  await page.screenshot({path:join(tmpdir(),'limpatex-financial-p2-desktop.png'),fullPage:true});
  await props.screenshot({path:join(tmpdir(),'limpatex-financial-p2-properties-demo.png')});
  for (const width of [375,768,1024,1440]) { await page.setViewportSize({width,height:900}); assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`Viewport ${width} must not overflow`); await expect(filter('Clientes').locator('summary')).toBeVisible(); }
  await page.setViewportSize({width:375,height:900}); await (await open('Propiedades')).getByLabel('Apartamento 01',{exact:true}).check(); await filter('Propiedades').locator('summary').click(); await expect(indicators.getByRole('article',{name:'Ingresos totales'})).toContainText('100,00'); await page.getByRole('button',{name:'Por propiedad',exact:true}).click(); await expect(props.getByRole('table')).toContainText('Apartamento 01'); await page.screenshot({path:join(tmpdir(),'limpatex-financial-p2-mobile.png'),fullPage:true});
  assert.equal(await page.evaluate(()=>window.writes),0); assert.deepEqual(errors,[]); assert.deepEqual(unexpected,[]);
  console.log('financial-analytics-browser: real page and readonly sources, six visible filters and empty intersections, partial-cost badges, KPIs/property pages, unchanged global balance, allocation/alerts persistence, year drilldown and focus, budget scoped comparison/error, downloads and four screen sizes passed');
} finally { await browser.close(); }
