import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {pathToFileURL} from 'node:url';
const dir=mkdtempSync(join(tmpdir(),'financial-external-'));
try {
  await build({stdin:{contents:"export * from './src/features/financial/financialModel';export * from './src/features/financial/financialSource';",resolveDir:process.cwd()},outfile:join(dir,'model.mjs'),bundle:true,platform:'node',format:'esm',logLevel:'silent'});
  const {newSettings,analyze,readSettings,buildServices}=await import(pathToFileURL(join(dir,'model.mjs')));
  const filters={start:'2026-09-01',end:'2026-09-30',clients:[],properties:[],workers:[]};
  const base={id:'fixed',label:'Recepción',mode:'monthly',start:filters.start,end:'',income:132960,cost:0,weeklyHours:16,costCategory:'other',clientId:'c',propertyId:'',workerId:'',notes:'',overrides:{}};
  const settings={...newSettings(),rates:[{item:'tourismSalary',date:'2000-01-01',mills:0}],incomes:[base]};
  let result=analyze([],settings,filters);
  assert.equal(result.total.revenue,132960);assert.equal(result.total.costs.personal,100804);assert.equal(result.total.result,32156);assert.equal(result.total.services,0);
  assert.equal(result.clients[0].revenue,132960);assert.equal(result.general.revenue,0);
  result=analyze([],{...settings,incomes:[{...base,id:'hostel',income:249369,weeklyHours:35}]},filters);
  assert.equal(result.total.costs.personal,220509);assert.equal(result.total.result,28860);
  result=analyze([],{...settings,incomes:[{...base,clientId:''}]},filters);
  assert.equal(result.clients.length,0);assert.equal(result.general.revenue,result.total.revenue);assert.equal(result.general.expense,result.total.expense);
  const partial=analyze([],settings,{...filters,end:'2026-09-15'});
  assert.equal(partial.total.revenue,66480);assert.equal(partial.total.costs.personal,50402);
  assert.equal(analyze([],settings,{...filters,start:'2026-09-16'}).total.revenue+partial.total.revenue,result.total.revenue);
  assert.equal(analyze([],settings,{...filters,end:'2026-10-31'}).total.revenue,265920);
  assert.equal(analyze([],settings,{...filters,start:'2026-08-01',end:'2026-08-31'}).total.revenue,0);
  assert.equal(analyze([],{...settings,incomes:[{...base,end:'2026-09-15'}]},filters).total.revenue,66480);
  const exception={...base,overrides:{'2026-09':{income:150000,cost:1000,weeklyHours:20}}};
  result=analyze([],{...settings,incomes:[exception]},filters);
  assert.equal(result.total.revenue,150000);assert.equal(result.total.costs.personal,126005);assert.equal(result.total.costs.other,1000);
  assert.equal(analyze([],{...settings,incomes:[exception]},{...filters,start:'2026-10-01',end:'2026-10-31'}).total.revenue,132960);
  const laundry={...base,id:'laundry',mode:'manual',start:'2026-09-30',income:250545,cost:202470,weeklyHours:0,costCategory:'laundry'};
  result=analyze([],{...settings,incomes:[laundry]},filters);
  assert.equal(result.total.revenue,250545);assert.equal(result.total.expense,202470);assert.equal(result.total.result,48075);assert.equal(result.total.costs.products,0);
  assert.equal(analyze([],{...settings,incomes:[laundry]},{...filters,end:'2026-09-29'}).total.revenue,0);
  result=analyze([],{...settings,incomes:[{...laundry,cost:null}]},filters);
  assert.equal(result.total.pending,1);assert.equal(result.incomes[0].pending[0],'Coste externo pendiente');
  for(const field of ['clients','properties','workers'])assert.equal(analyze([],settings,{...filters,[field]:['unrelated']}).total.revenue,0);
  const service={id:'task',date:'2026-09-10',type:'limpieza-turistica',clientId:'c',clientName:'Cliente',propertyId:'p',propertyName:'Casa',revenue:10000,revenueEstimated:true,workers:[{id:'w1',name:'A',minutes:270,actual:false},{id:'w2',name:'B',minutes:270,actual:false}],quantities:{doubleSheet:40,kitchenKit:2,toiletPaper:2}};
  const supplement={...base,id:'virtual',mode:'perCleaning',income:275,weeklyHours:0};
  const rules={...settings,incomes:[supplement],policies:[{clientId:'c',propertyId:'',laundry:false,kits:false,consumables:false}]};
  result=analyze([service],rules,filters);
  assert.equal(result.total.revenue,10275);assert.equal(result.total.costs.products,300);assert.equal(result.total.costs.personal,13050);assert.equal(result.total.costs.laundry,0);assert.equal(result.total.costs.supplies,0);assert.equal(result.incomes.length,0);
  const restored=analyze([service],{...rules,policies:[...rules.policies,{clientId:'c',propertyId:'p',laundry:true}]},filters);
  assert.equal(restored.total.costs.laundry,2200);assert.equal(restored.total.costs.supplies,0); // Property opt-in overrides client exclusion; other flags inherit.
  assert.equal(analyze([service,service].map((s,i)=>({...s,id:String(i)})),rules,{...filters,workers:['w1','w2']}).total.revenue,20550);
  assert.equal(analyze([{...service,revenue:0}],rules,filters).total.revenue,0);
  assert.equal(analyze([service],{...rules,incomes:[{...supplement,start:'2026-09-11'}]},filters).total.revenue,10000);
  const montse={...rules,policies:[{clientId:'c',propertyId:'',laundry:false,kits:false,consumables:false,minutes:90}]};
  assert.equal(analyze([service],montse,filters).total.costs.personal,2175);
  result=analyze([{...service,propertyName:'Check in apartamento'}],rules,filters);
  assert.equal(result.total.costs.personal,1450);assert.equal(result.total.costs.products,0);assert.equal(result.total.costs.supplies,0);assert.equal(result.total.revenue,10000);
  const pan={...rules,policies:[{clientId:'c',propertyId:'',kits:false}]};
  result=analyze([service],pan,filters);assert.equal(result.total.costs.laundry,2200);assert.equal(result.total.costs.supplies,26);
  const property={id:'p',nombre:'Casa',cliente_id:'c',coste_servicio:20.35,duracion_servicio:60,numero_sabanas:10,amenities_bano:9};
  const task={id:'t',type:'limpieza',date:'2026-09-10',status:'pending',coste:9.93,cliente_id:'c',propiedad_id:'p',property:'Casa',cleaner_id:'w1',cleaner:'A',start_time:'10:00',end_time:'11:00',task_assignments:[]};
  const custom=buildServices([task],[property],[{id:'c',name:'Cliente',amenitiesControlEnabled:false}],[],'2026-10-07',[{property_id:'p',quantity_per_cleaning:2,product:{name:'Sabanas matrimonio'}},{property_id:'p',quantity_per_cleaning:1,product:{name:'PAÑOS DE COCINA'}},{property_id:'p',quantity_per_cleaning:2,product:{name:'BOLSAS DE BASURA 30L'}}])[0];
  assert.equal(custom.revenue,2035);assert.equal(custom.quantities.doubleSheet,2);assert.equal(custom.quantities.kitchenCloth,1);assert.equal(custom.quantities.bathKit,0);
  assert.ok(analyze([custom],settings,filters).services[0].pending.some(p=>p.includes('BOLSAS')));
  assert.deepEqual(readSettings(JSON.parse(JSON.stringify(rules))),rules);
  for(const invalid of [{...base,income:-1},{...base,cost:-1},{...base,weeklyHours:NaN},{...base,weeklyHours:169},{...base,end:'2026-08-31'},{...base,overrides:{'2026-9':{income:1,cost:0,weeklyHours:0}}},{...supplement,cost:1},{...laundry,weeklyHours:1}])assert.throws(()=>readSettings({...settings,incomes:[invalid]}));
  assert.throws(()=>readSettings({...settings,incomes:[base,base]}));
  console.log('financial-external: fixed/manual/supplement, 4.345, period replacement, filters, personalized consumptions, check-in, property tariffs and validation passed');
}finally{rmSync(dir,{recursive:true,force:true});}
