import assert from 'node:assert/strict';
import { build } from 'esbuild';
import { chromium, expect } from '@playwright/test';
import { existsSync, readFileSync } from 'node:fs';
import postcss from 'postcss';
import tailwindcss from 'tailwindcss';
import autoprefixer from 'autoprefixer';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
const fixture = `import React,{useState} from 'react';import {createRoot} from 'react-dom/client';
import {FinancialIndicators} from './src/features/financial/FinancialIndicators';import {FinancialClientTable} from './src/features/financial/FinancialClientTable';import {FinancialTrend} from './src/features/financial/FinancialEvolution';import {financialInsights} from './src/features/financial/financialInsights';import {analyze,QUANTITY_ITEMS} from './src/features/financial/financialModel';
const names=Array.from({length:26},(_,i)=>({id:'c'+String(i).padStart(2,'0'),name:'Cliente '+String(i).padStart(2,'0')}));
const services=names.flatMap((client,i)=>['2026-08-20','2026-09-20'].map((date,index)=>({id:client.id+date,type:'limpieza',date,clientId:client.id,clientName:client.name,propertyId:'p'+i,propertyName:'Piso '+i,revenue:(i+1)*1000*(index+1),revenueEstimated:false,workers:[{id:'w',name:'Ana',minutes:60,actual:true}],quantities:Object.fromEntries(QUANTITY_ITEMS.map(item=>[item.id,0]))})));
const settings={version:1,rates:[],adjustments:{},expenses:[]};window.selectedClients=[];
function Fixture(){const [only,setOnly]=useState(false),[empty,setEmpty]=useState(false),[view,setView]=useState({open:true,matchingDays:false,comparison:'balance',chart:'lines'});const filters={start:'2026-09-01',end:'2026-09-30',clients:empty?['missing']:only?['c00']:[],properties:[],workers:[]};const result=analyze(services,settings,filters);window.fixtureTotals=result.total;
return <main className="mx-auto max-w-[1440px] space-y-5 bg-[#f7f5fc] p-4"><h1 className="text-3xl font-bold text-[#310984]">Análisis financiero · datos de prueba</h1><div className="flex gap-4"><label><input type="checkbox" checked={only} onChange={e=>setOnly(e.target.checked)}/>Un cliente</label><label><input type="checkbox" checked={empty} onChange={e=>setEmpty(e.target.checked)}/>Sin actividad</label></div><FinancialIndicators summary={result.total} insights={financialInsights(services,settings,filters)}/><FinancialTrend services={services} settings={settings} filters={filters} view={view} onViewChange={patch=>setView(v=>({...v,...patch}))} onDetails={(id,period)=>{window.detail={id,period}}}/><section aria-label="Clientes" className="min-w-0 rounded-2xl bg-white p-5"><h2 className="mb-4 text-lg font-semibold text-[#310984]">Tabla de resultados por cliente</h2><FinancialClientTable result={result} names={names} onClient={id=>window.selectedClients.push(id)}/></section></main>}
createRoot(document.getElementById('root')).render(<Fixture/>);`;
const built = await build({ stdin: { contents: fixture, resolveDir: process.cwd(), loader: 'tsx' }, bundle: true, write: false, outdir: join(tmpdir(), 'financial-design-bundle'), platform: 'browser', format: 'iife', jsx: 'automatic', metafile: true, define: { 'process.env.NODE_ENV': '"production"' } });
assert.ok(!Object.keys(built.metafile.inputs).some(path => /integrations\/supabase|useFinancialData|financialPersistence/.test(path)), 'Fixture must not bundle a backend');
const source = readFileSync('src/index.css', 'utf8').replace(/^\s*@import\s+"@fontsource\/[^"\n]+";\s*$/gm, '');
const { css } = await postcss([tailwindcss('tailwind.config.ts'), autoprefixer]).process(source + built.outputFiles.filter(file => file.path.endsWith('.css')).map(file => file.text).join('\n'), { from: 'src/index.css' });
const html = `<html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>${css}</style></head><body><div id="root"></div><script>${built.outputFiles.find(file => !file.path.endsWith('.css')).text.replaceAll('</script','<\\/script')}</script></body></html>`;
const executablePath = process.platform === 'linux' && existsSync('/usr/bin/google-chrome') ? '/usr/bin/google-chrome' : undefined;
const browser = await chromium.launch({ headless: true, executablePath });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1050 } });
  const errors = [], requests = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.route('**/*', route => route.request().url() === 'https://financial-design.local.test/' ? route.fulfill({ contentType: 'text/html', body: html }) : (requests.push(route.request().url()), route.abort()));
  await page.goto('https://financial-design.local.test/');
  const indicators = page.getByRole('region', { name: 'Indicadores financieros' }), trend = page.getByRole('region', { name: 'Evolución mensual' }), clients = page.getByRole('region', { name: 'Clientes', exact: true });
  await expect(indicators.getByText('Provisional', { exact: true })).toHaveCount(4);
  await expect(indicators.locator('.recharts-line')).toHaveCount(4);
  await expect(indicators.getByRole('article', { name: 'Ingresos totales' })).toContainText('+3.510,00 € · 100,0%');
  await expect(indicators.getByRole('article', { name: 'Gastos incluidos' })).toContainText('vs mes anterior');
  assert.ok(await indicators.getByRole('article', { name: 'Gastos incluidos' }).locator('[class*="text-rose-700"]').count(), 'Increasing expenses must be unfavorable');
  await indicators.getByRole('button', { name: 'Cómo se calcula: Indicadores', exact: true }).press('Enter');
  await expect(page.getByText('No existe un cierre contable registrado.', { exact: false })).toBeVisible();
  await page.getByRole('button', { name: 'Cerrar ayuda: Indicadores', exact: true }).press('Enter');
  await expect(page.getByText('No existe un cierre contable registrado.', { exact: false })).not.toBeVisible();
  await expect(indicators.getByRole('button', { name: 'Cómo se calcula: Indicadores', exact: true })).toBeFocused();
  await expect(trend.locator('.recharts-line')).toHaveCount(3);
  await expect(trend.locator('.recharts-xAxis .recharts-cartesian-axis-tick')).toHaveCount(12);
  await trend.locator('.recharts-line').first().locator('.recharts-dot').last().hover();
  await expect(trend.getByRole('tooltip')).toContainText('Ingresos: 7.020,00 €');
  await trend.getByRole('button', { name: 'Ingresos', exact: true }).click();
  await expect(trend.getByRole('button', { name: 'Ingresos', exact: true })).toHaveAttribute('aria-pressed', 'false');
  await trend.getByRole('button', { name: 'Ingresos', exact: true }).click();
  await expect(trend.locator('.recharts-line')).toHaveCount(3);
  await expect(clients.locator('tbody tr')).toHaveCount(10);
  const totalBefore = await clients.locator('tfoot').textContent();
  await expect(clients.locator('tbody tr').first()).toContainText('Cliente 25');
  await clients.getByRole('button', { name: 'Ordenar por Cliente', exact: true }).click();
  await expect(clients.getByRole('columnheader', { name: 'Ordenar por Cliente', exact: true })).toHaveAttribute('aria-sort', 'ascending');
  await expect(clients.locator('tbody tr').first()).toContainText('Cliente 00');
  await clients.getByRole('button', { name: 'Página siguiente de clientes' }).click();
  await expect(clients.locator('tbody tr').first()).toContainText('Cliente 10');
  await clients.getByRole('button', { name: 'Página siguiente de clientes' }).click();
  await expect(clients.locator('tbody tr')).toHaveCount(6);
  await expect(clients.getByRole('button', { name: 'Página siguiente de clientes' })).toBeDisabled();
  assert.equal(await clients.locator('tfoot').textContent(), totalBefore, 'Pagination cannot change total or general activity');
  await clients.getByLabel('Clientes por página').selectOption('25');
  await expect(clients.locator('tbody tr')).toHaveCount(25);
  await expect(clients.getByRole('status')).toContainText('1–25 de 26');
  await clients.getByRole('button', { name: 'Ordenar por Ingresos', exact: true }).press('Enter');
  await expect(clients.locator('tbody tr').first()).toContainText('Cliente 25');
  await clients.getByRole('button', { name: 'Ordenar por Ingresos', exact: true }).press('Enter');
  await expect(clients.locator('tbody tr').first()).toContainText('Cliente 00');
  await clients.getByRole('button', { name: 'Cliente 00', exact: true }).click();
  assert.deepEqual(await page.evaluate(() => window.selectedClients), ['c00']);
  await page.getByLabel('Un cliente', { exact: true }).check();
  await expect(clients.locator('tbody tr')).toHaveCount(1);
  await expect(clients.getByRole('status')).toContainText('1–1 de 1');
  await expect(clients.locator('tbody td').last()).toHaveClass(/text-emerald-700/);
  await page.getByLabel('Sin actividad', { exact: true }).check();
  await expect(clients).toContainText('Sin actividad de clientes');
  await expect(indicators.getByRole('article', { name: 'Margen', exact: true })).toContainText('Sin base comparativa');
  await expect(clients.getByRole('button', { name: 'Página siguiente de clientes' })).toBeDisabled();
  await page.getByLabel('Sin actividad', { exact: true }).uncheck();
  await page.getByLabel('Un cliente', { exact: true }).uncheck();
  await clients.getByLabel('Clientes por página').selectOption('10');
  await page.screenshot({ path: join(tmpdir(), 'limpatex-financial-p1-desktop.png'), fullPage: true });
  for (const width of [375, 768, 1024, 1440]) {
    await page.setViewportSize({ width, height: 900 });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'No page overflow at ' + width);
    await expect(indicators.getByRole('article', { name: 'Ingresos totales' })).toBeVisible();
  }
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: join(tmpdir(), 'limpatex-financial-p1-mobile.png'), fullPage: true });
  await trend.getByRole('button', { name: 'Ocultar evolución', exact: true }).click();
  await expect(trend.locator('svg.recharts-surface')).toHaveCount(0);
  await expect(trend.locator('.recharts-cartesian-axis-tick')).toHaveCount(0);
  assert.deepEqual(errors, []); assert.deepEqual(requests, []);
  console.log('financial-design: four KPI deltas/sparklines/provisional badges, expense semantics, keyboard help, twelve visible months, real tooltip/legend, sorting/pagination/stable totals/client IDs, filters/empty/margins, collapse and four responsive widths passed');
} finally { await browser.close(); }
