import assert from 'node:assert/strict';
import { build } from 'esbuild';
import { chromium, expect } from '@playwright/test';
import { readFileSync, existsSync } from 'node:fs';
import postcss from 'postcss';
import tailwindcss from 'tailwindcss';
import autoprefixer from 'autoprefixer';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
const modules = {
  '@/contexts/SedeContext': "export const useSede=()=>({activeSede:{id:'s',nombre:'Sede de prueba'}});",
  '@/hooks/useAuth': "export const useAuth=()=>({user:{id:'u'}});",
  '@/integrations/supabase/client': `
    const date=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Madrid'}).format(new Date());
    const data={tasks:[{id:'t',type:'limpieza-turistica',date,status:'pending',coste:0,cliente_id:'c',propiedad_id:'p',property:'Apartamento Centro',cleaner_id:'w1',cleaner:'Ana',start_time:'10:00',end_time:'11:00',task_assignments:[{cleaner_id:'w1',cleaner_name:'Ana'},{cleaner_id:'w2',cleaner_name:'Bea'}],task_reports:[]}],
      properties:[{id:'p',nombre:'Apartamento Centro',cliente_id:'c',coste_servicio:100,duracion_servicio:120,numero_sabanas:2,numero_sabanas_pequenas:0,numero_sabanas_suite:0,numero_fundas_almohada:2,numero_toallas_grandes:2,numero_toallas_pequenas:2,numero_alfombrines:1,amenities_cocina:1,amenities_bano:1,kit_alimentario:1,cantidad_rollos_papel_higienico:2}],clients:[{id:'c',nombre:'Cliente de prueba'},{id:'c2',nombre:'Cliente sin servicios'}],cleaners:[{id:'w1',name:'Ana'},{id:'w2',name:'Bea'},{id:'nc',name:'NOT COUNT'}]};
    const task=data.tasks[0]; task.duracion=120; task.end_time='12:00'; // Two hours total, one hour per each of two people.
    data.properties.push({...data.properties[0],id:'pzero',nombre:'Jornada Hotel de prueba',coste_servicio:0});
    data.tasks.push({...task,id:'no-income',propiedad_id:'pzero',coste:0},
      {...task,id:'missing-income',propiedad_id:'missing',property:'Servicio con precio pendiente',coste:null});
    data.tasks.push({...task,id:'excluded-nc',coste:999,task_assignments:[{cleaner_id:'nc',cleaner_name:'Nombre antiguo'}]},
      {...task,id:'excluded-past',date:'2000-01-01',coste:999,cleaner_id:null,task_assignments:[]},
      {...task,id:'excluded-cancelled',status:'cancelled',coste:999});
    data.stock_property_consumption_rules=[];
    export const supabase={from(table){const calls=[];let payload=null;const q={select(...a){calls.push(['select',...a]);return q},insert(value){payload=value;return q},update(value){payload=value;return q},eq(...a){calls.push(['eq',...a]);return q},gte(...a){calls.push(['gte',...a]);return q},lte(...a){calls.push(['lte',...a]);return q},order(...a){calls.push(['order',...a]);return q},async maybeSingle(){if(table!=='financial_settings')throw new Error('Unexpected table');if(window.failFinance)return {data:null,error:{message:'Fallo simulado'}};return fetch('https://financial.local.test/config',{method:payload?'POST':'GET',headers:{'Content-Type':'application/json'},body:payload?JSON.stringify({payload,calls}):undefined}).then(r=>r.json())},range(from,to){if(window.failSource)return Promise.resolve({data:null,error:{message:'Source unavailable'}});window.reads=window.reads||[];window.reads.push({table,calls,from,to});return new Promise(resolve=>setTimeout(()=>resolve({data:data[table].slice(from,to+1),error:null}),window.sourceDelay || 0))}};return q}};
  `,
};
const built = await build({ stdin: { contents: `import React from 'react';import {createRoot} from 'react-dom/client';import {MemoryRouter} from 'react-router-dom';import {QueryClient,QueryClientProvider} from '@tanstack/react-query';import Page from './src/features/financial/FinancialAnalysisPage';createRoot(document.getElementById('root')).render(<MemoryRouter><QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><Page/></QueryClientProvider></MemoryRouter>);`, resolveDir: process.cwd(), loader: 'tsx' }, bundle: true, write: false, platform: 'browser', format: 'iife', jsx: 'automatic', metafile: true, define: { 'process.env.NODE_ENV': '"production"' }, plugins: [{ name: 'financial-fixture', setup(plugin) {
  plugin.onResolve({ filter: /.*/ }, args => Object.hasOwn(modules, args.path) ? { path: args.path, namespace: 'fixture' } : null);
  plugin.onLoad({ filter: /.*/, namespace: 'fixture' }, args => ({ contents: modules[args.path], loader: 'js', resolveDir: process.cwd() }));
} }], outdir: join(tmpdir(), 'financial-browser-bundle') });
assert.ok(!Object.keys(built.metafile.inputs).some(path => path.startsWith('src/integrations/supabase')), 'Real production client must not be bundled');
// Functional checks run before the production build. Compile actual app styles
// directly, omitting font downloads so this fixture remains fully offline.
const cssSource = readFileSync('src/index.css', 'utf8').replace(/^\s*@import\s+"@fontsource\/[^"\n]+";\s*$/gm, '');
const componentCss = built.outputFiles.filter(file => file.path.endsWith('.css')).map(file => file.text).join('\n');
const { css } = await postcss([tailwindcss('tailwind.config.ts'), autoprefixer]).process(cssSource + '\n' + componentCss, { from: 'src/index.css' });
const html = `<html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>${css}</style></head><body><div id="root"></div><script>${built.outputFiles.find(file => file.path.endsWith('.js')).text.replaceAll('</script','<\\/script')}</script></body></html>`;
// Offline functional checks run before Playwright's download step in delivery.
// Use the runner's installed Chrome when present; never download or skip checks.
const executablePath = process.platform === 'linux' && existsSync('/usr/bin/google-chrome') ? '/usr/bin/google-chrome' : undefined;
const browser = await chromium.launch({ headless: true, executablePath });
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1050 }, hasTouch: true });
  const page = await context.newPage();
  const errors = [], requests = [];
  const openDetails = async text => { const summary=page.locator('summary').filter({hasText:text}); if(!await summary.evaluate(element=>element.parentElement.open)) await summary.click(); };

  page.on('pageerror', error => errors.push(error.message));
  let shared={document:{version:1,rates:[],expenses:[],adjustments:{}},revision:1};
  const handle=async route=>{
    if(route.request().url()==='https://financial.local.test/')return route.fulfill({contentType:'text/html',body:html});
    if(route.request().url()==='https://financial.local.test/config'){
      let data=shared;
      if(route.request().method()==='POST') {const {payload,calls}=route.request().postDataJSON();const expected=calls.find(c=>c[0]==='eq' && c[1]==='revision')?.[2];if(expected!==shared.revision)data=null;else shared=data={document:payload.document,revision:payload.revision};}
      return route.fulfill({contentType:'application/json',body:JSON.stringify({data,error:null})});
    }
    requests.push(route.request().url());return route.abort();
  };
  await page.route('**/*',handle);
  await page.goto('https://financial.local.test/');
  await expect(page.getByRole('heading', { name: 'Análisis financiero', exact: true })).toBeVisible();
  await expect(page.getByText('100,00 €', { exact: true }).first()).toBeVisible();
  await page.getByRole('button',{name:'Cómo se calcula: Comparativa del periodo',exact:true}).click();
  await expect(page.getByText('29,00 €', { exact: true }).first()).toBeVisible();
  await page.getByRole('button',{name:/^Cerrar ayuda:/}).press('Enter');
  await expect(page.getByText(/1 servicios contabilizados/)).toBeVisible();
  await page.locator('summary').filter({hasText:'Servicios fuera del balance:'}).click();
  await expect(page.getByText(/1 con ingreso cero · 1 con precio pendiente/)).toBeVisible();
  await expect(page.getByRole('listitem').filter({hasText:'Jornada Hotel de prueba'})).toBeVisible();
  await expect(page.getByRole('listitem').filter({hasText:'Servicio con precio pendiente'})).toBeVisible();
  await page.locator('summary').filter({hasText:'Servicios fuera del balance:'}).click();
  await expect(page.getByText('Productos', { exact: true }).first()).toBeVisible();
  await expect(page.getByText('3,00 €', { exact: true }).first()).toBeVisible();
  const reads = await page.evaluate(() => window.reads);
  assert.equal(reads.length, 5);
  for (const read of reads) { assert.deepEqual(read.calls.find(call => call[0] === 'eq'), ['eq', read.table==='stock_property_consumption_rules'?'property.sede_id':'sede_id', 's']); assert.deepEqual([read.from,read.to], [0,499]); }
  await openDetails('Fechas personalizadas y filtros');
  await page.getByRole('button',{name:/^Costes pendientes ·/}).click();
  await page.getByRole('region',{name:'Revisar',exact:true}).getByRole('button',{name:/Apartamento Centro/}).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.getByRole('dialog').getByRole('button',{name:'Close',exact:true}).click();
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await page.getByRole('button',{name:/^Fuera del balance ·/}).click();
  await expect(page.getByRole('region',{name:'Revisar',exact:true})).toContainText('Precio pendiente');
  const previousEnd = await page.getByLabel('Hasta', { exact: true }).inputValue();
  const [year, month] = previousEnd.split('-').map(Number);
  const monthEnd = new Date(Date.UTC(year, month, 0)).toISOString().slice(0, 10);
  await page.getByLabel('Mes del análisis', { exact: true }).fill(previousEnd.slice(0,7));
  await expect(page.getByLabel('Desde',{exact:true})).toHaveValue(previousEnd.slice(0,7)+'-01');
  await expect(page.getByLabel('Hasta',{exact:true})).toHaveValue(monthEnd);
  await expect(page.getByText('2.317,00 €', { exact: true }).first()).toBeVisible();
  const graph=page.getByRole('region',{name:'Comparativa del periodo'});
  const costChart=page.getByRole('region',{name:'Distribución de gastos'});
  await expect(costChart.getByRole('listitem').filter({hasText:'Personal'}).last()).toContainText('2.346,00 €');
  await graph.getByRole('button',{name:'Cómo se calcula: Comparativa del periodo',exact:true}).click();
  await expect(page.getByLabel('Desglose de Personal')).toContainText('29,00 €');
  await expect(page.getByLabel('Desglose de Personal')).toContainText('2.317,00 €');
  await page.getByRole('button',{name:/^Cerrar ayuda:/}).press('Enter');
  assert.deepEqual(await graph.locator('ul[aria-label]').first().getByRole('listitem').allTextContents(), ['Ingresos', 'Personal', 'Lavandería', 'Amenities y consumibles', 'Productos']);
  await page.locator('summary').filter({hasText:'Clientes:'}).click();
  await page.getByLabel('Cliente de prueba',{exact:true}).check();
  await expect(costChart.getByRole('listitem').filter({hasText:'Personal'}).last()).toContainText('29,00 €');
  await graph.getByRole('button',{name:'Cómo se calcula: Comparativa del periodo',exact:true}).click();
  await expect(page.getByLabel('Desglose de Personal')).toContainText('0,00 € de dirección y estructura');
  await page.getByRole('button',{name:/^Cerrar ayuda:/}).press('Enter');
  await page.getByLabel('Cliente de prueba',{exact:true}).uncheck();
  await page.locator('summary').filter({hasText:'Clientes:'}).click();
  await expect(costChart.getByRole('listitem').filter({hasText:'Personal'}).last()).toContainText('2.346,00 €');
  await graph.screenshot({path:join(tmpdir(),'limpatex-financial-segmented-personal-demo.png')});
  const detailRegion=page.getByRole('region',{name:'Desglose del gráfico'});
  const revenueBar=graph.getByRole('button',{name:/^Ingresos · Periodo seleccionado/});
  await revenueBar.hover();
  await expect.poll(()=>revenueBar.evaluate(node=>getComputedStyle(node).transform)).not.toBe('none');
  await expect(graph.locator('.recharts-tooltip-wrapper')).toContainText('100,00 €');
  await expect(graph.locator('.recharts-tooltip-wrapper .recharts-tooltip-item')).toHaveCount(1);
  await graph.screenshot({path:join(tmpdir(),'limpatex-financial-hover.png')});
  await revenueBar.click();
  await expect(page.getByRole('heading',{name:'Ingresos · desglose',exact:true})).toBeFocused();
  await expect(detailRegion.getByRole('row').filter({hasText:'Apartamento Centro'})).toContainText('100,00 €');
  assert.equal(await detailRegion.getByRole('row').filter({hasText:'Jornada Hotel de prueba'}).count(),0);
  await page.getByRole('button',{name:'Volver al gráfico',exact:true}).click();
  await expect(revenueBar).toBeFocused();
  await graph.getByRole('button',{name:/^Personal · Periodo seleccionado/}).focus();
  await page.keyboard.press('Enter');
  await expect(page.getByRole('heading',{name:'Gastos · desglose · Personal',exact:true})).toBeVisible();
  await expect(detailRegion).toContainText('2.346,00 €');
  await expect(detailRegion.getByRole('row').filter({hasText:'Salario dirección turismo'})).toContainText('2.317,00 €');
  await expect(detailRegion.getByRole('row').filter({hasText:'Apartamento Centro'})).toContainText('29,00 €');
  await detailRegion.screenshot({path:join(tmpdir(),'limpatex-financial-personal-detail.png')});
  await page.reload();
  await expect(page.getByRole('heading',{name:'Gastos · desglose · Personal',exact:true})).toBeVisible();
  await expect(page.getByLabel('Hasta',{exact:true})).toHaveValue(monthEnd);
  await page.getByRole('button',{name:'Volver al gráfico',exact:true}).click();
  for (const label of ['Lavandería','Amenities y consumibles','Productos']) {
    await graph.getByRole('button',{name:`Ver concepto: ${label}`,exact:true}).click();
    await expect(page.getByRole('heading',{name:`Gastos · desglose · ${label}`,exact:true})).toBeVisible();
    await expect(detailRegion.getByRole('row').filter({hasText:'Apartamento Centro'})).toBeVisible();
    await page.getByRole('button',{name:'Volver al gráfico',exact:true}).click();
  }
  await page.emulateMedia({reducedMotion:'reduce'});
  await revenueBar.hover();
  assert.equal(await revenueBar.evaluate(node=>getComputedStyle(node).transitionDuration),'0s');
  assert.equal(await revenueBar.evaluate(node=>getComputedStyle(node).transform),'none');
  await page.emulateMedia({reducedMotion:'no-preference'});
  await openDetails('Fechas personalizadas y filtros');
  await page.getByLabel('Hasta', { exact: true }).fill(previousEnd);
  if(previousEnd!==monthEnd)await expect(page.getByLabel('Mes del análisis',{exact:true})).toHaveValue('');
  await expect(graph.locator('svg.recharts-surface')).toBeVisible();
  const balanceBars=await graph.locator('.recharts-bar-rectangle .recharts-rectangle').evaluateAll(nodes=>nodes.map(node=>({x:node.getBBox().x,y:node.getBBox().y,height:node.getBBox().height,color:node.getAttribute('fill')})));
  assert.equal(balanceBars.length,5);
  assert.equal(new Set(balanceBars.map(bar=>bar.color)).size,5,'Each income/expense concept has its own color');
  for (const [index,bar] of balanceBars.entries()) {
    if(index>0)assert.ok(balanceBars[index-1].x<bar.x,'Columns must be side by side');
    assert.ok(Math.abs((bar.y+bar.height)-(balanceBars[0].y+balanceBars[0].height))<1,'All income and expense columns share a zero baseline');
  }
  assert.equal(await costChart.getByRole('listitem').count(),4,'Direction is included in the personnel category, not repeated separately');
  assert.equal(await costChart.locator('.recharts-bar').count(),0,'Expense composition must not duplicate the period columns');
  assert.equal(await costChart.locator('.recharts-pie').count(),1);

  await expect(page.getByRole('region',{name:'Distribución de gastos'}).locator('svg.recharts-surface')).toBeVisible();
  await expect(page.getByRole('region',{name:'Origen de los ingresos'})).toContainText('Limpiezas · tarifa base');
  await page.getByRole('button',{name:'Mes anterior',exact:true}).click();
  const earlierMonth=await page.getByLabel('Mes del análisis').inputValue();
  assert.notEqual(earlierMonth,previousEnd.slice(0,7));
  await page.getByRole('button',{name:'Mes siguiente',exact:true}).click();
  await expect(page.getByLabel('Mes del análisis')).toHaveValue(previousEnd.slice(0,7));
  await page.getByLabel('Hasta',{exact:true}).fill(previousEnd);
  await page.getByRole('button',{name:'Margen %',exact:true}).click();
  await expect(page.getByRole('button',{name:'Margen %',exact:true})).toHaveAttribute('aria-pressed','true');
  await page.getByRole('button',{name:/^Ver detalle de Cliente de prueba ·/}).click();
  await expect(page.getByRole('heading',{name:'Servicios · origen de cada importe'})).toBeVisible();
  await page.getByRole('button',{name:'Ver todo · mes actual'}).click();
  await page.getByRole('button',{name:'General',exact:true}).click();
  await expect(page.getByRole('region',{name:'Evolución mensual'}).locator('.recharts-line')).toHaveCount(3);
  await expect(page.getByRole('region',{name:'Tabla de resultados por cliente'}).getByRole('table')).toBeVisible();
  await expect(page.getByRole('region',{name:'Evolución mensual'}).locator('svg.recharts-surface').first()).toBeVisible();
  await openDetails('Datos de la evolución · 12 meses');
  await expect(page.getByRole('region',{name:'Evolución mensual'}).getByRole('row')).toHaveCount(13);
  const monthFromLines=page.getByRole('region',{name:'Evolución mensual'}).locator('tbody tr').nth(10).getByRole('button');
  await monthFromLines.press('Enter');
  await expect(page.getByRole('heading',{name:'Ingresos · desglose',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Volver al gráfico',exact:true}).click();
  await expect(monthFromLines).toBeFocused();
  await expect(page.getByRole('region',{name:'Evolución mensual'}).locator('.recharts-line')).toHaveCount(3);
  await page.getByRole('region',{name:'Evolución mensual'}).getByRole('button',{name:'Columnas',exact:true}).click();
  const trend=page.getByRole('region',{name:'Evolución mensual'});
  await expect(trend.locator('.recharts-bar')).toHaveCount(5);
  await expect(trend.locator('.recharts-line')).toHaveCount(0);
  const previousPeriod=await trend.getByRole('row').nth(5).locator('th').textContent();
  await trend.locator('.recharts-bar').nth(1).getByRole('button').nth(4).click();
  await expect(page.getByRole('heading',{name:'Gastos · desglose · Personal',exact:true})).toBeVisible();
  await expect(detailRegion).toContainText(previousPeriod);
  await expect(page.getByLabel('Hasta',{exact:true})).not.toHaveValue(previousEnd);
  await page.getByRole('button',{name:'Volver al gráfico',exact:true}).click();
  await expect(page.getByLabel('Hasta',{exact:true})).toHaveValue(previousEnd);
  await expect(page.getByRole('button',{name:'Ocultar evolución',exact:true})).toBeVisible();
  await expect(trend.locator('.recharts-bar').nth(1).getByRole('button').nth(4)).toBeFocused();
  await trend.getByRole('button',{name:'Tipos de gasto',exact:true}).click();
  await expect(trend.locator('.recharts-bar')).toHaveCount(4);
  await expect(trend.getByRole('button',{name:'Tipos de gasto',exact:true})).toHaveAttribute('aria-pressed','true');
  await trend.getByRole('button',{name:'Origen de ingresos',exact:true}).click();
  await expect(trend.locator('.recharts-bar')).toHaveCount(1);
  await trend.getByRole('button',{name:'Balance',exact:true}).click();

  await page.getByLabel(/Comparar del día 1 al/).uncheck();
  await trend.getByRole('button',{name:'Cómo se calcula: Evolución mensual',exact:true}).click();
  await expect(page.getByText(/Comparación de meses completos/)).toBeVisible();
  await page.getByRole('button',{name:/^Cerrar ayuda:/}).press('Enter');
  await page.evaluate(()=>{window.failSource=true});
  await page.getByRole('button',{name:'Actualizar datos',exact:true}).click();
  await expect(page.getByText('No se pudieron cargar los datos. No se muestran totales parciales.')).toBeVisible();
  await expect(page.getByRole('region',{name:'Indicadores financieros'})).not.toBeVisible();
  await expect(page.getByRole('region',{name:'Evolución mensual'})).not.toBeVisible();
  await page.evaluate(()=>{window.failSource=false});
  await page.getByRole('button',{name:'Reintentar',exact:true}).click();
  await expect(page.getByRole('region',{name:'Evolución mensual'}).locator('svg.recharts-surface')).toBeVisible();
  await page.getByRole('region',{name:'Evolución mensual'}).screenshot({path:join(tmpdir(),'limpatex-financial-trend.png')});
  await page.getByRole('button',{name:'Ocultar evolución',exact:true}).click();
  await expect(trend.locator('svg.recharts-surface')).toHaveCount(0);
  await expect(trend.locator('.recharts-cartesian-axis-tick')).toHaveCount(0);
  await page.getByRole('button', { name: 'Tarifas', exact: true }).click();
  await expect(page.getByText('0,247 € / prenda')).toBeVisible();
  await expect(page.getByText('2.317,00 € / mes · coste de empresa')).toBeVisible();
  await page.getByLabel('Concepto', { exact: true }).selectOption('tourismSalary');
  await page.getByLabel('Coste de empresa mensual').fill('0');
  await page.getByLabel('Aplicar desde').fill('2000-01-01');
  await page.getByRole('button', { name: 'Guardar tarifa' }).click();
  await page.getByLabel('Concepto', { exact: true }).selectOption('kitchenKit');
  await page.getByLabel('Precio unitario sin IVA').fill('1,17');
  await page.getByRole('button', { name: 'Guardar tarifa' }).click();
  await expect(page.getByRole('status')).toContainText('Borrador actualizado');
  await page.getByLabel('Concepto', { exact: true }).selectOption('products');
  await page.getByLabel('Porcentaje sobre limpieza').fill('4,2');
  await page.getByRole('button', { name: 'Guardar tarifa' }).click();
  await page.getByRole('button', { name: 'General', exact: true }).click();
  await expect(page.getByText('4,20 €', { exact: true }).first()).toBeVisible();
  await page.getByRole('button', { name: 'Otros gastos', exact: true }).click();
  await page.getByLabel('Concepto del gasto').fill('Alquiler de prueba');
  await page.getByLabel('Importe sin IVA', { exact: true }).fill('50');
  await page.getByRole('button', { name: 'Añadir al análisis' }).click();
  await expect(page.getByText('Alquiler de prueba', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'General', exact: true }).click();
  await expect(page.getByText('Gastos generales incluidos:')).toContainText('50,00 €');
  await expect(graph.locator('.financial-column[role=button]')).toHaveCount(6);
  await expect(costChart.getByRole('listitem').filter({hasText:'Otros gastos'}).last()).toContainText('50,00 €');
  await page.locator('summary').filter({ hasText: 'Trabajadores:' }).click();
  await page.getByLabel('Ana', { exact: true }).check();
  await page.locator('summary').filter({ hasText: 'Trabajadores:' }).click();
  await expect(page.getByText('Gastos generales incluidos:')).toContainText('0,00 €');
  await expect(graph.locator('.financial-column[role=button]')).toHaveCount(5);
  await graph.getByRole('button',{name:'Cómo se calcula: Comparativa del periodo',exact:true}).click();
  await expect(page.getByLabel('Desglose de Personal')).toContainText('0,00 € de dirección y estructura');
  await page.getByRole('button',{name:/^Cerrar ayuda:/}).press('Enter');
  await expect(page.getByText('100,00 €', { exact: true }).first()).toBeVisible();
  await expect(page.getByText('29,00 €', { exact: true }).first()).toBeVisible();
  await page.getByRole('button', { name: 'Ver todo · mes actual' }).click();
  await page.getByRole('button', { name: 'Servicios', exact: true }).click();
  await page.getByRole('button', { name: 'Revisar costes' }).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByLabel(/Ana/).fill('1,5');
  for (const input of await dialog.locator('input[inputmode="numeric"]').all()) if (!(await input.inputValue())) await input.fill('0');
  await dialog.getByLabel('He revisado todas las cantidades de este servicio').check();
  await dialog.getByRole('button', { name: 'Guardar ajustes del análisis' }).click();
  await expect(dialog).not.toBeVisible();
  await expect(page.getByText('36,25 €', { exact: true })).toBeVisible();
  await page.getByRole('button',{name:'Guardar cambios',exact:true}).click();
  await expect(page.getByRole('status')).toContainText('guardados y compartidos');
  await page.reload();
  await expect(page.getByText('36,25 €', { exact: true }).first()).toBeVisible();
  await expect(page.getByRole('heading',{name:'Servicios · origen de cada importe',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'General',exact:true}).click();
  await expect(page.getByText('Gastos generales incluidos:')).toContainText('50,00 €');
  await page.getByRole('button',{name:'Otros ingresos',exact:true}).click();
  await page.getByLabel('Concepto del ingreso').fill('Lavandería externa de prueba');
  await page.getByLabel('Ingreso sin IVA',{exact:true}).fill('300');
  await page.getByLabel('Coste externo sin IVA').fill('200');
  await page.getByLabel('Categoría del coste').selectOption('laundry');
  await page.getByRole('button',{name:'Añadir ingreso',exact:true}).click();
  await expect(page.getByRole('row').filter({hasText:'Lavandería externa de prueba'})).toContainText('100,00 €');
  await page.getByLabel('Concepto del ingreso').fill('Recepción de prueba');
  await page.getByLabel('Tipo de ingreso').selectOption('monthly');
  await page.getByLabel('Ingreso sin IVA',{exact:true}).fill('1329,60');
  await page.getByLabel('Horas de personal por semana').fill('16');
  await page.getByLabel('Cliente del ingreso').selectOption('c2');
  await page.getByRole('button',{name:'Añadir ingreso',exact:true}).click();
  await openDetails('Fechas personalizadas y filtros');
  await page.getByLabel('Hasta',{exact:true}).fill(monthEnd);
  await expect(page.getByRole('row').filter({hasText:'Recepción de prueba'})).toContainText('1.008,04 €');
  await page.getByLabel('Concepto del ingreso').fill('Virtual por limpieza de prueba');
  await page.getByLabel('Tipo de ingreso').selectOption('perCleaning');
  await page.getByLabel('Ingreso sin IVA',{exact:true}).fill('2,75');
  await page.getByLabel('Cliente del ingreso').selectOption('c');
  await page.getByRole('button',{name:'Añadir ingreso',exact:true}).click();
  await page.getByRole('button',{name:'General',exact:true}).click();
  await expect(page.getByRole('region',{name:'Tabla de resultados por cliente'}).getByRole('table')).toBeVisible();
  await expect(page.getByRole('row').filter({hasText:'Cliente de prueba'}).first()).toContainText('102,75 €');
  await expect(page.getByRole('region',{name:'Origen de los ingresos'})).toContainText('Suplementos por limpieza');
  const incomeChart=page.getByRole('region',{name:'Origen de los ingresos'});
  await expect(incomeChart.locator('.financial-column[role=button]')).toHaveCount(4);
  await incomeChart.getByRole('button',{name:'Ver concepto: Recepción de prueba',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Ingresos · desglose · Recepción de prueba',exact:true})).toBeVisible();
  await expect(detailRegion.getByRole('row').filter({hasText:'Recepción de prueba'})).toContainText('1.329,60 €');
  await expect(detailRegion.locator('tbody tr')).toHaveCount(1);
  await page.getByRole('button',{name:'Volver al gráfico',exact:true}).click();
  await graph.getByRole('button',{name:/^Ingresos · Periodo seleccionado/}).click();
  await expect(detailRegion.locator('tbody tr')).toHaveCount(3);
  await expect(detailRegion.getByRole('row').filter({hasText:'Apartamento Centro'})).toContainText('102,75 €');
  await expect(detailRegion.getByRole('row').filter({hasText:'Lavandería externa de prueba'})).toContainText('300,00 €');
  await expect(detailRegion).toContainText('1.732,35 €');
  await page.getByRole('button',{name:'Volver al gráfico',exact:true}).click();
  if(await page.getByRole('button',{name:'Ver evolución mensual',exact:true}).isVisible()) await page.getByRole('button',{name:'Ver evolución mensual',exact:true}).click();
  await page.getByRole('region',{name:'Evolución mensual'}).getByRole('button',{name:'Columnas',exact:true}).click();
  await page.getByRole('region',{name:'Evolución mensual'}).getByRole('button',{name:'Origen de ingresos',exact:true}).click();
  await expect(page.getByRole('region',{name:'Evolución mensual'}).locator('.recharts-bar')).toHaveCount(4);
  await page.getByRole('button',{name:'Ocultar evolución',exact:true}).click();

  await page.getByRole('button',{name:/^Ver detalle de Cliente sin servicios ·/}).click();
  await expect(page.getByRole('heading',{name:'Ingresos externos de esta selección'})).toBeVisible();
  await expect(page.getByRole('row').filter({hasText:'Recepción de prueba'})).toContainText('1.329,60 €');
  await expect(page.getByText('No hay servicios contabilizables con estos filtros.')).toBeVisible();
  await page.getByRole('button',{name:'Ver todo · mes actual'}).click();
  await page.getByLabel('Hasta',{exact:true}).fill(monthEnd);
  await page.getByRole('button',{name:'Por cliente',exact:true}).click();
  await expect(page.getByRole('row').filter({hasText:'Cliente de prueba'}).first()).toContainText('4,20 €');
  await expect(page.getByRole('row').filter({hasText:'Cliente sin servicios'})).toContainText('1.329,60 €');
  await page.getByRole('button',{name:'Otros ingresos',exact:true}).click();
  await page.locator('div.rounded-lg').filter({hasText:'Recepción de prueba'}).getByRole('button',{name:'Editar ingreso'}).click();
  await page.getByLabel('Cambiar importes solo este mes · opcional').fill(previousEnd.slice(0,7));
  await page.getByLabel('Ingreso sin IVA',{exact:true}).fill('1500');
  await page.getByRole('button',{name:'Actualizar ingreso',exact:true}).click();
  await expect(page.getByRole('row').filter({hasText:'Recepción de prueba'})).toContainText('1.500,00 €');
  await page.evaluate(()=>{window.failFinance=true});
  await page.getByRole('button',{name:'Guardar cambios',exact:true}).click();
  await expect(page.getByRole('status')).toContainText('Tu borrador se conserva');
  assert.equal(shared.document.incomes,undefined,'Failed save must not persist draft');
  await page.evaluate(()=>{window.failFinance=false});
  await page.getByRole('button',{name:'Guardar cambios',exact:true}).click();
  await expect(page.getByRole('status')).toContainText('guardados y compartidos');
  const second=await browser.newPage();await second.route('**/*',handle);await second.goto('https://financial.local.test/');
  await second.getByRole('button',{name:'Otros ingresos',exact:true}).click();
  await expect(second.getByText('Lavandería externa de prueba',{exact:true})).toBeVisible();
  assert.equal(await second.evaluate(()=>localStorage.length),0,'Shared settings work without browser-local configuration');
  await second.close();
  shared={...shared,revision:shared.revision+1};
  await page.getByLabel('Concepto del ingreso').fill('Borrador en conflicto');
  await page.getByRole('button',{name:'Añadir ingreso',exact:true}).click();
  await page.getByRole('button',{name:'Guardar cambios',exact:true}).click();
  await expect(page.getByRole('status')).toContainText('Otra persona ha cambiado');
  assert.ok(!shared.document.incomes.some(i=>i.label==='Borrador en conflicto'));
  await openDetails(/^(Configuración compartida de esta sede|Cambios sin guardar)$/);
  await page.getByRole('button',{name:'Descartar y recargar',exact:true}).click();
  await expect(page.locator('summary').filter({hasText:/^Configuración compartida de esta sede$/})).toBeVisible();
  await expect(page.getByText('Ingresos totales',{exact:true})).toBeVisible();
  await page.evaluate(()=>{window.failFinance=true});
  await openDetails(/^(Configuración compartida de esta sede|Cambios sin guardar)$/);
  await page.getByRole('button',{name:'Descartar y recargar',exact:true}).click();
  await expect(page.getByText('Ingresos totales',{exact:true})).not.toBeVisible();
  await expect(page.getByText(/Configuración sin cargar/)).toBeVisible();
  await page.evaluate(()=>{window.failFinance=false});
  await openDetails(/^(Configuración compartida de esta sede|Cambios sin guardar)$/);
  await page.getByRole('button',{name:'Descartar y recargar',exact:true}).click();
  await expect(page.getByText('Ingresos totales',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Servicios',exact:true}).click();
  await page.getByRole('button',{name:'Margen inferior al 10%',exact:true}).click();
  await expect(page.getByText('No hay servicios contabilizables con estos filtros.')).toBeVisible();
  await page.getByRole('button',{name:'Todos los servicios',exact:true}).click();
  await page.getByRole('button',{name:'Revisar costes',exact:true}).click();
  await page.getByRole('dialog').getByLabel(/^Paño de cocina/).fill('1');
  await page.getByRole('dialog').getByRole('button',{name:'Guardar ajustes del análisis',exact:true}).click();
  await page.getByRole('button',{name:'Tarifas',exact:true}).click();
  await page.getByLabel('Cliente de la regla').selectOption('c');
  await page.getByLabel('Propiedad de la regla').selectOption('p');
  await page.getByLabel(/^Cobro de paño de cocina/).selectOption('yes');
  await page.getByRole('button',{name:'Aplicar regla al borrador',exact:true}).click();
  await page.getByRole('button',{name:'Servicios',exact:true}).click();
  await expect(page.getByRole('row').filter({hasText:'Apartamento Centro'})).toContainText('103,00 €');
  await page.getByRole('button',{name:'Revisar costes',exact:true}).click();
  await expect(page.getByRole('dialog')).toContainText('paño de cocina: 0,25 €');
  await expect(page.getByRole('dialog')).toContainText('otros suplementos: 2,75 €');
  await page.getByRole('dialog').getByRole('button',{name:'Close',exact:true}).click();
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await page.getByRole('button',{name:'Guardar cambios',exact:true}).click();
  await expect(page.getByRole('status')).toContainText('guardados y compartidos');
  assert.equal(shared.document.policies.find(p=>p.propertyId==='p').kitchenClothIncome,true);
  await page.getByRole('button',{name:'Otros ingresos',exact:true}).click();
  const incomeCount=shared.document.incomes.length;
  await page.getByLabel('Concepto del ingreso').fill('Ingreso puntual con miles de prueba');
  await page.getByLabel('Ingreso sin IVA',{exact:true}).fill('4.05,45');
  await page.getByLabel('Fecha del ingreso').fill(monthEnd);
  await page.getByLabel('Coste externo sin IVA').fill('3418,43');
  await page.getByLabel('Categoría del coste').selectOption('personal');
  await page.getByLabel('Cliente del ingreso').selectOption('c');
  await page.getByLabel('Trabajador del ingreso').selectOption('w1');
  await page.getByRole('button',{name:'Añadir ingreso',exact:true}).click();
  await expect(page.getByRole('alert')).toContainText('Introduce un ingreso válido');
  assert.equal(shared.document.incomes.length,incomeCount);
  await page.getByLabel('Ingreso sin IVA',{exact:true}).fill('4.058,45');
  await page.getByLabel('Coste externo sin IVA').fill('3418,430');
  await page.getByRole('button',{name:'Añadir ingreso',exact:true}).click();
  await expect(page.getByRole('alert')).toContainText('Introduce un coste válido');
  await page.getByLabel('Coste externo sin IVA').fill('3.418,43');
  await page.getByRole('button',{name:'Añadir ingreso',exact:true}).click();
  const groupedRow=page.getByRole('row').filter({hasText:'Ingreso puntual con miles de prueba'});
  await expect(groupedRow).toContainText('4.058,45 €');
  await expect(groupedRow).toContainText('3.418,43 €');
  await expect(groupedRow).toContainText('640,02 €');
  assert.equal(shared.document.incomes.length,incomeCount,'Adding an income remains a draft until Save');
  await page.getByRole('button',{name:'Guardar cambios',exact:true}).click();
  await expect(page.getByRole('status')).toContainText('guardados y compartidos');
  const groupedEntry=shared.document.incomes.find(i=>i.label==='Ingreso puntual con miles de prueba');
  assert.deepEqual([groupedEntry.income,groupedEntry.cost,groupedEntry.mode,groupedEntry.start,groupedEntry.clientId,groupedEntry.workerId,groupedEntry.costCategory],[405845,341843,'manual',monthEnd,'c','w1','personal']);
  assert.equal(shared.document.incomes.length,incomeCount+1);
  await page.reload();
  await expect(groupedRow).toContainText('640,02 €');
  await page.getByLabel('Concepto del ingreso').fill('Formulario que debe mantenerse');
  const beforeFocus=await page.evaluate(()=>window.reads.length);
  const otherTab=await page.context().newPage();
  await otherTab.goto('about:blank');
  await otherTab.bringToFront();
  await page.bringToFront();
  await page.evaluate(async()=>{
    // Exercise the event React Query subscribes to deterministically as well.
    let state='hidden';Object.defineProperty(document,'visibilityState',{configurable:true,get:()=>state});
    document.dispatchEvent(new Event('visibilitychange'));state='visible';document.dispatchEvent(new Event('visibilitychange'));
    await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));
  });
  await otherTab.close();
  assert.equal(await page.evaluate(()=>window.reads.length),beforeFocus,'Returning to browser tab must not refetch');
  await expect(page.getByLabel('Concepto del ingreso')).toHaveValue('Formulario que debe mantenerse');
  await page.evaluate(()=>{window.sourceDelay=250});
  await page.getByRole('button',{name:'Actualizar datos',exact:true}).click();
  await expect(page.getByRole('button',{name:'Actualizando datos…',exact:true})).toBeVisible();
  await expect(page.getByLabel('Concepto del ingreso')).toHaveValue('Formulario que debe mantenerse');
  await expect(page.getByRole('button',{name:'Actualizar datos',exact:true})).toBeEnabled();
  assert.equal(await page.evaluate(()=>window.reads.length),beforeFocus+5,'Explicit update must read every source');
  await expect(page.getByLabel('Concepto del ingreso')).toHaveValue('Formulario que debe mantenerse');
  const retainedEnd=await page.getByLabel('Hasta',{exact:true}).inputValue();
  await page.reload();
  await expect(page.getByLabel('Concepto del ingreso')).toBeVisible();
  await expect(page.getByLabel('Hasta',{exact:true})).toHaveValue(retainedEnd);
  await page.getByRole('button',{name:'General',exact:true}).click();
  const monthlyStart=await page.getByLabel('Desde',{exact:true}).inputValue();
  const monthlyEnd=await page.getByLabel('Hasta',{exact:true}).inputValue();
  const annualYear=monthlyEnd.slice(0,4);
  await openDetails('Fechas personalizadas y filtros');
  for(const [filter,label] of [['Clientes:','Cliente de prueba'],['Propiedades:','Apartamento Centro'],['Trabajadores:','Ana']]){
    await page.locator('summary').filter({hasText:filter}).click();
    await page.getByLabel(label,{exact:true}).check();
    await page.locator('summary').filter({hasText:filter}).click();
  }
  const sharedRevision=shared.revision;
  await page.getByRole('button',{name:'Vista Anual',exact:true}).click();
  await expect(page.getByLabel('Año del análisis',{exact:true})).toHaveValue(annualYear);
  await expect(page.getByLabel('Desde',{exact:true})).toHaveValue(annualYear+'-01-01');
  await expect(page.getByLabel('Hasta',{exact:true})).toHaveValue(annualYear+'-12-31');
  const annualRegion=page.getByRole('region',{name:'Resumen anual por meses',exact:true});
  await expect(annualRegion.getByRole('heading',{name:'Vista anual · '+annualYear,exact:true})).toBeVisible();
  await expect(annualRegion.locator('.recharts-bar')).toHaveCount(5);
  await expect(annualRegion.locator('ul[aria-label^="Leyenda"]').getByRole('listitem')).toHaveCount(5);
  await expect(annualRegion.locator('.recharts-line')).toHaveCount(3);
  const annualRead=(await page.evaluate(()=>window.reads)).findLast(read=>read.table==='tasks');
  assert.deepEqual(annualRead.calls.find(call=>call[0]==='gte'),['gte','date',String(Number(annualYear)-1)+'-01-01']);
  assert.deepEqual(annualRead.calls.find(call=>call[0]==='lte'),['lte','date',annualYear+'-12-31']);
  for(const [filter,label] of [['Clientes:','Cliente de prueba'],['Propiedades:','Apartamento Centro'],['Trabajadores:','Ana']]){
    await page.locator('summary').filter({hasText:filter}).click();
    await expect(page.getByLabel(label,{exact:true})).toBeChecked();
    await page.locator('summary').filter({hasText:filter}).click();
  }
  // The external income has no property; include it only after removing that filter.
  await page.locator('summary').filter({hasText:'Propiedades:'}).click();
  await page.getByLabel('Apartamento Centro',{exact:true}).uncheck();
  await page.locator('summary').filter({hasText:'Propiedades:'}).click();
  await annualRegion.locator('summary').filter({hasText:'Desglose de los doce meses'}).click();
  await expect(annualRegion.locator('tbody tr')).toHaveCount(12);
  const annualRevenue=annualRegion.locator(`[data-financial-concept="revenue"][data-period-start="${monthlyEnd.slice(0,7)}-01"]`).getByRole('button');
  await annualRevenue.click();
  await expect(page.getByRole('heading',{name:'Ingresos · desglose',exact:true})).toBeVisible();
  await expect(page.getByLabel('Desde',{exact:true})).toHaveValue(monthlyEnd.slice(0,7)+'-01');
  await expect(page.getByLabel('Hasta',{exact:true})).toHaveValue(monthEnd);
  await expect(detailRegion.getByRole('row').filter({hasText:'Ingreso puntual con miles de prueba'})).toContainText('4.058,45 €');
  await page.getByRole('button',{name:'Volver al gráfico',exact:true}).click();
  await expect(page.getByLabel('Año del análisis',{exact:true})).toHaveValue(annualYear);
  await expect(annualRevenue).toBeFocused();
  await annualRegion.getByRole('button',{name:'Tipos de gasto',exact:true}).click();
  await expect(annualRegion.locator('.recharts-bar')).toHaveCount(4);
  await annualRegion.getByRole('button',{name:'Ver concepto: Personal',exact:true}).click();
  await expect(page.getByLabel('Desde',{exact:true})).toHaveValue(annualYear+'-01-01');
  await expect(page.getByRole('heading',{name:'Gastos · desglose · Personal',exact:true})).toBeVisible();
  await expect(detailRegion.getByRole('row').filter({hasText:'Ingreso puntual con miles de prueba'})).toContainText('3.418,43 €');
  await page.getByRole('button',{name:'Volver al gráfico',exact:true}).click();
  await expect(annualRegion.getByRole('button',{name:'Tipos de gasto',exact:true})).toHaveAttribute('aria-pressed','true');
  await annualRegion.getByRole('button',{name:'Origen de ingresos',exact:true}).click();
  const annualExternal=annualRegion.locator(`[data-financial-concept="external:Ingreso puntual con miles de prueba"][data-period-start="${monthlyEnd.slice(0,7)}-01"]`).getByRole('button');
  await annualExternal.press('Enter');
  await expect(page.getByRole('heading',{name:'Ingresos · desglose · Ingreso puntual con miles de prueba',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Volver al gráfico',exact:true}).click();
  await expect(annualExternal).toBeFocused();
  await expect(annualRegion.getByRole('button',{name:'Origen de ingresos',exact:true})).toHaveAttribute('aria-pressed','true');
  await page.reload();
  await expect(page.getByLabel('Año del análisis',{exact:true})).toHaveValue(annualYear);
  await expect(annualRegion.getByRole('button',{name:'Origen de ingresos',exact:true})).toHaveAttribute('aria-pressed','true');
  for(const [filter,label,checked] of [['Clientes:','Cliente de prueba',true],['Propiedades:','Apartamento Centro',false],['Trabajadores:','Ana',true]]){
    await openDetails('Fechas personalizadas y filtros');
    await page.locator('summary').filter({hasText:filter}).click();
    await expect(page.getByLabel(label,{exact:true})).toBeChecked({checked});
    await page.locator('summary').filter({hasText:filter}).click();
  }
  await page.getByLabel('Año del análisis',{exact:true}).selectOption('2024');
  await expect(page.getByRole('button',{name:'Actualizar datos',exact:true})).toBeEnabled();
  await annualRegion.locator('summary').filter({hasText:'Desglose de los doce meses'}).click();
  await annualRegion.locator('tbody tr').nth(1).getByRole('button').click();
  await expect(page.getByLabel('Desde',{exact:true})).toHaveValue('2024-02-01');
  await expect(page.getByLabel('Hasta',{exact:true})).toHaveValue('2024-02-29');
  await page.getByRole('button',{name:'Volver al gráfico',exact:true}).click();
  await expect(annualRegion).toBeFocused();
  await page.getByRole('button',{name:'Año anterior',exact:true}).click();
  await expect(page.getByLabel('Año del análisis',{exact:true})).toHaveValue('2023');
  await page.getByRole('button',{name:'Año siguiente',exact:true}).click();
  await expect(page.getByLabel('Año del análisis',{exact:true})).toHaveValue('2024');
  await page.getByLabel('Año del análisis',{exact:true}).selectOption(annualYear);
  await page.getByRole('button',{name:'Vista Mensual',exact:true}).click();
  await expect(page.getByLabel('Desde',{exact:true})).toHaveValue(monthlyStart);
  await expect(page.getByLabel('Hasta',{exact:true})).toHaveValue(monthlyEnd);
  assert.equal(shared.revision,sharedRevision,'Annual navigation must not save business settings');
  await page.getByRole('button',{name:'Ver todo · mes actual',exact:true}).click();
  await page.getByLabel('Mes del análisis',{exact:true}).fill(monthlyEnd.slice(0,7));
  await page.getByRole('button',{name:'Vista Anual',exact:true}).click();
  await annualRegion.getByRole('button',{name:'Ingresos y gastos',exact:true}).click();
  await expect(annualRegion.locator('.recharts-bar')).toHaveCount(6);
  await page.screenshot({path:join(tmpdir(),'limpatex-financial-annual-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await annualRegion.locator('summary').filter({hasText:'Desglose de los doce meses'}).click();
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'Annual chart and monthly table scroll within mobile viewport');
  await page.screenshot({path:join(tmpdir(),'limpatex-financial-annual-mobile.png'),fullPage:true});
  await annualRegion.getByRole('button',{name:'Ver concepto: Personal',exact:true}).tap();
  await expect(page.getByRole('heading',{name:'Gastos · desglose · Personal',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Volver al gráfico',exact:true}).click();
  await expect(page.getByLabel('Año del análisis',{exact:true})).toHaveValue(annualYear);
  await page.getByRole('button',{name:'Vista Mensual',exact:true}).click();
  await page.setViewportSize({width:1440,height:1050});
  await page.screenshot({ path: join(tmpdir(), 'limpatex-financial-desktop.png'), fullPage: true });
  await page.getByRole('region',{name:'Comparativa del periodo'}).screenshot({path:join(tmpdir(),'limpatex-financial-grouped-demo.png')});
  await page.setViewportSize({ width: 390, height: 844 });
  await openDetails('Fechas personalizadas y filtros');
  await page.locator('summary').filter({hasText:'Clientes:'}).click();
  await expect(page.getByLabel('Cliente de prueba',{exact:true})).toBeVisible();
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'Open mobile filters fit the viewport');
  await page.locator('summary').filter({hasText:'Clientes:'}).click();
  await page.locator('summary').filter({hasText:'Fechas personalizadas y filtros'}).click();
  await page.screenshot({path:join(tmpdir(),'limpatex-financial-mobile-populated.png'),fullPage:true});
  await graph.getByRole('button',{name:/^Ingresos · Periodo seleccionado/}).tap();
  await expect(page.getByRole('heading',{name:'Ingresos · desglose',exact:true})).toBeVisible();
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'Detail table scrolls inside mobile viewport');
  await page.getByRole('button',{name:'Volver al gráfico',exact:true}).click();
  await page.getByLabel('Mes del análisis',{exact:true}).fill('2024-02');
  await expect(page.getByLabel('Desde',{exact:true})).toHaveValue('2024-02-01');
  await expect(page.getByLabel('Hasta',{exact:true})).toHaveValue('2024-02-29');
  await expect(page.getByRole('button',{name:'Actualizar datos',exact:true})).toBeEnabled();
  await page.reload();
  await expect(page.getByLabel('Mes del análisis',{exact:true})).toHaveValue('2024-02');
  await expect(page.getByLabel('Hasta',{exact:true})).toHaveValue('2024-02-29');
  await expect(page.getByRole('heading', { name: 'Análisis financiero', exact: true })).toBeVisible();
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'No page-level horizontal overflow on mobile');
  await page.screenshot({ path: join(tmpdir(), 'limpatex-financial-mobile.png'), fullPage: true });
  await page.evaluate(()=>{window.failSource=true});
  await page.getByRole('button',{name:'Actualizar datos',exact:true}).click();
  await expect(page.getByText('No se pudieron cargar los datos. No se muestran totales parciales.')).toBeVisible();
  await expect(page.getByText('Ingresos totales',{exact:true})).not.toBeVisible();
  await page.evaluate(()=>{window.failSource=false});
  await page.getByRole('button',{name:'Reintentar',exact:true}).click();
  await expect(page.getByText('Ingresos totales',{exact:true})).toBeVisible();
  assert.deepEqual(errors, []); assert.deepEqual(requests.filter(url => !url.endsWith('.woff') && !url.endsWith('.woff2')), []);
  console.log('financial-browser: real page/reader, offline fixtures, filters, annual/monthly views, twelve months, click/keyboard detail and return, persistence, desktop/mobile and existing regressions passed');
} finally { await browser.close(); }
