import { build } from 'esbuild';
import { chromium, expect } from '@playwright/test';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
const outputDir = 'docs/previsor/incidencias-n01-n03-capturas';
mkdirSync(outputDir, { recursive: true });
const built = await build({ entryPoints: ['scripts/forecastUiAcceptance.entry.tsx'], bundle: true, outdir: 'test-ui', write: false, platform: 'browser', format: 'iife', jsx: 'automatic', metafile: true, define: { 'process.env.NODE_ENV': '"production"' } });
expect(Object.keys(built.metafile.inputs).some(p => p.includes('integrations/supabase'))).toBe(false);
const js = built.outputFiles.find(f => f.path.endsWith('.js')).text;
const css = built.outputFiles.find(f => f.path.endsWith('.css')).text;
const html = `<!doctype html><html lang="es"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:0}*{box-sizing:border-box}${css}</style><div id="root"></div><script>${js.replaceAll('</script', '<\\/script')}</script></html>`;
const browser = await chromium.launch({ headless: true });
const errors = [], requests = [], checks = [];
const origin = 'http://forecast.test';
const query = 'month=2026-09&horizon=3&week=2026-10-19';
const record = text => { checks.push(text); console.log('PASS', text); };
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  page.on('pageerror', error => errors.push(error.message));
  await page.route('**/*', route => { const r = route.request(); if (r.url().startsWith(origin) && r.isNavigationRequest()) return route.fulfill({ contentType: 'text/html', body: html }); requests.push(r.url()); return route.abort(); });
  const go = async (screen, extra = '') => { const params = new URLSearchParams(query); for (const [key, value] of new URLSearchParams(extra)) params.set(key, value); await page.goto(`${origin}/staffing-forecast/screens/${screen}?${params}`); await expect(page.locator('h1')).toBeVisible(); };
  if (!process.env.FORECAST_REVISION_ONLY) {
  await go('home');
  await expect(page.getByRole('heading', { name: 'Pendiente de revisar' })).toBeVisible();
  await expect(page.getByText('Revisar datos que impiden cerrar la previsión')).toBeVisible();
  record('A01/A02: Inicio prioriza datos y separa objetivos pendientes de evaluación');
  await go('forecast', '&view=week');
  await expect(page.locator('.sf-context')).toContainText('19 de octubre de 2026');
  const countLink = page.locator('.sf-panel-actions a').filter({ hasText: /tareas? sin asignar/ }).first();
  const text = await countLink.innerText(), count = Number(text.match(/\d+/)[0]);
  await countLink.click();
  await expect(page.getByLabel('Vista de cobertura')).toHaveValue('week');
  const displayed = await page.locator('.sf-context-line strong').innerText();
  expect(displayed).toContain(`${count} tareas`);
  record('A03/A04: contador semanal y destino coinciden sin cambiar al mes');
  await go('shifts', '&view=day&date=2026-10-19&task=window-conflict&detail=candidates');
  const dialog = page.getByRole('dialog');
  await expect(dialog.getByText('33 min', { exact: true })).toBeVisible();
  await expect(dialog.getByText('El horario registrado queda fuera de la ventana del cliente.')).toBeVisible();
  const calendar = dialog.getByRole('link', { name: /Abrir en calendario diario/ });
  expect(await calendar.getAttribute('href')).toBe('/calendar?date=2026-10-19&task=window-conflict');
  await expect(calendar).toHaveAttribute('target', '_blank');
  const profile = dialog.getByRole('link', { name: 'Ver perfil' }).first();
  await expect(profile).toBeVisible();
  if (await profile.count()) {
    await profile.click();
    await expect(page.getByLabel('Mes del balance')).toHaveValue('2026-10');
    await page.getByRole('button', { name: 'Volver a candidatos' }).click();
    await expect(page.getByRole('heading', { name: 'Candidatos para Ventana contradictoria' })).toBeVisible();
  }
  record('A03/A08/A13/A15: tarea, ventana, propuesta, perfil de octubre y enlace operativo');
  await go('team', '&focusMonth=2026-10');
  await expect(page.locator('.sf-team-list')).not.toContainText('Persona Excluida');
  await page.getByLabel('Mostrar').selectOption('unknown');
  await expect(page.locator('.sf-team-list')).toContainText('Jornada Por Revisar');
  await page.getByLabel('Buscar persona').fill('ninguna-persona');
  await expect(page.getByText('No hay personas con estos filtros.')).toBeVisible();
  await page.getByRole('button', { name: 'Limpiar filtros' }).first().click();
  const opener = page.getByRole('link', { name: 'Ver detalle', exact: true }).first();
  await opener.focus(); await page.keyboard.press('Enter');
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(opener).toBeFocused();
  record('A05/A19/A23: filtros, exclusiones, apertura con teclado y retorno de foco');
  await go('team', '&focusMonth=2026-10&q=Ana');
  await page.getByRole('link', { name: 'Ver detalle', exact: true }).click();
  await page.getByRole('button', { name: 'Tareas', exact: true }).click();
  await page.getByLabel('Buscar tarea o centro').fill('Marina');
  await page.getByLabel('Fecha de la tarea').fill('2026-10-06');
  await page.getByLabel('Tipo de tareas').selectOption('registered');
  await expect(page.getByRole('dialog').locator('.sf-task-card')).toHaveCount(1);
  await page.getByRole('link', { name: 'Ver tarea', exact: true }).click();
  await page.getByRole('button', { name: 'Volver a las tareas de la persona' }).click();
  await expect(page.getByLabel('Buscar tarea o centro')).toHaveValue('Marina');
  await expect(page.getByLabel('Fecha de la tarea')).toHaveValue('2026-10-06');
  await page.getByRole('link', { name: 'Ver tarea', exact: true }).click();
  await page.keyboard.press('Escape');
  await expect(page.getByLabel('Tipo de tareas')).toHaveValue('registered');
  await page.getByLabel('Buscar tarea o centro').fill('sin-coincidencias');
  await expect(page.getByText('No hay tareas con estos filtros.')).toBeVisible();
  await page.getByRole('button', { name: 'Limpiar filtros de tareas' }).click();
  await page.keyboard.press('Escape');
  await expect(page.getByLabel('Buscar persona')).toHaveValue('Ana');
  record('UI-10: tareas filtrables; apertura y regreso al perfil mantienen fecha, búsqueda y filtro del equipo');
  await go('settings', '&tab=data');
  const issueGroup = page.locator('.sf-issue-group').filter({ hasText: 'Revisar jornadas' });
  await expect(issueGroup.locator('summary').first()).toContainText('1 persona');
  await expect(issueGroup.getByRole('link')).toHaveCount(0);
  await issueGroup.locator('summary').first().click();
  await expect(issueGroup.getByRole('link', { name: 'Revisar Jornada Por Revisar' })).toBeVisible();
  record('UI-07: recuento de registros afectados, incidencias desplegadas bajo demanda y enlace reconocible');
  await go('forecast', '&view=week&scenario=reserve');
  await page.getByRole('button', { name: 'Simular refuerzo', exact: true }).click();
  await page.getByLabel('Horas semanales').fill('-1');
  await page.getByRole('button', { name: 'Ver simulación' }).click();
  await expect(page.getByRole('alert')).toContainText('Indica horas positivas');
  await page.getByLabel('Horas semanales').fill('15,5');
  await page.getByRole('button', { name: 'Ver simulación' }).click();
  await expect(page.locator('.sf-simulation')).toContainText('15,5 h/semana');
  expect(new URL(page.url()).searchParams.get('simFrom')).toBe('2026-10-19');
  expect(new URL(page.url()).searchParams.get('simTo')).toBe('2026-10-25');
  await expect(page.getByText(/Sin propuesta viable:.*antes.*después/)).toBeVisible(); await page.getByText('Desglose del resultado y reconciliación', {exact:true}).click(); await expect(page.getByText('Sin propuesta viable antes',{exact:true})).toBeVisible();
  await page.getByRole('button', { name: 'Volver a situación actual' }).click();
  expect(new URL(page.url()).searchParams.get('scenario')).toBe('reserve');
  await expect(page.locator('.sf-simulation')).toHaveCount(0);
  record('A11/A17: simulación semanal, validación decimal y restauración conservando reserva');
  await go('reports', '&fixture=partial&focusMonth=2026-10');
  await expect(page.locator('.sf-donut')).toHaveCount(0);
  await page.getByLabel('Orden del informe').selectOption('pending');
  await expect(page.locator('tbody tr').first()).toContainText('Horas pendientes');
  await page.getByLabel('Buscar persona').fill('Jornada Por Revisar');
  const downloadEvent = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Exportar CSV' }).click();
  const download = await downloadEvent;
  expect(download.suggestedFilename()).toBe('prevision-hours-2026-10.csv');
  const csv = readFileSync(await download.path(), 'utf8');
  expect(csv).toContain('Jornada Por Revisar'); expect(csv).toContain('Por verificar'); expect(csv).toContain('Búsqueda'); expect(csv).not.toContain('Ana García');
  await page.getByLabel('Tipo de informe', { exact: true }).selectOption('absences');
  await expect(page.getByRole('table')).toContainText('Mantenimiento');
  const second = page.waitForEvent('download'); await page.getByRole('button', { name: 'Exportar CSV' }).click();
  const absenceDownload = await second;
  expect(absenceDownload.suggestedFilename()).toBe('prevision-absences-2026-10.csv');
  expect(readFileSync(await absenceDownload.path(), 'utf8')).toContain('Mantenimiento');
  record('A07/A18/A21: datos desconocidos sin anillo, descarga real CSV con contexto y filtros');
  await go('forecast', '&fixture=loading'); await page.getByRole('button', { name: 'Cancelar consulta' }).click();
  await expect(page.getByRole('alert')).toContainText('Consulta cancelada');
  await expect(page.locator('.sf-metric')).toHaveCount(0);
  await page.getByRole('button', { name: 'Reintentar' }).click();
  await expect(page.getByRole('heading', { name: 'Evolución por semana' })).toBeVisible();
  record('A20: cancelación y reintento sin resultados anteriores aparentando vigencia');
  await go('team', '&focusMonth=2026-12');
  await expect(page.getByRole('heading', { name: 'Este mes no está calculado' })).toBeVisible();
  await expect(page.locator('.sf-metric')).toHaveCount(0);
  await page.getByRole('button', { name: 'Consultar este mes completo' }).click();
  await expect(page.getByRole('heading', { name: 'Equipo · Diciembre de 2026', exact: false })).toBeVisible();
  record('A02/A12: mes fuera del horizonte sin falsos ceros; consulta explícita del mes completo');
  await go('centers', '&focusMonth=2026-10');
  await page.getByLabel('Buscar centro', { exact: true }).last().fill('sin-coincidencias');
  await expect(page.getByText('No hay centros con estos filtros.')).toBeVisible();
  await page.getByRole('button', { name: 'Limpiar filtros' }).last().click();
  await expect(page.locator('.sf-center-item').first()).toBeVisible();
  record('A19: búsqueda de centros vacía recuperable sin perder periodo');
  await go('forecast');
  await page.getByText('Consultar tabla de datos del gráfico').click();
  await expect(page.locator('.sf-chart-data')).toContainText('Pasado');
  await expect(page.locator('.sf-chart-data')).toContainText('Futuro');
  const point = page.locator('.sf-chart circle').first();
  await point.focus(); await point.press('Enter');
  await expect(page.getByRole('status')).toContainText('capacidad');
  record('A23/A24: gráfico consultable por teclado y tabla; pasado y futuro diferenciados');
  for (const width of [390, 768, 1024, 1440]) {
    await page.setViewportSize({ width, height: width < 500 ? 844 : 1000 });
    for (const screen of ['home', 'forecast', 'team', 'shifts', 'centers', 'reports', 'settings']) {
      await go(screen, '&focusMonth=2026-10');
      await expect(page.locator('.sf-skip-link')).not.toBeInViewport();
      const size = await page.evaluate(() => ({ content: document.documentElement.scrollWidth, viewport: innerWidth }));
      expect(size.content, `${screen} at ${width}`).toBeLessThanOrEqual(size.viewport + 1);
      await page.screenshot({ path: join(outputDir, `${screen}-${width}.png`), fullPage: true });
    }
    if (width === 390) {
      await page.getByRole('button', { name: 'Menú', exact: true }).click();
      await expect(page.getByRole('navigation', { name: 'Navegación del previsor' })).toBeVisible();
      await page.getByRole('link', { name: 'Equipo', exact: true }).click();
      await page.getByRole('button', { name: 'Filtrar', exact: true }).click();
      await expect(page.getByLabel('Mes del objetivo')).toBeVisible();
    }
  }
  record('A22: siete pantallas en 390/768/1024/1440 sin desbordamiento global; menú móvil y filtros');
  await page.setViewportSize({ width: 390, height: 844 });
  await go('shifts', '&view=day&date=2026-10-19');
  await expect(page.locator('.sf-timeline')).toBeVisible();
  await page.screenshot({ path: join(outputDir, 'coverage-day-390.png'), fullPage: true });
  await page.getByRole('link', { name: 'Ventana contradictoria', exact: true }).first().click();
  await expect(page.getByRole('dialog')).toContainText('33 min');
  await page.screenshot({ path: join(outputDir, 'task-detail-390.png') });
  const dialogBounds = await page.getByRole('dialog').boundingBox();
  expect(dialogBounds.x).toBeGreaterThanOrEqual(0); expect(dialogBounds.x + dialogBounds.width).toBeLessThanOrEqual(390);
  await page.getByRole('dialog').press('Escape');
  await page.getByLabel('Vista de cobertura').selectOption('month');
  await expect(page.locator('.sf-month-grid')).toBeVisible();
  await expect(page.locator('.sf-timeline')).toHaveCount(0);
  await page.screenshot({ path: join(outputDir, 'coverage-month-390.png'), fullPage: true });
  await go('team', '&focusMonth=2026-10');
  await page.getByRole('link', { name: 'Ver detalle', exact: true }).first().click();
  await page.getByRole('button', { name: 'Disponibilidad', exact: true }).click();
  await expect(page.getByRole('dialog')).toContainText('Servicios recurrentes e indisponibilidad de la ficha');
  await expect(page.getByRole('button', { name: 'Cerrar detalle' })).toBeInViewport();
  const closeBounds = await page.getByRole('button', { name: 'Cerrar detalle' }).boundingBox();
  expect(closeBounds.x + closeBounds.width).toBeLessThanOrEqual(390);
  await page.screenshot({ path: join(outputDir, 'person-availability-390.png') });
  record('A07/A13/A22: agenda diaria, calendario mensual y detalles móviles distintos y legibles');
  for (const width of [390, 1440]) {
    await page.setViewportSize({ width, height: 1000 });
    for (const screen of ['home', 'forecast', 'team', 'shifts', 'centers', 'reports', 'settings']) {
      await go(screen, '&focusMonth=2026-10');
      // Text enlargement is applied to computed sizes, all measured before any mutation.
      // It exercises reflow without pretending that deviceScaleFactor is browser zoom.
      await page.evaluate(() => {
        const sizes = [...document.querySelectorAll('.sf-workspace, .sf-workspace *')].map(el => [el, parseFloat(getComputedStyle(el).fontSize)]);
        sizes.forEach(([el, size]) => { if (el instanceof HTMLElement || el instanceof SVGElement) el.style.fontSize = size * 2 + 'px'; });
      });
      const size = await page.evaluate(() => ({ content: document.documentElement.scrollWidth, viewport: innerWidth }));
      if (size.content > size.viewport + 1) console.log(await page.evaluate(() => [...document.querySelectorAll('.sf-workspace *')].filter(e => e.getBoundingClientRect().right > innerWidth + 1 && !e.closest('.sf-table-scroll,.sf-chart-scroll,.sf-timeline-scroll')).slice(0, 12).map(e => ({ tag: e.tagName, class: e.className, text: e.textContent.slice(0, 100), right: e.getBoundingClientRect().right }))));
      expect(size.content, `${screen} with 200% text at ${width}`).toBeLessThanOrEqual(size.viewport + 1);
      if (screen === 'team') await page.screenshot({ path: join(outputDir, `team-text-200-${width}.png`), fullPage: true });
    }
  }
  record('A22/A23: aumento de texto al 200 % en las siete pantallas, en móvil y escritorio');
  const luminance = hex => { const rgb = hex.match(/[0-9a-f]{2}/gi).map(v => parseInt(v, 16) / 255).map(v => v <= .04045 ? v / 12.92 : ((v + .055) / 1.055) ** 2.4); return rgb[0] * .2126 + rgb[1] * .7152 + rgb[2] * .0722; };
  const contrast = (a, b) => (Math.max(luminance(a), luminance(b)) + .05) / (Math.min(luminance(a), luminance(b)) + .05);
  for (const [fg, bg] of [['18334b', 'ffffff'], ['526b7c', 'f4f8fb'], ['405e75', 'eff5f8'], ['ffffff', '285d94'], ['795719', 'fff1d7'], ['206448', 'e6f4ee'], ['285d94', 'eef5fc'], ['e0eaf0', '19394f'], ['8e352f', 'fff0ee']]) expect(contrast(fg, bg), `text #${fg} on #${bg}`).toBeGreaterThanOrEqual(4.5);
  record('A23: nueve pares de color de texto ≥4,5:1; no sustituye auditoría accesible con sesión real');

  }
  await page.setViewportSize({ width: 1440, height: 900 });
  await go('forecast', '&focusMonth=2026-10&fixture=partial&scenario=reserve');
  const attention = page.locator('.sf-team-attention');
  await expect(attention.getByRole('link', {name:/pendientes de evaluar/})).toContainText(/pendientes de evaluar/);
  await expect(page.getByText('Subtotal turístico conocido', { exact: true })).toBeVisible();
  await expect(page.locator('.sf-forecast-metrics').getByText('Subtotal con reserva', { exact: true })).toBeVisible();
  await attention.getByRole('link', {name:/pendientes de evaluar/}).click();
  await expect(page.getByLabel('Mostrar')).toHaveValue('unknown');
  record('R03/N05: evaluación pendiente y horas por completar tienen accesos separados');
  await go('forecast', '&fixture=partial');
  await page.getByRole('link', { name: '1 tarea sin duración · total pendiente' }).click();
  await expect(page.getByLabel('Filtro de tareas')).toHaveValue('unknown-duration');
  await expect(page.locator('.sf-context-line strong')).toContainText('1 tarea');
  record('R10: subtotal incluye duraciones válidas del día incompleto y enlace abre exactamente su bloqueo');
  await go('forecast');
  const upcoming = page.locator('.sf-panel').filter({ has: page.getByRole('heading', { name: 'Trabajo por resolver desde hoy' }) });
  await expect(upcoming.locator(':scope > .sf-day-list > div')).toHaveCount(3);
  await expect(upcoming.locator(':scope > .sf-day-list > div').first()).toContainText('lun, 5 oct');
  await expect(upcoming.getByText(/Registros anteriores por revisar/)).toBeVisible();
  await upcoming.getByRole('link', {name:/Ver todo el trabajo por revisar/}).click();
  await expect(page.locator('.sf-filter-day')).not.toHaveCount(0);
  record('R04: fechas futuras separadas del histórico, motivo local y acceso al conjunto completo');
  await go('forecast', '&view=week&center=empty-center');
  await expect(page.locator('.sf-day-list .sf-badge').filter({ hasText: 'Sin tareas registradas' })).toHaveCount(7);
  await expect(page.getByRole('link', { name: /0 tareas sin asignar.*candidatos/ })).toHaveCount(0);
  await expect(page.locator('.sf-day-list')).not.toContainText('Pendiente de verificar');
  record('R05/R11: centro sin tareas no hereda estados de tareas ajenas ni ofrece cero candidatos');
  await go('forecast', '&view=week&fixture=no-fit&refuerzo=15.5&simFrom=2026-10-19&simTo=2026-10-25');
  const comparison = page.locator('.sf-panel').filter({ has: page.getByRole('heading', { name: 'Comparación del refuerzo con el equipo actual' }) });
  await expect(comparison.getByText('El refuerzo no aporta encajes adicionales con los datos disponibles.')).toBeVisible();
  const compareBox = await comparison.boundingBox(), chartBox = await page.locator('.sf-chart').boundingBox();
  expect(compareBox.y).toBeLessThan(chartBox.y);
  const capacityLabels = await page.locator('.sf-chart circle[aria-label*="Capacidad de referencia"]').evaluateAll(es => es.map(e => e.getAttribute('aria-label')));
  expect(capacityLabels.every(s => s.endsWith('0 h'))).toBe(true);
  await expect(page.locator('.sf-simulation')).toContainText('15,5 h/semana');
  record('R07/R08: cero encajes destacado junto a simulación; capacidad real sin mejora ficticia; decimal español');
  await go('forecast', '&view=week&fixture=sequence&refuerzo=15&simFrom=2026-10-19&simTo=2026-10-25');
  await page.getByText('Ver propuestas del refuerzo por fecha y hora', { exact: true }).click();
  expect(await page.locator('.sf-detail-block .sf-task-name').allTextContents()).toEqual(['Servicio primero', 'Servicio segundo', 'Servicio tercero']);
  await page.getByText('Desglose del resultado y reconciliación',{exact:true}).click();
  await expect(page.getByText(/3 pendientes − 3 resueltas por refuerzo − 0 por reorganización/)).toBeVisible();
  record('R08: contadores reconciliados por identidad y propuestas ordenadas por hora');
  await go('forecast', '&view=week');
  await page.getByText('Desglose diario de la capacidad del equipo', { exact: true }).click();
  await page.locator('.sf-capacity-breakdown > details > summary').first().click();
  await expect(page.locator('.sf-capacity-breakdown')).toContainText('Ajuste al límite semanal');
  await expect(page.locator('.sf-capacity-breakdown')).toContainText('Otros servicios computables del día');
  record('R06: desglose diario consultable con bloqueos, cómputo de servicios y límite semanal');
  await go('team', '&fixture=other-services&focusMonth=2026-10&person=w0');
  await expect(page.getByRole('dialog').getByText('Otros servicios ya incluidos')).toBeVisible();
  await expect(page.getByRole('dialog').locator('.sf-detail-list')).toContainText('1 h');
  await page.getByRole('button', { name: 'Disponibilidad', exact: true }).click();
  await expect(page.getByRole('dialog').getByRole('link', { name: 'Turno importado de prueba', exact: true })).toBeVisible();
  await expect(page.getByRole('dialog')).not.toContainText('No hay otros servicios registrados en este mes');
  record('R12: el servicio incluido en el balance también aparece con su franja en disponibilidad');
  await go('forecast', '&view=week&week=2026-09-28');
  await expect(page.getByRole('link', { name: 'Objetivos de septiembre de 2026', exact: true })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Objetivos de octubre de 2026', exact: true })).toBeVisible();
  await page.getByLabel('Mes del objetivo').selectOption('2026-10');
  await expect(page.locator('.sf-team-attention')).toContainText('Objetivos de octubre de 2026');
  record('R13: semana partida da acceso a ambos balances y permite seleccionar el mes');
  await go('forecast', '&fixture=partial');
  await page.locator('.sf-quality > summary').click();
  const durationIssue = page.locator('.sf-issue-group').filter({ hasText: 'Revisar duración de tareas' });
  await expect(durationIssue.locator('summary').first()).not.toContainText('0 propiedades');
  await durationIssue.locator('summary').first().click();
  await expect(durationIssue.getByRole('link', { name: /Revisar duración:/ })).toHaveCount(1);
  await expect(page.locator('.sf-issues').getByText(/Toda la sede/).first()).toBeVisible();
  record('R11: avisos con ámbito y acción principal; contadores irrelevantes ocultos');
  await go('forecast');
  const partialPoints = page.locator('.sf-chart circle[aria-label*="semana parcial"]');
  await expect(partialPoints).toHaveCount(4);
  const partialXs = await partialPoints.evaluateAll(es => es.map(e => e.getAttribute('cx')));
  const drawnSegments = await page.locator('.sf-chart line[stroke="#285d94"]').evaluateAll(es => es.map(e => [e.getAttribute('x1'), e.getAttribute('x2')]));
  expect(drawnSegments.every(xs => xs.every(x => !partialXs.includes(x)))).toBe(true);
  for (const width of [390, 768, 1024, 1440]) {
    await page.setViewportSize({ width, height: width === 390 ? 844 : width === 1024 ? 768 : 900 });
    await go('forecast');
    await expect(page.locator('.sf-chart')).toBeVisible();
    await expect.poll(() => page.locator('.sf-chart').evaluate(e => e.getBoundingClientRect().width)).toBeLessThanOrEqual(width);
    const size = await page.locator('.sf-chart-scroll').evaluate(e => ({ scroll: e.scrollWidth, width: e.clientWidth }));
    expect(size.scroll).toBeLessThanOrEqual(size.width + 1);
    if (width === 390) {
      await expect(page.locator('.sf-month-summaries')).toBeVisible();
      await expect(page.locator('.sf-month-summaries > article')).toHaveCount(3);
      await page.getByRole('button', { name: 'Menú', exact: true }).click();
      await page.keyboard.press('Escape');
      await expect(page.getByRole('button', { name: 'Menú', exact: true })).toHaveAttribute('aria-expanded', 'false');
      await expect(page.getByRole('button', { name: 'Menú', exact: true })).toBeFocused();
    }
    await page.screenshot({ path: join(outputDir, 'revision-forecast-' + width + '.png'), fullPage: true });
  }
  record('R09/R13/móvil: semanas parciales sin trazos engañosos, tendencia completa, tarjetas mensuales y Escape');


  await page.setViewportSize({width:1440,height:900});
  await go('forecast','&fixture=four-durations');
  await page.getByRole('link',{name:'4 tareas sin duración · total pendiente'}).click();
  await expect(page.locator('.sf-context-line strong')).toContainText('4 tareas');
  await expect(page.locator('.sf-filter-day')).toHaveCount(4);
  await expect(page.locator('.sf-filter-day .sf-task-card')).toHaveCount(4);
  await expect(page.locator('.sf-day-cell')).toHaveCount(0);
  for(const day of [4,11,18,25]) await expect(page.getByRole('link',{name:'Duración pendiente '+day,exact:true})).toBeVisible();
  await page.getByRole('link',{name:'Duración pendiente 18',exact:true}).click();
  await expect(page.getByRole('dialog')).toContainText('18 de septiembre');
  await expect(page.getByRole('dialog')).toContainText('Datos insuficientes');
  await page.getByRole('button',{name:'Cerrar detalle'}).click();
  await page.getByRole('link',{name:'Ver calendario completo de este periodo'}).click();
  await expect(page.locator('.sf-day-cell')).toHaveCount(91);
  record('N03: cuatro duraciones abren cuatro registros en cuatro fechas; detalle exacto y calendario completo secundario');
  await go('forecast','&fixture=record-cases&view=week&refuerzo=15&simFrom=2026-10-19&simTo=2026-10-25');
  await expect(page.getByText('Sin propuesta viable: 0 antes → 0 después.')).toBeVisible();
  await expect(page.locator('.sf-day-list')).not.toContainText('Tareas sin encaje');
  await expect(page.locator('.sf-day-list')).toContainText('Registro por corregir · Propuesta disponible');
  await page.locator('.sf-simulation-records').getByRole('link',{name:'11 ya tienen encaje'}).click();
  await expect(page.getByLabel('Filtro de tareas')).toHaveValue('record-with-fit');
  await expect(page.locator('.sf-context-line strong')).toContainText('11 tareas');
  await expect(page.locator('.sf-filter-day .sf-task-card')).toHaveCount(11);
  await page.getByRole('link',{name:'Registro con propuesta 0',exact:true}).click();
  await expect(page.getByRole('dialog')).toContainText('El horario registrado queda fuera de la ventana del cliente.');
  await expect(page.getByRole('dialog')).toContainText('Propuesta disponible');
  record('N02: once registros por corregir con propuesta frente a cero sin capacidad; misma población hasta el detalle');
  await go('team','&fixture=recurring-profile&person=w1&focusMonth=2026-10');
  await expect(page.getByRole('dialog')).toContainText('4,5 h');
  await page.getByRole('button',{name:'Disponibilidad',exact:true}).click();
  await expect(page.getByRole('link',{name:'Hotel de prueba recurrente',exact:true})).toBeVisible();
  await expect(page.getByRole('dialog')).toContainText('Compromiso recurrente · aún sin tarea materializada');
  await page.getByRole('link',{name:'Hotel de prueba recurrente',exact:true}).click();
  await expect(page.getByRole('dialog')).toContainText('09:30–14:00');
  record('N01: compromiso recurrente reconocible en balance, disponibilidad y detalle sin escrituras');
  const layout=[];
  for (const width of [390,768,1024,1440]) {
    await page.setViewportSize({width,height:width===390?844:width===1024?768:900});
    await go('forecast','&focusMonth=2026-10');
    const months=page.getByRole('heading',{name:'Resumen por mes natural'}), daily=page.getByRole('heading',{name:'Trabajo por resolver desde hoy'});
    const positions=await Promise.all([months.boundingBox(),daily.boundingBox(),page.locator('.sf-chart').boundingBox()]);
    expect(positions[0].y).toBeLessThan(positions[1].y);
    const card=page.locator('.sf-team-attention');
    await expect(card.getByLabel('Mes del objetivo')).toBeVisible();
    await expect(card.getByRole('link',{name:/con horas por completar/})).toBeVisible();
    await expect(card.getByRole('link',{name:/pendientes de evaluar/})).toBeVisible();
    const fontSizes=await card.locator('.sf-attention-stats strong').evaluateAll(es=>es.map(e=>getComputedStyle(e).fontSize));
    expect(fontSizes[0]).toEqual(fontSizes[1]);
    await card.getByRole('link',{name:/con horas por completar/}).click();
    await expect(page.getByLabel('Mostrar')).toHaveValue('risk');
    await expect(page.getByLabel('Mes del objetivo')).toHaveValue('2026-10');
    await go('forecast','&focusMonth=2026-10');
    layout.push({width,monthsY:positions[0].y,chartY:positions[2].y});
    await page.screenshot({path:join(outputDir,'incidents-forecast-'+width+'.png'),fullPage:true});
  }
  writeFileSync(join(outputDir,'layout.json'),JSON.stringify(layout,null,2));
  record('N05: meses antes de problemas diarios, dos cifras iguales y mes integrado; filtros correctos en cuatro anchos');
  expect(errors).toEqual([]); expect(requests).toEqual([]);
  writeFileSync(join(outputDir, 'resultados.json'), JSON.stringify({ checks, errors, unexpectedRequests: requests }, null, 2));
} finally { await browser.close(); }
