import { build } from 'esbuild';
import { chromium, expect } from '@playwright/test';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
const outputDir = 'docs/previsor/ui-ux-capturas';
mkdirSync(outputDir, { recursive: true });
const built = await build({ entryPoints: ['scripts/forecastUiAcceptance.entry.tsx'], bundle: true, outdir: 'test-ui', write: false, platform: 'browser', format: 'iife', jsx: 'automatic', metafile: true, define: { 'process.env.NODE_ENV': '"production"' } });
expect(Object.keys(built.metafile.inputs).some(p => p.includes('integrations/supabase'))).toBe(false);
const js = built.outputFiles.find(f => f.path.endsWith('.js')).text;
const css = built.outputFiles.find(f => f.path.endsWith('.css')).text;
const html = `<!doctype html><html lang="es"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:0}*{box-sizing:border-box}${css}</style><div id="root"></div><script>${js.replaceAll('</script', '<\\/script')}</script></html>`;
const browser = await chromium.launch({ headless: true });
const errors = [], requests = [], checks = [];
const origin = 'http://forecast.test';
const query = 'month=2026-09&horizon=3&week=2026-10-19';
const record = text => { checks.push(text); console.log('PASS', text); };
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  page.on('pageerror', error => errors.push(error.message));
  await page.route('**/*', route => { const r = route.request(); if (r.url().startsWith(origin) && r.isNavigationRequest()) return route.fulfill({ contentType: 'text/html', body: html }); requests.push(r.url()); return route.abort(); });
  const go = async (screen, extra = '') => { await page.goto(`${origin}/staffing-forecast/screens/${screen}?${query}${extra}`); await expect(page.locator('h1')).toBeVisible(); };
  await go('home');
  await expect(page.getByRole('heading', { name: 'Pendiente de revisar' })).toBeVisible();
  await expect(page.getByText('Revisar datos que impiden cerrar la previsión')).toBeVisible();
  record('A01/A02: Inicio prioriza datos y separa objetivos pendientes de evaluación');
  await go('forecast', '&view=week');
  await expect(page.locator('.sf-context')).toContainText('19 de octubre de 2026');
  const countLink = page.locator('.sf-panel-actions a').filter({ hasText: /tareas? sin asignar/ }).first();
  const text = await countLink.innerText(), count = Number(text.match(/\d+/)[0]);
  await countLink.click();
  await expect(page.getByLabel('Vista de cobertura')).toHaveValue('week');
  const displayed = await page.locator('.sf-context-line strong').innerText();
  expect(displayed).toContain(`${count} tareas`);
  record('A03/A04: contador semanal y destino coinciden sin cambiar al mes');
  await go('shifts', '&view=day&date=2026-10-19&task=window-conflict&detail=candidates');
  const dialog = page.getByRole('dialog');
  await expect(dialog.getByText('33 min', { exact: true })).toBeVisible();
  await expect(dialog.getByText('El horario registrado queda fuera de la ventana del cliente.')).toBeVisible();
  const calendar = dialog.getByRole('link', { name: /Abrir en calendario diario/ });
  expect(await calendar.getAttribute('href')).toBe('/calendar?date=2026-10-19&task=window-conflict');
  await expect(calendar).toHaveAttribute('target', '_blank');
  const profile = dialog.getByRole('link', { name: 'Ver perfil' }).first();
  await expect(profile).toBeVisible();
  if (await profile.count()) {
    await profile.click();
    await expect(page.getByLabel('Mes del balance')).toHaveValue('2026-10');
    await page.getByRole('button', { name: 'Volver a candidatos' }).click();
    await expect(page.getByRole('heading', { name: 'Candidatos para Ventana contradictoria' })).toBeVisible();
  }
  record('A03/A08/A13/A15: tarea, ventana, propuesta, perfil de octubre y enlace operativo');
  await go('team', '&focusMonth=2026-10');
  await expect(page.locator('.sf-team-list')).not.toContainText('Persona Excluida');
  await page.getByLabel('Mostrar').selectOption('unknown');
  await expect(page.locator('.sf-team-list')).toContainText('Jornada Por Revisar');
  await page.getByLabel('Buscar persona').fill('ninguna-persona');
  await expect(page.getByText('No hay personas con estos filtros.')).toBeVisible();
  await page.getByRole('button', { name: 'Limpiar filtros' }).first().click();
  const opener = page.getByRole('link', { name: 'Ver detalle', exact: true }).first();
  await opener.focus(); await page.keyboard.press('Enter');
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(opener).toBeFocused();
  record('A05/A19/A23: filtros, exclusiones, apertura con teclado y retorno de foco');
  await go('team', '&focusMonth=2026-10&q=Ana');
  await page.getByRole('link', { name: 'Ver detalle', exact: true }).click();
  await page.getByRole('button', { name: 'Tareas', exact: true }).click();
  await page.getByLabel('Buscar tarea o centro').fill('Marina');
  await page.getByLabel('Fecha de la tarea').fill('2026-10-06');
  await page.getByLabel('Tipo de tareas').selectOption('registered');
  await expect(page.getByRole('dialog').locator('.sf-task-card')).toHaveCount(1);
  await page.getByRole('link', { name: 'Ver tarea', exact: true }).click();
  await page.getByRole('button', { name: 'Volver a las tareas de la persona' }).click();
  await expect(page.getByLabel('Buscar tarea o centro')).toHaveValue('Marina');
  await expect(page.getByLabel('Fecha de la tarea')).toHaveValue('2026-10-06');
  await page.getByRole('link', { name: 'Ver tarea', exact: true }).click();
  await page.keyboard.press('Escape');
  await expect(page.getByLabel('Tipo de tareas')).toHaveValue('registered');
  await page.getByLabel('Buscar tarea o centro').fill('sin-coincidencias');
  await expect(page.getByText('No hay tareas con estos filtros.')).toBeVisible();
  await page.getByRole('button', { name: 'Limpiar filtros de tareas' }).click();
  await page.keyboard.press('Escape');
  await expect(page.getByLabel('Buscar persona')).toHaveValue('Ana');
  record('UI-10: tareas filtrables; apertura y regreso al perfil mantienen fecha, búsqueda y filtro del equipo');
  await go('settings', '&tab=data');
  const issueGroup = page.locator('.sf-issue-group').filter({ hasText: 'Revisar jornadas' });
  await expect(issueGroup.locator('summary').first()).toContainText('1 persona');
  await expect(issueGroup.getByRole('link')).toHaveCount(0);
  await issueGroup.locator('summary').first().click();
  await expect(issueGroup.getByRole('link', { name: 'Revisar Jornada Por Revisar' })).toBeVisible();
  record('UI-07: recuento de registros afectados, incidencias desplegadas bajo demanda y enlace reconocible');
  await go('forecast', '&view=week&scenario=reserve');
  await page.getByRole('button', { name: 'Simular refuerzo', exact: true }).click();
  await page.getByLabel('Horas semanales').fill('-1');
  await page.getByRole('button', { name: 'Ver simulación' }).click();
  await expect(page.getByRole('alert')).toContainText('Indica horas positivas');
  await page.getByLabel('Horas semanales').fill('15,5');
  await page.getByRole('button', { name: 'Ver simulación' }).click();
  await expect(page.locator('.sf-simulation')).toContainText('15.5 h/semana');
  expect(new URL(page.url()).searchParams.get('simFrom')).toBe('2026-10-19');
  expect(new URL(page.url()).searchParams.get('simTo')).toBe('2026-10-25');
  await expect(page.getByText(/tareas? sin encaje planificado/)).toHaveCount(2);
  await page.getByRole('button', { name: 'Volver a situación actual' }).click();
  expect(new URL(page.url()).searchParams.get('scenario')).toBe('reserve');
  await expect(page.locator('.sf-simulation')).toHaveCount(0);
  record('A11/A17: simulación semanal, validación decimal y restauración conservando reserva');
  await go('reports', '&fixture=partial&focusMonth=2026-10');
  await expect(page.locator('.sf-donut')).toHaveCount(0);
  await page.getByLabel('Orden del informe').selectOption('pending');
  await expect(page.locator('tbody tr').first()).toContainText('Horas pendientes');
  await page.getByLabel('Buscar persona').fill('Jornada Por Revisar');
  const downloadEvent = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Exportar CSV' }).click();
  const download = await downloadEvent;
  expect(download.suggestedFilename()).toBe('prevision-hours-2026-10.csv');
  const csv = readFileSync(await download.path(), 'utf8');
  expect(csv).toContain('Jornada Por Revisar'); expect(csv).toContain('Por verificar'); expect(csv).toContain('Búsqueda'); expect(csv).not.toContain('Ana García');
  await page.getByLabel('Tipo de informe', { exact: true }).selectOption('absences');
  await expect(page.getByRole('table')).toContainText('Mantenimiento');
  const second = page.waitForEvent('download'); await page.getByRole('button', { name: 'Exportar CSV' }).click();
  const absenceDownload = await second;
  expect(absenceDownload.suggestedFilename()).toBe('prevision-absences-2026-10.csv');
  expect(readFileSync(await absenceDownload.path(), 'utf8')).toContain('Mantenimiento');
  record('A07/A18/A21: datos desconocidos sin anillo, descarga real CSV con contexto y filtros');
  await go('forecast', '&fixture=loading'); await page.getByRole('button', { name: 'Cancelar consulta' }).click();
  await expect(page.getByRole('alert')).toContainText('Consulta cancelada');
  await expect(page.locator('.sf-metric')).toHaveCount(0);
  await page.getByRole('button', { name: 'Reintentar' }).click();
  await expect(page.getByRole('heading', { name: 'Evolución por semana' })).toBeVisible();
  record('A20: cancelación y reintento sin resultados anteriores aparentando vigencia');
  await go('team', '&focusMonth=2026-12');
  await expect(page.getByRole('heading', { name: 'Este mes no está calculado' })).toBeVisible();
  await expect(page.locator('.sf-metric')).toHaveCount(0);
  await page.getByRole('button', { name: 'Consultar este mes completo' }).click();
  await expect(page.getByRole('heading', { name: 'Equipo · Diciembre de 2026', exact: false })).toBeVisible();
  record('A02/A12: mes fuera del horizonte sin falsos ceros; consulta explícita del mes completo');
  await go('centers', '&focusMonth=2026-10');
  await page.getByLabel('Buscar centro', { exact: true }).last().fill('sin-coincidencias');
  await expect(page.getByText('No hay centros con estos filtros.')).toBeVisible();
  await page.getByRole('button', { name: 'Limpiar filtros' }).last().click();
  await expect(page.locator('.sf-center-item').first()).toBeVisible();
  record('A19: búsqueda de centros vacía recuperable sin perder periodo');
  await go('forecast');
  await page.getByText('Consultar tabla de datos del gráfico').click();
  await expect(page.locator('.sf-chart-data')).toContainText('Pasado');
  await expect(page.locator('.sf-chart-data')).toContainText('Futuro');
  const point = page.locator('.sf-chart circle').first();
  await point.focus(); await point.press('Enter');
  await expect(page.getByRole('status')).toContainText('capacidad');
  record('A23/A24: gráfico consultable por teclado y tabla; pasado y futuro diferenciados');
  for (const width of [390, 768, 1024, 1440]) {
    await page.setViewportSize({ width, height: width < 500 ? 844 : 1000 });
    for (const screen of ['home', 'forecast', 'team', 'shifts', 'centers', 'reports', 'settings']) {
      await go(screen, '&focusMonth=2026-10');
      await expect(page.locator('.sf-skip-link')).not.toBeInViewport();
      const size = await page.evaluate(() => ({ content: document.documentElement.scrollWidth, viewport: innerWidth }));
      expect(size.content, `${screen} at ${width}`).toBeLessThanOrEqual(size.viewport + 1);
      await page.screenshot({ path: join(outputDir, `${screen}-${width}.png`), fullPage: true });
    }
    if (width === 390) {
      await page.getByRole('button', { name: 'Menú', exact: true }).click();
      await expect(page.getByRole('navigation', { name: 'Navegación del previsor' })).toBeVisible();
      await page.getByRole('link', { name: 'Equipo', exact: true }).click();
      await page.getByRole('button', { name: 'Filtrar', exact: true }).click();
      await expect(page.getByLabel('Mes del objetivo')).toBeVisible();
    }
  }
  record('A22: siete pantallas en 390/768/1024/1440 sin desbordamiento global; menú móvil y filtros');
  await page.setViewportSize({ width: 390, height: 844 });
  await go('shifts', '&view=day&date=2026-10-19');
  await expect(page.locator('.sf-timeline')).toBeVisible();
  await page.screenshot({ path: join(outputDir, 'coverage-day-390.png'), fullPage: true });
  await page.getByRole('link', { name: 'Ventana contradictoria', exact: true }).first().click();
  await expect(page.getByRole('dialog')).toContainText('33 min');
  await page.screenshot({ path: join(outputDir, 'task-detail-390.png') });
  const dialogBounds = await page.getByRole('dialog').boundingBox();
  expect(dialogBounds.x).toBeGreaterThanOrEqual(0); expect(dialogBounds.x + dialogBounds.width).toBeLessThanOrEqual(390);
  await page.getByRole('dialog').press('Escape');
  await page.getByLabel('Vista de cobertura').selectOption('month');
  await expect(page.locator('.sf-month-grid')).toBeVisible();
  await expect(page.locator('.sf-timeline')).toHaveCount(0);
  await page.screenshot({ path: join(outputDir, 'coverage-month-390.png'), fullPage: true });
  await go('team', '&focusMonth=2026-10');
  await page.getByRole('link', { name: 'Ver detalle', exact: true }).first().click();
  await page.getByRole('button', { name: 'Disponibilidad', exact: true }).click();
  await expect(page.getByRole('dialog')).toContainText('Otros compromisos que ocupan disponibilidad');
  await expect(page.getByRole('button', { name: 'Cerrar detalle' })).toBeInViewport();
  const closeBounds = await page.getByRole('button', { name: 'Cerrar detalle' }).boundingBox();
  expect(closeBounds.x + closeBounds.width).toBeLessThanOrEqual(390);
  await page.screenshot({ path: join(outputDir, 'person-availability-390.png') });
  record('A07/A13/A22: agenda diaria, calendario mensual y detalles móviles distintos y legibles');
  for (const width of [390, 1440]) {
    await page.setViewportSize({ width, height: 1000 });
    for (const screen of ['home', 'forecast', 'team', 'shifts', 'centers', 'reports', 'settings']) {
      await go(screen, '&focusMonth=2026-10');
      // Text enlargement is applied to computed sizes, all measured before any mutation.
      // It exercises reflow without pretending that deviceScaleFactor is browser zoom.
      await page.evaluate(() => {
        const sizes = [...document.querySelectorAll('.sf-workspace, .sf-workspace *')].map(el => [el, parseFloat(getComputedStyle(el).fontSize)]);
        sizes.forEach(([el, size]) => { if (el instanceof HTMLElement || el instanceof SVGElement) el.style.fontSize = size * 2 + 'px'; });
      });
      const size = await page.evaluate(() => ({ content: document.documentElement.scrollWidth, viewport: innerWidth }));
      if (size.content > size.viewport + 1) console.log(await page.evaluate(() => [...document.querySelectorAll('.sf-workspace *')].filter(e => e.getBoundingClientRect().right > innerWidth + 1 && !e.closest('.sf-table-scroll,.sf-chart-scroll,.sf-timeline-scroll')).slice(0, 12).map(e => ({ tag: e.tagName, class: e.className, text: e.textContent.slice(0, 100), right: e.getBoundingClientRect().right }))));
      expect(size.content, `${screen} with 200% text at ${width}`).toBeLessThanOrEqual(size.viewport + 1);
      if (screen === 'team') await page.screenshot({ path: join(outputDir, `team-text-200-${width}.png`), fullPage: true });
    }
  }
  record('A22/A23: aumento de texto al 200 % en las siete pantallas, en móvil y escritorio');
  const luminance = hex => { const rgb = hex.match(/[0-9a-f]{2}/gi).map(v => parseInt(v, 16) / 255).map(v => v <= .04045 ? v / 12.92 : ((v + .055) / 1.055) ** 2.4); return rgb[0] * .2126 + rgb[1] * .7152 + rgb[2] * .0722; };
  const contrast = (a, b) => (Math.max(luminance(a), luminance(b)) + .05) / (Math.min(luminance(a), luminance(b)) + .05);
  for (const [fg, bg] of [['18334b', 'ffffff'], ['526b7c', 'f4f8fb'], ['405e75', 'eff5f8'], ['ffffff', '285d94'], ['795719', 'fff1d7'], ['206448', 'e6f4ee'], ['285d94', 'eef5fc'], ['e0eaf0', '19394f'], ['8e352f', 'fff0ee']]) expect(contrast(fg, bg), `text #${fg} on #${bg}`).toBeGreaterThanOrEqual(4.5);
  record('A23: nueve pares de color de texto ≥4,5:1; no sustituye auditoría accesible con sesión real');
  expect(errors).toEqual([]); expect(requests).toEqual([]);
  writeFileSync(join(outputDir, 'resultados.json'), JSON.stringify({ checks, errors, unexpectedRequests: requests }, null, 2));
} finally { await browser.close(); }
