import type { ForecastDataset, ForecastContext, ForecastTask, ForecastWorker } from '../src/features/staffing/forecastContract';
export const context: ForecastContext = { sedeId: '1e0759ec-5e63-4edd-9dad-e493c715bbba', month: '2026-10', horizon: 1, week: '2026-10-05', center: '', scenario: 'known', asOf: '2026-09-21T10:00' };
export const worker = (id = 'w', overrides: Partial<ForecastWorker> = {}): ForecastWorker => ({ id, name: `Persona ${id}`, weeklyMinutes: 900, weeklyMinutesMax: 1170, restDays: [1], restDay: 1, flexibleRest: false, canMove: true, contractKnown: true, excluded: false, availability: Array.from({ length: 7 }, (_, day) => ({ day, startMinute: 0, endMinute: 1440 })), homeCenterIds: ['c'], centerPriorities: [{ centerId: 'c', priority: 10 }], unavailableDates: [], confirmedRestDates: [], ...overrides });
export const task = (id = 't', overrides: Partial<ForecastTask> = {}): ForecastTask => ({ id, name: `Apartamento ${id}`, propertyId: `p:${id}`, centerId: 'c', date: '2026-10-06', minutes: 60, start: NaN, end: NaN, windowStart: 660, windowEnd: 1020, ambiguous: false, tourism: true, status: 'pending', ...overrides });
export const dataset = (overrides: Partial<ForecastDataset> = {}): ForecastDataset => ({ sedeId: context.sedeId, from: '2026-09-28', to: '2026-11-01', fetchedAt: '2026-09-21T08:00:00Z', rulesVersion: 'staffing-2026-09-21.1', centers: [{ id: 'c', name: 'Edificio de muestra', startMinute: 660, endMinute: 1020, propertyCount: 5 }], workers: [worker()], tasks: [task()], absences: [], issues: [], sources: [{ name: 'fixture sin conexión', count: 1, status: 'ready', fetchedAt: '2026-09-21T08:00:00Z' }], ...overrides });
export function visualFixture() {
  const centers = ['Marina', 'Plaza del Sol', 'Casa del Mar', 'Paseo del Puerto', 'Jardines', 'Residencial de nombre extenso para verificar la lectura'].map((name, i) => ({ id: `c${i}`, name, startMinute: 660, endMinute: 1020, propertyCount: i + 2 }));
  const workers = ['Ana García', 'Carlos Ruiz', 'Laura Martín', 'Javier López', 'María Torres', 'Sergio Díaz', 'Elena Navarro', 'David Moreno', 'Persona con nombre y apellidos especialmente largos'].map((name, i) => worker(`w${i}`, { name, weeklyMinutes: i === 8 ? 0 : 900, centerPriorities: [{ centerId: `c${i % 6}`, priority: i < 6 ? 10 : 20 }], restDays: [i % 6 + 1], restDay: i % 6 + 1 }));
  const tasks: ForecastTask[] = [];
  for (let day = 1; day <= 31; day++) for (let i = 0; i < (day % 7 === 4 ? 18 : 6); i++) tasks.push(task(`${day}-${i}`, { date: `2026-10-${String(day).padStart(2, '0')}`, name: `${centers[i % 6].name} · Apartamento ${i + 1}`, centerId: `c${i % 6}`, minutes: 75 + i % 3 * 15, ...(i < 3 && day < 10 ? { workerId: `w${i}`, start: 660, end: 660 + 75 + i % 3 * 15 } : {}) }));
  return dataset({ centers, workers, tasks });
}
