import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {readFileSync} from 'node:fs';
const result=await build({entryPoints:['src/utils/cleaning-planning/proposalBatchApply.ts'],bundle:true,write:false,format:'esm',platform:'node'});
const {validateProposalBatchForApply:validate,buildProposalSignature:signature}=await import(`data:text/javascript;base64,${Buffer.from(result.outputFiles[0].text).toString('base64')}`);
const task={id:'saved',date:'2026-09-16',startTime:'09:00',endTime:'10:00',status:'pending',cleanerId:'a'};
const proposal={taskId:'saved',cleanerId:'b',cleanerName:'B',proposedStartTime:'09:00',proposedEndTime:'10:00'};
const check=(p,fresh=task)=>validate({proposals:[p],proposalSignature:signature([p]),activeCleanerIds:['a','b'],expectedTasks:[task],freshTasks:[fresh]});
assert.equal(check(proposal).canApply,true,'Saved assignment can be reassigned');
assert.equal(check({...proposal,cleanerId:'a',proposedStartTime:'11:00',proposedEndTime:'12:00'}).canApply,true,'Same worker can change schedule');
assert.equal(check({...proposal,cleanerId:'a'}).canApply,false,'Unchanged assignment is not reapplied');
assert.equal(check(proposal,{...task,cleanerId:'b'}).canApply,false,'Concurrent reassignment remains protected');
assert.equal(check(proposal,{...task,startTime:'08:00'}).canApply,false,'Concurrent schedule edit remains protected');
const calendar=readFileSync('src/components/cleaning-planning/PlanningProposalCalendar.tsx','utf8');
assert.doesNotMatch(calendar,/editable: false/);
assert.ok(calendar.includes('id={`desktop:${item.id}`}'),'Saved cards have unique drag IDs');
const panel=readFileSync('src/components/cleaning-planning/AssignmentProposalPanel.tsx','utf8');
assert.match(panel,/new Set\(calendarTasks/,'Saved tasks are included in the save batch');
const page=readFileSync('src/components/cleaning-planning/CleaningPlanningPage.tsx','utf8');
assert.match(page,/expectedTasks: filteredTasks/);
assert.doesNotMatch(page,/if \(!proposal \|\| proposal.proposals.length === 0/);
console.log('PASS: saved reassignment, schedule-only changes, concurrent edit protection and saved-task save scope');
