import { build } from 'esbuild';
import { mkdtempSync, rmSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import assert from 'node:assert/strict';
const dir = mkdtempSync(join(tmpdir(), 'staffing-ui-'));
try {
  const outfile = join(dir, 'ui.cjs');
  await build({ stdin: { contents: `import React from 'react'; import {renderToStaticMarkup} from 'react-dom/server'; import {StaffingDashboard} from './src/features/staffing/StaffingDashboard'; export const html = renderToStaticMarkup(React.createElement(StaffingDashboard, {dataset:{centers:[],workers:[],services:[],issues:[],inventory:[],fetchedAt:'2026-09-14T12:00:00Z'}, dateFrom:'2026-09-14', asOf:'2026-09-14', weeks:12, compute:()=>({weeks:[],days:[],centers:[],issues:[]})}));`, resolveDir: process.cwd(), loader: 'tsx' }, outfile, jsx: 'automatic', bundle: true, platform: 'node', format: 'cjs', logLevel: 'silent' });
  const {html} = (await import(pathToFileURL(outfile).href)).default;
  for (const label of ['Previsión de personal','Simular cambios','Datos y criterios','Sin datos suficientes']) assert.ok(html.includes(label), label);
  const source = readFileSync('src/features/staffing/StaffingDashboard.tsx','utf8');
  const monthlySource = readFileSync('src/features/staffing/StaffingMonthly.tsx','utf8');
  assert.ok(!monthlySource.includes('Mes en curso · desde'), 'monthly observed-hours status is removed');
  assert.ok(!/supabase|\.insert\(|\.update\(|\.upsert\(/.test(source), 'view has no persistence');
  assert.ok(html.includes('Sin semanas/datos calculables para este mes'));
  assert.ok(!html.includes('Vistas de detalle'));
  assert.ok(html.includes('Previsión mensual'));
  assert.equal((html.match(/Datos y criterios/g) || []).length, 1, 'criteria link stays in the monthly header');
  assert.equal((html.match(/Horas de trabajo previsto/g) || []).length, 3, 'monthly cards label planned work');
  assert.equal((html.match(/Horas de trabajo posibles/g) || []).length, 3, 'monthly cards label possible work');
  assert.equal((html.match(/Equipo actual/g) || []).length, 3, 'monthly cards label current team');
  assert.ok(!html.includes('Solo se agregan días civiles únicos dentro del mes'), 'monthly criteria subtitle is removed');
  assert.ok(!html.includes('visión de conjunto'), 'monthly overview suffix is removed');
  assert.ok(!html.includes('Escenario bajo / alto: hipótesis editables'), 'scenario disclaimer is removed from overview');
  assert.ok(!html.includes('Solo se suman los días del mes'), 'week subtitle is removed');
  assert.ok(!html.includes('Mes en curso · desde'), 'monthly observed-hours status is removed');
  assert.ok(!html.includes('Decidir por meses. Afinar por semanas.'));
  assert.ok(!html.includes('Tres meses naturales · escenarios explícitos, no intervalos de confianza'));
  assert.ok(!html.includes('Solo simulación'));
  assert.ok(html.includes('Meses de previsión'));
  assert.ok(html.includes('Periodicidad'));
  assert.ok(html.includes('Mensual'));
  assert.ok(html.includes('Semanal'));
  assert.ok(readFileSync(join(process.cwd(), 'src/features/staffing/StaffingDashboard.tsx'), 'utf8').includes('Mes de análisis'));
  assert.ok(!html.includes('El total mensual no basta'));
  assert.ok(html.includes('Revisar distribución diaria'));
  assert.ok(html.includes('Capacidad mensual y encaje diario son distintos'));
  assert.ok(html.includes('Puede haber horas suficientes en el total del mes, pero cada servicio debe encajar en su día, horario y centro.'));

  assert.ok(html.includes('Abrir comparación diaria y mapa de centros →'), 'daily comparison action stays available');

  assert.ok(!html.includes('coste mensual validado'));
  assert.ok(!html.includes('Propuesta orientativa'));
  assert.equal((html.match(/<h1/g) || []).length, 1);
  for (const path of ['src/App.tsx', 'src/components/dashboard/DashboardSidebar.tsx', 'src/components/dashboard/MobileDashboardSidebar.tsx']) assert.ok(readFileSync(path, 'utf8').includes('/staffing-forecast'), `new route discoverable: ${path}`);
  console.log('staffing-ui-tests: OK (SSR empty/labels and read-only boundary)');
  const regressionFile = join(dir, 'regressions.cjs');
  await build({ stdin: { contents: `import React from 'react'; import {renderToStaticMarkup} from 'react-dom/server'; import {StaffingDashboard} from './src/features/staffing/StaffingDashboard'; import {buildStaffingForecast} from './src/features/staffing/engine';
    const base={centers:[{id:'c',name:'Centro',startMinute:480,endMinute:1080}],workers:[{id:'w',name:'Persona demo',weeklyMinutes:2400,homeCenterIds:['c'],availability:[0,1,2,3,4,5,6].map(day=>({day,startMinute:480,endMinute:1080})),restDay:0,flexibleRest:false,canMove:true,unavailableDates:[],confirmedRestDates:[]}],services:[{id:'s',centerId:'c',date:'2026-09-14',personMinutes:60,startMinute:600,endMinute:660,requiredWorkers:1,source:'task',kind:'fixed'}],issues:[{code:'inactive-properties-excluded',message:'2 propiedades inactivas excluidas de la planificación'}],inventory:[],providerCoverage:[{provider:'avantio',label:'Avantio',referenceDate:'2026-09-14',reservations30:4,reservations31to60:2,latestDate:'2026-11-20',status:'extended'},{provider:'lh',label:'Little Hotelier',referenceDate:'2026-09-14',reservations30:3,reservations31to60:0,latestDate:'2026-10-10',status:'one-month'},{provider:'avirato',label:'Avirato',referenceDate:'2026-09-14',reservations30:1,reservations31to60:1,latestDate:'2026-11-20',status:'extended'}],fetchedAt:''};
    export let calls=0;
    const render=(dataset, compute=(...args)=>{calls++;return buildStaffingForecast(...args)} )=>renderToStaticMarkup(React.createElement(StaffingDashboard,{dataset,dateFrom:'2026-09-14',asOf:'2026-09-14',weeks:1,compute}));
    export const valid=render(base); export const initialCalls=calls;
    export const invalid=render({...base,services:base.services.map(s=>({...s,personMinutes:0}))});
    export const incomplete=render({...base,issues:[{code:'source-unavailable',message:'Fuente no disponible'}]});
    export const estimated=render({...base,services:base.services.map(s=>({...s,kind:'checkout'}))});
    export const collaborators=render({...base,workers:[{...base.workers[0],id:'e',name:'Plantilla demo',weeklyMinutes:1200},{...base.workers[0],id:'c',name:'Colaborador demo',engagement:'collaborator',weeklyMinutes:600}]});
    export const duplicate=render(base, (...args)=>{const result=buildStaffingForecast(...args); return {...result,days:result.days.length ? [result.days[0], {...result.days[0]}] : result.days};});
  `, resolveDir: process.cwd(), loader: 'tsx' }, outfile: regressionFile, jsx:'automatic', bundle:true, platform:'node', format:'cjs',logLevel:'silent' });
  const regression = (await import(pathToFileURL(regressionFile).href)).default;
  for (const key of ['invalid','incomplete']) {
    assert.ok(regression[key].includes('Parcial: consultar datos y criterios'), key);
    assert.ok(!regression[key].includes('No se detecta déficit'), key);
    assert.ok(!regression[key].includes('de holgura calculada'), key);
  }
  assert.ok(regression.duplicate.includes('Parcial: consultar datos y criterios'), 'duplicate monthly data must mark the dashboard partial');
  assert.ok(!regression.duplicate.includes('Mes completo'), 'duplicate monthly data must not look complete');
  assert.equal(regression.initialCalls,1,'identical baseline and scenario evaluated only once');
  assert.ok(regression.valid.includes('Capacidad potencial'));
  assert.ok(regression.estimated.includes('estimadas sin comprobar'));
  assert.ok(!regression.estimated.includes('0,2 h sin encaje cuantificadas'),'expected minutes are not proven uncovered work');
  assert.ok(regression.collaborators.includes('10 h de autónomos ya incluidas'), 'collaborator share must be shown as included, not added to total');
  assert.ok(regression.collaborators.includes('10 h de autónomos ya incluidas'));
  assert.ok(!regression.collaborators.includes('aria-label="Coste de Colaborador demo"'), 'do not offer an ignored payroll price for collaborators');
  assert.ok(!regression.collaborators.includes('aria-label="Coste de Plantilla demo"'), 'editing only in explicitly opened scenario');
  assert.ok(!regression.valid.includes('2 propiedades inactivas excluidas de la planificación'), 'diagnostics are on demand, not repeated on first view');
  assert.ok(regression.incomplete.includes('No se pudieron leer todas las fuentes'), 'source failures stay visible');
  assert.ok(regression.valid.includes('staffing-estimate'), 'estimate distinguished by pattern');
  assert.ok(regression.valid.includes('staffing-tab-Días'), 'compact days view is the default');
  assert.ok(regression.valid.includes('Equilibrio diario de sede'), 'daily bars use site totals');
  assert.ok(!regression.valid.includes('Detalle por centro'), 'no ambiguous global center filter');
  assert.ok(!regression.valid.includes('Sin asignación calculada'), 'task details are not mounted initially');
  console.log('staffing-ui-regressions: OK (uncertainty and single initial evaluation)');
} finally { rmSync(dir,{recursive:true,force:true}); }
