import { build } from 'esbuild';
import postcss from 'postcss';
import tailwindcss from 'tailwindcss';
import { chromium, expect } from '@playwright/test';
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
const built = await build({ entryPoints: ['scripts/staffingBrowser.entry.tsx'], bundle: true, write: false, platform: 'browser', format: 'iife', jsx: 'automatic', minify: true, metafile: true, define: { 'process.env.NODE_ENV': '"production"' } });
expect(Object.keys(built.metafile.inputs).some(path => path.includes('integrations/supabase'))).toBe(false);
const css = await postcss([tailwindcss({ config: 'tailwind.config.ts', content: ['src/features/staffing/**/*.{tsx,ts}', 'scripts/staffingBrowser.entry.tsx'] })]).process('@tailwind base; @tailwind components; @tailwind utilities;', { from: undefined });
const html = `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Previsión · demostración sintética</title><style>${css.css}</style></head><body><div id="root"></div><script>${built.outputFiles[0].text.replaceAll('</script', '<\\/script')}</script></body></html>`;
const browser = await chromium.launch({ headless: true });
const errors = [], requests = [], checks = [];
const open = async (width = 1440, mode = '') => {
  const page = await browser.newPage({ viewport: { width, height: width < 500 ? 844 : 1000 } });
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  await page.route('**/*', route => { requests.push(route.request().url()); return route.abort(); });
  await page.setContent(html.replace('<html lang="es">', `<html lang="es" ${mode}>`));
  await expect(page.getByRole('heading', { name: 'Previsión de personal', exact: true })).toBeVisible();
  return page;
};
const overflow = async page => { const size = await page.evaluate(() => ({ document: document.documentElement.scrollWidth, viewport: innerWidth })); expect(size.document).toBeLessThanOrEqual(size.viewport); return size; };
const discard = async (page, accept = true) => { page.once('dialog', dialog => accept ? dialog.accept() : dialog.dismiss()); await page.getByRole('button', { name: 'Descartar cambios', exact: true }).click(); };
try {
  const page = await open();
  await expect(page.locator('h1')).toHaveCount(1);
  await expect(page.getByText('DEMOSTRACIÓN CON DATOS SINTÉTICOS', { exact: false })).toBeVisible();
  const monthTabs = page.locator('[role="tablist"][aria-label="Meses de previsión"] [role="tab"]');
  await expect(monthTabs).toHaveCount(3);

  await expect(page.getByLabel('Periodicidad')).toHaveValue('week');
  await expect(page.getByLabel('Semana de análisis')).toBeVisible();
  await page.getByLabel('Periodicidad').selectOption('month');
  await expect(page.getByLabel('Mes de análisis')).toBeVisible();
  await expect(page.getByLabel('Semana de análisis')).toHaveCount(0);
  await page.getByLabel('Mes de análisis').selectOption('2026-10');
  await expect(page.getByRole('heading', { name: 'octubre', exact: true })).toBeVisible();
  await expect(page.locator('svg g[role="button"][aria-pressed="true"]')).toHaveCount(0);
  await expect(page.locator('[aria-label="Semanas dentro de octubre"] button[aria-pressed="true"]')).toHaveCount(0);
  await page.getByLabel('Periodicidad').selectOption('week');
  await expect(page.getByLabel('Semana de análisis')).toBeVisible();
  await expect(page.getByLabel('Mes de análisis')).toHaveCount(0);
  await page.getByLabel('Semana de análisis').selectOption('2026-10-05');
  await expect(page.getByRole('heading', { name: 'octubre', exact: true })).toBeVisible();
  await page.getByLabel('Semana de análisis').selectOption('2026-09-14');
  await expect(page.getByRole('heading', { name: 'septiembre', exact: true })).toBeVisible();
  await expect(page.locator('[role="tab"]').filter({ hasText: 'Horas de trabajo previsto' })).toHaveCount(3);
  await expect(page.locator('[role="tab"]').filter({ hasText: 'Horas de trabajo posibles' })).toHaveCount(3);
  await expect(page.locator('[role="tab"]').filter({ hasText: 'Equipo actual' })).toHaveCount(3);
  await expect(page.getByText('Capacidad mensual y encaje diario son distintos', { exact: true })).toBeVisible();
  await expect(page.getByText('El total mensual no basta', { exact: true })).toHaveCount(0);
  await expect(page.getByRole('heading', { name: 'septiembre', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Comparar escenarios', exact: true }).click();
  await expect(page.getByRole('dialog', { name: 'Simular cambios' })).toBeVisible();
  await expect(page.getByRole('region', { name: 'Comparación de escenario' })).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).toHaveCount(0);
  checks.push('monthly CTA opens scenario comparison');
  await monthTabs.nth(1).click();
  await expect(page.getByRole('heading', { name: 'octubre', exact: true })).toBeVisible();
  const octoberWeek = page.locator('button').filter({ hasText: '05–11 OCT' }).first();
  await octoberWeek.click();
  await expect(octoberWeek).toHaveAttribute('aria-pressed', 'true');
  await monthTabs.nth(0).click();
  await expect(page.getByRole('heading', { name: 'septiembre', exact: true })).toBeVisible();
  await expect(page.getByLabel('Semana de análisis').locator('option')).toHaveCount(12);
  await expect(page.getByRole('button', { name: 'Parcial: consultar datos y criterios' })).toBeVisible();
  await expect(page.getByText('Propuesta orientativa', { exact: false })).toHaveCount(0);
  expect(await page.locator('svg polyline').getAttribute('points')).toContain(' ');
  expect(await page.locator('svg pattern').count()).toBe(1);
  const weekButton = page.locator('svg [role=button]').nth(3);
  await weekButton.focus(); await page.keyboard.press('Enter');
  await expect(page.getByLabel('Semana de análisis')).toHaveValue('2026-10-05');
  await expect(weekButton).toHaveAttribute('aria-pressed', 'true');
  await page.getByLabel('Semana de análisis').selectOption({ index: 0 });
  const total = await page.getByLabel('Resumen semanal de sede').innerText();
  const bars = page.getByLabel('Barras diarias');
  await expect(bars.getByRole('button')).toHaveCount(7);
  await expect(page.locator('[role="tablist"][aria-label="Vistas de detalle"] [role="tab"]')).toHaveCount(2);
  await expect(page.getByRole('dialog')).toHaveCount(0);
  const dayLabels = await bars.getByRole('button').allTextContents();
  await bars.getByRole('button').nth(1).click();
  await page.getByRole('button', { name: 'Abrir Centro Sur · demo el 15/09' }).click();
  await expect(page.getByRole('tab', { name: 'Centros', exact: true })).toHaveAttribute('aria-selected', 'true');
  await expect(page.getByRole('button', { name: /^Centro Sur · demo, 15\/09:/ })).toHaveAttribute('aria-pressed', 'true');
  await expect(page.getByLabel('Resumen seleccionado')).toContainText('4 h');
  await expect(page.getByLabel('Resumen seleccionado')).toContainText('Sin capacidad atribuida');
  await expect(bars).toHaveCount(0);
  const southColor = await page.getByRole('button', { name: /^Centro Sur · demo, 15\/09:/ }).evaluate(element => getComputedStyle(element).backgroundColor);
  await page.getByLabel('Buscar centro').fill('Sur');
  await expect(page.getByLabel('Mapa de carga por centro').locator('tbody tr')).toHaveCount(1);
  expect(await page.getByRole('button', { name: /^Centro Sur · demo, 15\/09:/ }).evaluate(element => getComputedStyle(element).backgroundColor)).toBe(southColor);
  await page.getByLabel('Buscar centro').fill('');
  await page.getByLabel('Mostrar sin actividad').uncheck();
  await expect(page.getByRole('button', { name: /^Centro sin actividad/ })).toHaveCount(0);
  await page.getByLabel('Mostrar sin actividad').check();
  await expect(page.getByRole('button', { name: /^Centro sin actividad/ })).toHaveCount(7);
  expect(await page.getByLabel('Resumen semanal de sede').innerText()).toBe(total);
  await page.getByRole('button', { name: 'Ver servicios y libranzas' }).click();
  await expect(page.getByRole('dialog')).toContainText('Centro Sur');
  await expect(page.getByRole('dialog')).not.toContainText('Centro Norte');
  await page.keyboard.press('Escape');
  await page.getByRole('tab', { name: 'Días', exact: true }).click();
  expect(await bars.getByRole('button').allTextContents()).toEqual(dayLabels);
  await expect(bars.getByRole('button').nth(1)).toHaveAttribute('aria-pressed', 'true');
  await page.getByRole('tab', { name: 'Días', exact: true }).focus(); await page.keyboard.press('End');
  await expect(page.getByRole('tab', { name: 'Centros', exact: true })).toBeFocused();
  await page.getByRole('button', { name: 'Ver equipo' }).click();
  await expect(page.getByRole('heading', { name: 'Colaboradores habituales' })).toBeVisible();
  await page.keyboard.press('Escape');
  checks.push('7 daily bar rows', 'exclusive views', 'origin to exact center/day', 'site totals invariant', 'known load heatmap', 'details lazy', 'tabs keyboard/team');
  await page.getByRole('button', { name: 'Simular cambios', exact: true }).click();
  await expect(page.getByRole('dialog', { name: 'Simular cambios' })).toBeVisible();
  const panelRect = await page.getByRole('dialog').boundingBox();
  expect(panelRect.y, 'side panel must start at viewport top').toBe(0);
  await expect(page.getByRole('button', { name: 'Cerrar Simular cambios' })).toBeFocused();
  await page.keyboard.press('Shift+Tab');
  expect(await page.evaluate(() => !!document.activeElement?.closest('dialog'))).toBe(true);
  await page.getByRole('button', { name: 'Añadir refuerzo hipotético' }).click();
  await expect(page.getByLabel('Horas de Refuerzo hipotético 1', { exact: true })).toHaveValue('15');
  await discard(page, false);
  await expect(page.getByLabel('Horas de Refuerzo hipotético 1', { exact: true })).toHaveValue('15');
  await discard(page);
  await expect(page.getByLabel('Horas de Refuerzo hipotético 1', { exact: true })).toHaveCount(0);
  await page.getByLabel('Buscar persona').fill('demo 1');
  await expect(page.locator('fieldset')).toHaveCount(1);
  await page.getByLabel('Horas de Operario demo 1', { exact: true }).fill('0');
  await expect(page.getByRole('region', { name: 'Comparación de escenario' })).toContainText('Contratadas:');
  await discard(page);
  await expect(page.getByLabel('Horas de Operario demo 1', { exact: true })).toHaveValue('20');
  await page.getByLabel('Buscar persona').fill('');
  await page.getByLabel('Simular ausencia').selectOption('w0');
  await expect(page.getByLabel('Resumen de cambios')).toContainText('1 ausencia');
  await discard(page);
  await page.getByLabel('Libranza flexible de Operario demo 1', { exact: true }).check();
  await page.getByLabel('Último día activo de Operario demo 1', { exact: true }).fill('2026-09-15');
  await expect(page.getByLabel('Resumen de cambios')).toContainText('fin de actividad');
  await discard(page);
  await expect(page.getByLabel('Coste de Operario demo 8', { exact: true })).toHaveCount(0);
  await page.getByLabel('Horas de Operario demo 8', { exact: true }).fill('0');
  const comparison = page.getByRole('region', { name: 'Comparación de escenario' });
  await expect(comparison.locator('p').filter({ hasText: 'Capacidad de autónomos' })).toContainText('→ 0 h');
  const contract = (await comparison.locator('p').filter({ hasText: /^Contratadas:/ }).innerText()).replace('Contratadas:', '').split('→').map(value => value.trim());
  expect(contract[0]).toBe(contract[1]);
  await discard(page);
  await page.getByText('Ajustes', { exact: true }).click();
  await page.getByLabel('Margen a una semana').fill('40');
  await expect(page.getByRole('region', { name: 'Comparación de escenario' })).toContainText('Base → escenario');
  await discard(page);
  await expect(page.getByLabel('Margen a una semana')).toHaveValue('20');
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Simular cambios', exact: true })).toBeFocused();
  checks.push('reinforcement', 'discard accept/cancel', 'search/person hours', 'absence/full horizon', 'rest/end date', 'collaborator not contract', 'demand reset/base comparison', 'modal focus/escape');
  await page.getByRole('tab', { name: 'Días', exact: true }).click();
  await page.screenshot({ path: resolve('../staffing-days-centers-desktop.png'), fullPage: true });
  await page.screenshot({ path: resolve('../staffing-monthly-desktop.png'), fullPage: true });
  await page.getByLabel('Análisis diario y centros').screenshot({ path: resolve('../staffing-days-centers-desktop-detail.png') });
  await page.getByRole('button', { name: 'Datos y criterios', exact: true }).click();
  await expect(page.getByRole('dialog', { name: 'Datos y criterios' })).toContainText('capacidad es potencial');
  await page.keyboard.press('Escape');
  await page.setViewportSize({ width: 390, height: 844 });
  const mobileOverflow = await overflow(page);
  await page.screenshot({ path: resolve('../staffing-monthly-mobile.png'), fullPage: true });
  await page.screenshot({ path: resolve('../staffing-days-centers-mobile.png'), fullPage: true });
  await page.getByRole('tab', { name: 'Centros', exact: true }).click();
  await page.getByLabel('Buscar centro').fill('');
  await overflow(page);
  await page.getByLabel('Análisis diario y centros').screenshot({ path: resolve('../staffing-days-centers-mobile-heatmap.png') });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByLabel('Análisis diario y centros').screenshot({ path: resolve('../staffing-days-centers-desktop-heatmap.png') });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('tab', { name: 'Días', exact: true }).click();
  await page.getByRole('button', { name: 'Simular cambios', exact: true }).click();
  await page.getByLabel('Horas de Operario demo 1', { exact: true }).fill('15');
  await overflow(page);
  const dialogOverflow = await page.getByRole('dialog').evaluate(element => ({ width: element.clientWidth, scroll: element.scrollWidth }));
  expect(dialogOverflow.scroll).toBeLessThanOrEqual(dialogOverflow.width);
  await page.getByRole('dialog').evaluate(element => { element.scrollTop = 0; });
  await page.screenshot({ path: resolve('../staffing-redesign-scenario-mobile.png') });
  await page.keyboard.press('Escape');
  await expect(page.getByText('Escenario modificado · sin guardar', { exact: true })).toBeVisible();
  for (const mode of ['empty', 'error']) {
    const state = await open(390, `data-staffing-mode="${mode}"`);
    await expect(mode === 'empty' ? state.getByRole('status') : state.getByRole('alert')).toContainText(mode === 'empty' ? 'Sin datos suficientes' : 'No se pudieron leer');
    await expect(state.getByRole('button', { name: 'Parcial: consultar datos y criterios' })).toBeVisible();
    await overflow(state);
    await state.screenshot({ path: resolve(`../staffing-redesign-${mode}.png`), fullPage: true });
  }
  const shortHorizon = await open(390, 'data-staffing-mode="short"');
  const shortMonthTabs = shortHorizon.locator('[role="tablist"][aria-label="Meses de previsión"] [role="tab"]');
  await shortMonthTabs.nth(2).click();
  await expect(shortHorizon.getByRole('heading', { name: 'noviembre', exact: true })).toBeVisible();
  await expect(shortHorizon.getByRole('status')).toContainText('Sin semanas/datos calculables para este mes');
  await shortHorizon.getByLabel('Periodicidad').selectOption('week');
  await expect(shortHorizon.getByLabel('Semana de análisis')).toBeDisabled();
  await expect(shortHorizon.getByLabel('Semana de análisis')).toHaveValue('');
  await expect(shortHorizon.getByRole('button', { name: 'Comparar escenarios', exact: true })).toBeDisabled();
  await expect(shortHorizon.getByRole('button', { name: 'Abrir comparación diaria y mapa de centros →', exact: true })).toBeDisabled();
  await expect(shortHorizon.locator('[aria-label="Semanas dentro de noviembre"] div.grid').getByRole('button')).toHaveCount(6);
  await expect(shortHorizon.locator('[aria-label="Semanas dentro de noviembre"] div.grid').getByRole('button').first()).toBeDisabled();
  await expect(shortHorizon.getByLabel('Análisis diario y centros')).toHaveCount(0);
  checks.push('empty future month keeps week empty and disables detail actions');
  await overflow(shortHorizon);
  const stress = await open(390, 'data-staffing-stress="true"');
  const many = await open(390, 'data-staffing-mode="many"');
  await expect(many.getByRole('button', { name: /^Abrir Centro/ })).toHaveCount(7);
  await many.getByRole('tab', { name: 'Centros', exact: true }).click();
  const map = many.getByLabel('Mapa de carga por centro');
  await expect(map.locator('tbody tr')).toHaveCount(7);
  await expect(many.getByLabel('Páginas de centros')).toContainText('40 centros · 1/6');
  await many.getByLabel('Páginas de centros').getByRole('button', { name: 'Siguiente' }).click();
  await expect(many.getByLabel('Páginas de centros')).toContainText('2/6');
  await many.getByLabel('Buscar centro').fill('prueba 00');
  await expect(map.locator('tbody tr')).toHaveCount(1);
  await expect(many.getByLabel('Páginas de centros')).toContainText('1/1');
  await map.evaluate(element => { element.scrollLeft = element.scrollWidth; });
  expect(await map.evaluate(element => element.scrollLeft)).toBeGreaterThan(0);
  await map.getByRole('button', { name: /20\/09:/ }).click();
  await expect(many.getByLabel('Resumen seleccionado')).toContainText('20/09');
  await many.getByRole('tab', { name: 'Días', exact: true }).click();
  await expect(many.getByLabel('Barras diarias').getByRole('button').last()).toHaveAttribute('aria-pressed', 'true');
  await many.getByLabel('Páginas de origen').getByRole('button', { name: 'Siguiente' }).click();
  await many.getByRole('button', { name: /^Abrir Centro/ }).last().click();
  await expect(map.locator('button[aria-pressed="true"]')).toHaveCount(1);
  await expect(map.locator('button[aria-pressed="true"]')).toBeFocused();
  const linkedCell = await map.locator('button[aria-pressed="true"]').boundingBox();
  const mapRect = await map.boundingBox();
  expect(linkedCell.x + linkedCell.width).toBeLessThanOrEqual(mapRect.x + mapRect.width + 1);
  await many.getByLabel('Periodicidad').selectOption('week');
  await many.getByLabel('Semana de análisis').selectOption({ index: 1 });
  await expect(many.getByLabel('Resumen seleccionado')).toContainText('21/09');
  await overflow(many);
  const duplicate = await open(390, 'data-staffing-mode="duplicate"');
  await expect(duplicate.getByRole('button', { name: /^Parcial: consultar datos y criterios/ })).toBeVisible();
  await duplicate.getByRole('button', { name: /^Parcial: consultar datos y criterios/ }).click();
  await expect(duplicate.getByRole('dialog', { name: 'Datos y criterios' })).toContainText('Día duplicado');
  await duplicate.keyboard.press('Escape');
  await expect(duplicate.getByLabel('Resumen seleccionado')).toContainText('Carga por centro no conciliada');
  await duplicate.getByRole('button', { name: /^Abrir Centro Norte/ }).click();
  await expect(duplicate.getByLabel('Resumen seleccionado')).not.toContainText('4 h');
  await overflow(duplicate);
  checks.push('40 centers bounded pagination and search reset', 'origin pagination deep link visible', 'mobile internal map scroll to Sunday', 'week selection fallback', 'duplicate input not presented as reconciled load', 'monthly duplicate diagnostic panel');
  expect(await stress.locator('html').getAttribute('data-compute-count')).toBe('1');
  await expect(stress.getByLabel('Periodicidad')).toHaveValue('week');
  await expect(stress.getByLabel('Semana de análisis').locator('option')).toHaveCount(24);
  await stress.getByRole('button', { name: 'Simular cambios', exact: true }).click();
  await stress.getByLabel('Horas de Operario demo 1', { exact: true }).fill('20');
  await discard(stress);
  await expect(stress.getByLabel('Horas de Operario demo 1', { exact: true })).toHaveValue('40');
  const perf = await stress.evaluate(() => ({ maxComputeMs: Number(document.documentElement.dataset.maxComputeMs), evaluations: Number(document.documentElement.dataset.computeCount), incomplete: document.documentElement.dataset.computeIncomplete }));
  expect(perf.maxComputeMs).toBeLessThan(500);
  expect(errors).toEqual([]); expect(requests).toEqual([]);
  writeFileSync(resolve('../staffing-days-centers-demo.html'), html);
  const report = { result: 'PASS', scope: 'real dashboard/engine synthetic only, not authenticated production', viewports: [1440, 390], checks, mobileOverflow, dialogOverflow, networkRequests: requests.length, consoleErrors: errors.length, stress: { weeks: 24, workers: 20, services: 2016, ...perf } };
  writeFileSync(resolve('../staffing-days-centers-browser.json'), JSON.stringify(report, null, 2));
  console.log(JSON.stringify(report, null, 2));
} finally { await browser.close(); }
await import('./staffingPageBrowserTest.mjs');
