import { build } from 'esbuild';
import postcss from 'postcss';
import tailwindcss from 'tailwindcss';
import { chromium, expect } from '@playwright/test';
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
const built = await build({ entryPoints: ['scripts/staffingBrowser.entry.tsx'], bundle: true, write: false, platform: 'browser', format: 'iife', jsx: 'automatic', minify: true, metafile: true, define: { 'process.env.NODE_ENV': '"production"' } });
expect(Object.keys(built.metafile.inputs).some(path => path.includes('integrations/supabase'))).toBe(false);
const css = await postcss([tailwindcss({ config: resolve('tailwind.config.ts'), content: ['src/features/staffing/**/*.{tsx,ts}', 'scripts/staffingBrowser.entry.tsx'] })]).process('@tailwind base; @tailwind components; @tailwind utilities;', { from: undefined });
const html = `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${css.css}</style></head><body><div id="root"></div><script>${built.outputFiles[0].text.replaceAll('</script','<\\/script')}</script></body></html>`;
const browser = await chromium.launch({ headless: true });
const errors = [], requests = [];
const open = async (width = 1440, attributes = '') => { const page = await browser.newPage({ viewport: { width, height: width < 500 ? 844 : 1000 } }); page.on('pageerror', error => errors.push(error.message)); page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); }); await page.route('**/*', route => { requests.push(route.request().url()); return route.abort(); }); await page.setContent(html.replace('<html lang="es">', `<html lang="es" ${attributes}>`)); await expect(page.getByRole('heading', { name: 'Previsión de personal', exact: true })).toBeVisible(); return page; };
try {
  const page = await open();
  const sectionTabs = page.locator('button[id^="staffing-section-tab-"]');
  await expect(sectionTabs).toHaveCount(3);
  await expect(sectionTabs.first()).toHaveAttribute('aria-current', 'page');
  await sectionTabs.first().focus(); await page.keyboard.press('ArrowRight');
  await expect(sectionTabs.nth(1)).toBeFocused();
  await expect(sectionTabs.nth(1)).toHaveAttribute('aria-current', 'page');
  await page.keyboard.press('End');
  await expect(sectionTabs.nth(2)).toBeFocused();
  await page.keyboard.press('Home');
  await expect(sectionTabs.first()).toBeFocused();
  const order = await page.locator('body').innerText();
  for (const [before, after] of [['Qué necesita atención', 'Trabajo y capacidad por semana'], ['Trabajo y capacidad por semana', 'Opciones para esta semana'], ['Opciones para esta semana', 'Equipo y carga simulada'], ['Equipo y carga simulada', 'Comparación de escenarios']]) expect(order.indexOf(before), `${before} exists`).toBeGreaterThanOrEqual(0), expect(order.indexOf(after), `${after} exists`).toBeGreaterThan(order.indexOf(before));
  await expect(page.getByRole('heading', { name: 'Trabajo y capacidad por semana', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Semanas', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await expect(page.getByRole('button', { name: 'Meses', exact: true })).toBeVisible();
  await expect(page.locator('svg pattern')).toHaveCount(1);
  await expect(page.locator('svg polyline')).toHaveCount(1);
  await expect(page.getByText('Desliza para ver más semanas →', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Meses', exact: true }).click();
  const selectedPeriod = page.locator('svg [aria-pressed="true"]').first();
  await expect(selectedPeriod).toBeVisible();
  expect(await selectedPeriod.getAttribute('aria-label')).not.toContain('28/09');
  const octoberPeriod = page.getByRole('button', { name: /octubre/i }).first();
  if (await octoberPeriod.count()) { await octoberPeriod.click(); await expect(page.getByLabel('Semana de análisis')).toHaveValue('2026-10-05'); }
  await page.getByRole('button', { name: 'Semanas', exact: true }).click();
  await expect(page.getByLabel('Barras diarias').getByRole('button')).toHaveCount(7);
  await expect(page.getByRole('columnheader', { name: 'Puede trabajar' }).first()).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'Limpiezas asignadas' }).first()).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'Horas libres' }).first()).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'Aviso' }).first()).toBeVisible();
  await expect(page.locator('p:visible', { hasText: 'de trabajo conocido sin repartir' }).first()).toBeVisible();
  await expect(page.getByRole('region', { name: 'Comparación de escenarios' })).toContainText('Trabajo sin repartir');
  const capacities = await page.getByLabel('Barras diarias').getByRole('button').evaluateAll(buttons => buttons.map(button => Number((button.getAttribute('aria-label')?.match(/el equipo puede hacer ([\d,.]+) h/)?.[1] || '0').replace(',', '.'))));
  const weeklyCapacity = Number((await page.getByLabel('Resumen semanal de sede').innerText()).match(/Horas del equipo\s+([\d,.]+) h/)?.[1]?.replace(',', '.') || '0');
  expect(Math.abs(capacities.reduce((sum, value) => sum + value, 0) - weeklyCapacity)).toBeLessThan(1);
  await page.getByRole('button', { name: /Probar refuerzo/ }).click();
  await expect(page.getByRole('dialog', { name: 'Simular cambios' })).toBeVisible();
  await expect(page.getByRole('dialog')).toContainText('Escenario base');
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('button', { name: 'Escenarios', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Prueba una alternativa antes de decidir', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Previsión', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Comparación de escenarios', exact: true })).toBeVisible();
  const mobile = await open(390);
  const size = await mobile.evaluate(() => ({ document: document.documentElement.scrollWidth, viewport: innerWidth }));
  expect(size.document).toBeLessThanOrEqual(size.viewport);
  await expect(mobile.getByText('Desliza para ver más semanas →', { exact: true })).toBeVisible();
  const partial = await open(390, 'data-staffing-mode="error"');
  await expect(partial.getByText('Faltan datos · revisa las fuentes', { exact: true })).toBeVisible();
  await expect(partial.getByRole('alert')).toContainText('incompleta');
  const empty = await open(1440, 'data-staffing-mode="empty"');
  await expect(empty.getByText('Sin datos suficientes:', { exact: false })).toBeVisible();
  const short = await open(1440, 'data-staffing-mode="short"');
  await expect(short.getByLabel('Semana de análisis').locator('option')).toHaveCount(4);
  const many = await open(1440, 'data-staffing-mode="many"');
  await expect(many.getByRole('heading', { name: 'Previsión de personal', exact: true })).toBeVisible();
  const duplicate = await open(1440, 'data-staffing-mode="duplicate"');
  await expect(duplicate.getByRole('button', { name: 'Parcial: consultar datos y criterios' })).toBeVisible();
  const stress = await open(1440, 'data-staffing-stress="true"');
  await expect(stress.getByRole('heading', { name: 'Previsión de personal', exact: true })).toBeVisible();
  expect(Number(await stress.evaluate(() => document.documentElement.dataset.computeCount || '0'))).toBeGreaterThan(0);
  await expect(mobile.getByRole('heading', { name: 'Qué necesita atención', exact: true })).toBeVisible();
  // El resumen ejecutivo sigue al periodo elegido (regresión del selector de fechas).
    await page.getByLabel('Periodicidad').selectOption('month');
    await expect(page.getByRole('article', { name: /^Total de / })).toBeVisible();
    await expect(page.getByRole('article', { name: /^Total de / })).toContainText('semanas');
    await page.getByLabel('Periodicidad').selectOption('period');
    await expect(page.getByRole('article', { name: 'Total del periodo', exact: true })).toBeVisible();
  expect(errors).toEqual([]);
  expect(requests).toEqual([]);
  console.log('staffing-visual-tests: OK (prompt layout, interaction and responsive no-network fixture)');
} finally { await browser.close(); }
