import { build } from 'esbuild';
import postcss from 'postcss';
import tailwindcss from 'tailwindcss';
import { chromium, expect } from '@playwright/test';
import { resolve } from 'node:path';
const built = await build({ entryPoints: ['scripts/staffingBrowser.entry.tsx'], bundle: true, write: false, platform: 'browser', format: 'iife', jsx: 'automatic', minify: true, metafile: true, define: { 'process.env.NODE_ENV': '"production"' }, plugins: [{ name: 'offline-sede-selector', setup(plugin) { plugin.onResolve({ filter: /^@\/components\/sede\/SedeSelector$/ }, () => ({ path: 'staffing-sede-selector', namespace: 'fixture' })); plugin.onLoad({ filter: /.*/, namespace: 'fixture' }, () => ({ contents: 'export const SedeSelector=()=>null;', loader: 'js' })); } }] });
expect(Object.keys(built.metafile.inputs).some(path => path.includes('integrations/supabase'))).toBe(false);
const css = await postcss([tailwindcss({ config: resolve('tailwind.config.ts'), content: ['src/features/staffing/**/*.{tsx,ts}', 'scripts/staffingBrowser.entry.tsx'] })]).process('@tailwind base; @tailwind components; @tailwind utilities;', { from: undefined });
const html = `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${css.css}</style></head><body><div id="root"></div><script>${built.outputFiles[0].text.replaceAll('</script','<\\/script')}</script></body></html>`;
const browser = await chromium.launch({ headless: true });
const errors = [], requests = [];
const open = async (width = 1440, attributes = '') => { const page = await browser.newPage({ viewport: { width, height: width < 500 ? 844 : 1000 } }); page.on('pageerror', error => errors.push(error.message)); page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); }); await page.route('**/*', route => { requests.push(route.request().url()); return route.abort(); }); await page.setContent(html.replace('<html lang="es">', `<html lang="es" ${attributes}>`)); await expect(page.getByRole('heading', { name: 'Previsión de personal', exact: true })).toBeVisible(); return page; };
try {
  const page = await open();
  await expect(page.getByRole('heading', { name: 'Trabajo previsto vs. capacidad del equipo', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Resumen por semana', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Mensual', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await page.getByRole('button', { name: 'Semanal', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Semanal', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await page.getByLabel('Centro').selectOption('north');
  await expect(page.getByLabel('Centro')).toHaveValue('north');
  await page.getByRole('button', { name: /Sem\. / }).first().click();
  await expect(page.getByRole('heading', { name: /Semana/ }).first()).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Carga diaria vs. capacidad', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Qué necesita atención', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Detalle diario de la semana', exact: true })).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'Tareas', exact: true })).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'Capacidad (h)', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Ver candidatos', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Ver candidatos', exact: true }).click();
  await expect(page.getByRole('heading', { name: /Candidatos para/ })).toBeVisible();
  await expect(page.getByText('Selecciona un candidato para revisar su disponibilidad.', { exact: false })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Abrir calendario diario', exact: true })).toBeVisible();
  await expect(page.getByText('Suplentes', { exact: true }).first()).toBeVisible();
  await expect(page.getByText('Backup', { exact: true }).first()).toBeVisible();
  await page.getByRole('button', { name: /Volver al detalle semanal/ }).click();
  await expect(page.getByRole('heading', { name: 'Detalle diario de la semana', exact: true })).toBeVisible();
  const mobile = await open(390);
  const size = await mobile.evaluate(() => ({ document: document.documentElement.scrollWidth, viewport: innerWidth }));
  expect(size.document).toBeLessThanOrEqual(size.viewport + 1);
  const partial = await open(1440, 'data-staffing-mode="error"');
  await expect(partial.getByRole('alert')).toContainText('incompleta');
  const empty = await open(1440, 'data-staffing-mode="empty"');
  await expect(empty.getByText('No hay datos para dibujar el periodo.', { exact: true })).toBeVisible();
  expect(errors).toEqual([]);
  expect(requests).toEqual([]);
  console.log('staffing-visual-tests: OK (resumen, detalle semanal, candidatos y responsive sin red)');
} finally { await browser.close(); }