import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const app = readFileSync('src/App.tsx', 'utf8');
const page = readFileSync('src/pages/Supervision.tsx', 'utf8');
const domain = readFileSync('src/features/supervision/domain.ts', 'utf8');
const migration = readFileSync('supabase/migrations/20260814120000_supervision_quality_mvp.sql', 'utf8');
const mediaMigration = readFileSync('supabase/migrations/20260814122000_supervision_media_scope.sql', 'utf8');
const hardeningMigration = readFileSync('supabase/migrations/20260815210000_supervision_rls_hardening.sql', 'utf8');
const closedRouteMigration = readFileSync('supabase/migrations/20260815220000_supervision_closed_route_guard.sql', 'utf8');
const incidentEmailFunction = readFileSync('supabase/functions/send-supervision-incident-email/index.ts', 'utf8');
const operationalMigration = readFileSync('supabase/migrations/20260815230000_supervision_operational_guards.sql', 'utf8');
const auditMigration = readFileSync('supabase/migrations/20260815232000_supervision_audit_immutability.sql', 'utf8');
const notificationMigration = readFileSync('supabase/migrations/20260815223000_supervision_incident_notification_guard.sql', 'utf8');
const dailyReportFunction = readFileSync('supabase/functions/send-supervision-daily-report/index.ts', 'utf8');
const storage = readFileSync('src/features/supervision/supervisionStorage.ts', 'utf8');
const workspaceHook = readFileSync('src/features/supervision/useSupervisionWorkspace.ts', 'utf8');
const taskStorageWrapper = readFileSync('src/services/taskStorage.ts', 'utf8');
const taskStorage = readFileSync('src/services/storage/taskStorage.ts', 'utf8');
const queue = readFileSync('src/features/supervision/offlineQueue.ts', 'utf8');
const incidentFunction = readFileSync('supabase/functions/send-supervision-incident-email/index.ts', 'utf8');
const auth = readFileSync('src/hooks/useAuth.ts', 'utf8');
const rolePermissions = readFileSync('src/hooks/useRolePermissions.ts', 'utf8');
const modeSwitcher = readFileSync('src/components/auth/OperationalModeSwitcher.tsx', 'utf8');
const optimizedTasks = readFileSync('src/hooks/useOptimizedTasks.ts', 'utf8');
const dashboardSidebar = readFileSync('src/components/dashboard/DashboardSidebar.tsx', 'utf8');
const mobileDashboardSidebar = readFileSync('src/components/dashboard/MobileDashboardSidebar.tsx', 'utf8');
const buildingAgenda = readFileSync('src/features/supervision/buildingAgenda.ts', 'utf8');
const buildingSupervisionStorage = readFileSync('src/features/supervision/buildingSupervisionStorage.ts', 'utf8');
const supervisionBuildingsPage = readFileSync('src/pages/SupervisionBuildings.tsx', 'utf8');
const buildingAssignmentsMigration = readFileSync('supabase/migrations/20260824130000_supervision_building_assignments.sql', 'utf8');
const buildingRoutesMigration = readFileSync('supabase/migrations/20260824131000_supervision_building_routes.sql', 'utf8');
const workItemsMigration = readFileSync('supabase/migrations/20260824140000_supervision_work_items.sql', 'utf8');
const routeAssignmentGuardMigration = readFileSync('supabase/migrations/20260824141000_supervision_route_assignment_guard.sql', 'utf8');
const stockLocationsMigration = readFileSync('supabase/migrations/20260824150000_supervision_stock_locations_checks.sql', 'utf8');
const stockDeltaFixMigration = readFileSync('supabase/migrations/20260824151000_supervision_stock_count_delta_fix.sql', 'utf8');
assert.match(app, /path=\"\/supervision\"/);
assert.match(app, /excludedRoles=\{\['supervisor'\]\}/g);
assert.match(dashboardSidebar, /title: 'Supervisión y calidad'/);
assert.match(dashboardSidebar, /permission: 'workers-forecast'/);
assert.match(dashboardSidebar, /case 'workers-forecast': return canAccessModule\('workers'\) && !isSupervisor\(\)/);
assert.match(mobileDashboardSidebar, /title: 'Supervisión y calidad'/);
assert.match(supervisionBuildingsPage, /Mi supervisión/);
assert.match(supervisionBuildingsPage, /BuildingSupervisionCard/);
assert.match(supervisionBuildingsPage, /ApartmentReviewSheet/);
assert.match(buildingAgenda, /buildBuildingSupervisionAgenda/);
assert.match(buildingAgenda, /returned_for_rework/);
assert.match(buildingSupervisionStorage, /supervision_building_supervisors/);
assert.match(buildingSupervisionStorage, /ensureAutomaticBuildingRoute/);
assert.match(buildingAssignmentsMigration, /supervision_building_supervisors/);
assert.match(buildingAssignmentsMigration, /supervision assignee must have supervisor role/);
assert.match(buildingAssignmentsMigration, /user_has_sede_access/);
assert.match(buildingRoutesMigration, /property_group_id/);
assert.match(buildingRoutesMigration, /supervision_routes_building_date_key/);
assert.match(workItemsMigration, /supervision_building_policies/);
assert.match(workItemsMigration, /supervision_work_items/);
assert.match(workItemsMigration, /generation_key TEXT NOT NULL UNIQUE/);
assert.match(workItemsMigration, /upsert_supervision_work_items/);
assert.match(workItemsMigration, /update_supervision_work_item_status/);
assert.match(workItemsMigration, /status IN \('pending', 'in_progress', 'completed', 'deferred', 'blocked', 'cancelled'\)/);
assert.match(routeAssignmentGuardMigration, /supervision_user_has_building_assignment/);
assert.match(stockLocationsMigration, /property_group_id UUID REFERENCES public\.property_groups/);
assert.match(stockLocationsMigration, /supervision_stock_checks/);
assert.match(stockLocationsMigration, /supervision_stock_check_lines/);
assert.match(stockLocationsMigration, /begin_supervision_stock_check/);
assert.match(stockLocationsMigration, /complete_supervision_stock_check/);
assert.match(stockLocationsMigration, /stock_warehouses_supervisor_read_scoped/);
assert.match(stockLocationsMigration, /stock_levels_supervisor_read_scoped/);
assert.match(stockDeltaFixMigration, /physical_delta/);
assert.match(stockDeltaFixMigration, /physical_quantity/);
assert.match(page, /Supervisión y calidad/);
assert.match(page, /Devolver para repaso/);
assert.match(page, /Fotos opcionales/);
assert.match(page, /formatMadridDate/);
assert.doesNotMatch(page, /new Date\(\)\.toISOString\(\)\.slice\(0, 10\)/);
assert.match(page, /Cobertura de revisión/);
assert.match(page, /Añade paradas y usa las flechas/);
assert.match(page, /Subir \$\{stopLabel\(stop\)\}/);
assert.match(page, /Bajar \$\{stopLabel\(stop\)\}/);
assert.match(domain, /calculateSupervisionMetrics/);
assert.match(domain, /Sin próxima entrada conocida/);
assert.match(page, /jsPDF/);
assert.match(storage, /operation === 'upload'/);
assert.match(storage, /function projectTaskForSupervision/);
assert.match(storage, /return tasks\.map\(projectTaskForSupervision\)/);
assert.match(taskStorageWrapper, /getTasksForSupervision: async \(options/);
assert.match(taskStorageWrapper, /baseTaskStorage\.getTasksForSupervision\(options\)/);
assert.match(storage, /export async function reorderStop/);
assert.match(storage, /knownStops: SupervisionStop\[\] = \[\]/);
assert.match(storage, /writeLocal\(sedeId, date, remoteResult\.value\)/);
assert.match(storage, /code === '42P01'/);
assert.doesNotMatch(storage, /message\.includes\('supervision_'\)/);
assert.match(storage, /db\.rpc\('reorder_supervision_stop'/);
assert.match(queue, /operation: .*'rpc'/);
assert.match(storage, /function: 'reorder_supervision_stop'/);
const supervisionProjection = storage.slice(storage.indexOf('function projectTaskForSupervision'), storage.indexOf('export async function getSupervisionTasks'));
const supervisionTaskQuery = taskStorage.slice(taskStorage.indexOf('async getTasksForSupervision'), taskStorage.indexOf('// Nuevo método para reportes'));
assert.doesNotMatch(supervisionProjection, /cost:|paymentMethod:|extraordinaryClient|clienteId/);
assert.match(supervisionTaskQuery, /\.select\(`/);
assert.doesNotMatch(supervisionTaskQuery, /\.select\(`\s*\*,/);
assert.doesNotMatch(supervisionTaskQuery, /coste|metodo_pago|cliente_id|extraordinary_client/i);
assert.match(queue, /entity: .*photo/);
assert.match(queue, /ownerUserId: string/);
assert.match(queue, /setSupervisionQueueOwner/);
assert.match(queue, /item\.ownerUserId === ownerUserId/);
assert.match(queue, /FALLBACK_PREFIX/);
assert.match(storage, /getSupervisionQueueOwner/);
assert.match(workspaceHook, /\['supervision-workspace', userId, sedeId, date\]/);
assert.match(workspaceHook, /\['supervision-tasks', userId, sedeId, date\]/);
assert.match(workspaceHook, /setSupervisionQueueOwner\(userId\)/);
assert.match(incidentFunction, /SUPABASE_ANON_KEY/);
assert.match(incidentFunction, /isServiceRoleCall/);
assert.match(mediaMigration, /supervision_review_media/);
assert.match(mediaMigration, /storage\.foldername/);
assert.match(hardeningMigration, /supervision_user_can_access_sede/);
assert.match(hardeningMigration, /user_has_role\('supervisor'/);
assert.match(hardeningMigration, /REVOKE ALL ON TABLE/);
assert.match(hardeningMigration, /FROM anon, authenticated/);
assert.doesNotMatch(hardeningMigration, /CREATE POLICY supervision_.* FOR ALL/);
assert.match(hardeningMigration, /trg_validate_supervision_review_route/);
assert.match(hardeningMigration, /trg_validate_supervision_incident_links/);
assert.match(hardeningMigration, /trg_validate_supervision_media_sede/);
assert.match(hardeningMigration, /trg_validate_supervision_daily_report_sede/);
assert.match(closedRouteMigration, /supervision route is completed and read-only/);
assert.match(closedRouteMigration, /trg_supervision_stops_open_route/);
assert.match(closedRouteMigration, /trg_supervision_reviews_open_route/);
assert.match(closedRouteMigration, /trg_supervision_incidents_open_route/);
assert.match(closedRouteMigration, /trg_supervision_reservations_open_route/);
assert.match(closedRouteMigration, /trg_supervision_media_open_route/);
assert.match(operationalMigration, /supervision_daily_report_runs/);
assert.match(operationalMigration, /claim_supervision_daily_report/);
assert.match(operationalMigration, /set_supervision_actor_from_auth/);
assert.match(operationalMigration, /file_size_limit = 10 \* 1024 \* 1024/);
assert.match(operationalMigration, /supervision_storage_object_matches_review/);
assert.match(operationalMigration, /UNIQUE \(route_id, report_date\)/);
assert.match(dailyReportFunction, /no routes for date/);
assert.match(dailyReportFunction, /claim_supervision_daily_report/);
assert.match(dailyReportFunction, /status: 'sent'/);
assert.match(dailyReportFunction, /route_id,report_date/);
assert.match(auditMigration, /REVOKE INSERT, UPDATE, DELETE ON TABLE public\.supervision_daily_reports/);
assert.match(auditMigration, /preserve_supervision_audit_fields/);
assert.match(auditMigration, /trg_supervision_reviews_audit_immutable/);
assert.match(auditMigration, /trg_supervision_incidents_audit_immutable/);
assert.match(notificationMigration, /notification_sent_at/);
assert.match(notificationMigration, /notification_message_id/);
assert.match(incidentEmailFunction, /callerHasOperationalRole/);
assert.match(incidentEmailFunction, /Only high or critical incidents trigger immediate email/);
assert.match(incidentEmailFunction, /notification_sent_at: 'is.null'/);
assert.match(incidentEmailFunction, /incident notification already sent/);
assert.match(migration, /supervision_routes/);
assert.match(migration, /supervision_reviews/);
assert.match(migration, /supervision_incidents/);
assert.match(migration, /user_has_sede_access/);
assert.match(auth, /userRoles: AppRole\[\]/);
assert.match(auth, /operationalMode: OperationalMode/);
assert.match(rolePermissions, /getEffectiveRole/);
assert.match(modeSwitcher, /aria-pressed=\{isActive\}/);
assert.match(modeSwitcher, /Modo operativo/);
assert.match(optimizedTasks, /const cleanerView = isCleaner\(\)/);
assert.doesNotMatch(optimizedTasks, /userRole === 'cleaner'/);
console.log('supervision-ui-contract-tests: OK');
