import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const app = readFileSync('src/App.tsx', 'utf8');
const page = readFileSync('src/pages/Supervision.tsx', 'utf8');
const domain = readFileSync('src/features/supervision/domain.ts', 'utf8');
const migration = readFileSync('supabase/migrations/20260814120000_supervision_quality_mvp.sql', 'utf8');
const mediaMigration = readFileSync('supabase/migrations/20260814122000_supervision_media_scope.sql', 'utf8');
const hardeningMigration = readFileSync('supabase/migrations/20260815210000_supervision_rls_hardening.sql', 'utf8');
const closedRouteMigration = readFileSync('supabase/migrations/20260815220000_supervision_closed_route_guard.sql', 'utf8');
const incidentEmailFunction = readFileSync('supabase/functions/send-supervision-incident-email/index.ts', 'utf8');
const notificationMigration = readFileSync('supabase/migrations/20260815223000_supervision_incident_notification_guard.sql', 'utf8');
const storage = readFileSync('src/features/supervision/supervisionStorage.ts', 'utf8');
const taskStorageWrapper = readFileSync('src/services/taskStorage.ts', 'utf8');
const taskStorage = readFileSync('src/services/storage/taskStorage.ts', 'utf8');
const queue = readFileSync('src/features/supervision/offlineQueue.ts', 'utf8');
const incidentFunction = readFileSync('supabase/functions/send-supervision-incident-email/index.ts', 'utf8');
const auth = readFileSync('src/hooks/useAuth.ts', 'utf8');
const rolePermissions = readFileSync('src/hooks/useRolePermissions.ts', 'utf8');
const modeSwitcher = readFileSync('src/components/auth/OperationalModeSwitcher.tsx', 'utf8');
const optimizedTasks = readFileSync('src/hooks/useOptimizedTasks.ts', 'utf8');
assert.match(app, /path=\"\/supervision\"/);
assert.match(page, /Supervisión y calidad/);
assert.match(page, /Devolver para repaso/);
assert.match(page, /Fotos opcionales/);
assert.match(page, /Cobertura de revisión/);
assert.match(page, /Añade paradas y usa las flechas/);
assert.match(page, /Subir \$\{stopLabel\(stop\)\}/);
assert.match(page, /Bajar \$\{stopLabel\(stop\)\}/);
assert.match(domain, /calculateSupervisionMetrics/);
assert.match(domain, /Sin próxima entrada conocida/);
assert.match(page, /jsPDF/);
assert.match(storage, /operation === 'upload'/);
assert.match(storage, /function projectTaskForSupervision/);
assert.match(storage, /return tasks\.map\(projectTaskForSupervision\)/);
assert.match(taskStorageWrapper, /getTasksForSupervision: async \(options/);
assert.match(taskStorageWrapper, /baseTaskStorage\.getTasksForSupervision\(options\)/);
assert.match(storage, /export async function reorderStop/);
assert.match(storage, /knownStops: SupervisionStop\[\] = \[\]/);
assert.match(storage, /writeLocal\(sedeId, date, remoteResult\.value\)/);
assert.match(storage, /code === '42P01'/);
assert.doesNotMatch(storage, /message\.includes\('supervision_'\)/);
assert.match(storage, /const temporarySequence = -1/);
assert.doesNotMatch(storage, /temporarySequence = -Date\.now\(\)/);
const supervisionProjection = storage.slice(storage.indexOf('function projectTaskForSupervision'), storage.indexOf('export async function getSupervisionTasks'));
const supervisionTaskQuery = taskStorage.slice(taskStorage.indexOf('async getTasksForSupervision'), taskStorage.indexOf('// Nuevo método para reportes'));
assert.doesNotMatch(supervisionProjection, /cost:|paymentMethod:|extraordinaryClient|clienteId/);
assert.match(supervisionTaskQuery, /\.select\(`/);
assert.doesNotMatch(supervisionTaskQuery, /\.select\(`\s*\*,/);
assert.doesNotMatch(supervisionTaskQuery, /coste|metodo_pago|cliente_id|extraordinary_client/i);
assert.match(queue, /entity: .*photo/);
assert.match(incidentFunction, /SUPABASE_ANON_KEY/);
assert.match(incidentFunction, /isServiceRoleCall/);
assert.match(mediaMigration, /supervision_review_media/);
assert.match(mediaMigration, /storage\.foldername/);
assert.match(hardeningMigration, /supervision_user_can_access_sede/);
assert.match(hardeningMigration, /user_has_role\('supervisor'/);
assert.match(hardeningMigration, /REVOKE ALL ON TABLE/);
assert.match(hardeningMigration, /FROM anon, authenticated/);
assert.doesNotMatch(hardeningMigration, /CREATE POLICY supervision_.* FOR ALL/);
assert.match(hardeningMigration, /trg_validate_supervision_review_route/);
assert.match(hardeningMigration, /trg_validate_supervision_incident_links/);
assert.match(hardeningMigration, /trg_validate_supervision_media_sede/);
assert.match(hardeningMigration, /trg_validate_supervision_daily_report_sede/);
assert.match(closedRouteMigration, /supervision route is completed and read-only/);
assert.match(closedRouteMigration, /trg_supervision_stops_open_route/);
assert.match(closedRouteMigration, /trg_supervision_reviews_open_route/);
assert.match(closedRouteMigration, /trg_supervision_incidents_open_route/);
assert.match(closedRouteMigration, /trg_supervision_reservations_open_route/);
assert.match(closedRouteMigration, /trg_supervision_media_open_route/);
assert.match(notificationMigration, /notification_sent_at/);
assert.match(notificationMigration, /notification_message_id/);
assert.match(incidentEmailFunction, /callerHasOperationalRole/);
assert.match(incidentEmailFunction, /Only high or critical incidents trigger immediate email/);
assert.match(incidentEmailFunction, /notification_sent_at: 'is.null'/);
assert.match(incidentEmailFunction, /incident notification already sent/);
assert.match(migration, /supervision_routes/);
assert.match(migration, /supervision_reviews/);
assert.match(migration, /supervision_incidents/);
assert.match(migration, /user_has_sede_access/);
assert.match(auth, /userRoles: AppRole\[\]/);
assert.match(auth, /operationalMode: OperationalMode/);
assert.match(rolePermissions, /getEffectiveRole/);
assert.match(modeSwitcher, /aria-pressed=\{isActive\}/);
assert.match(modeSwitcher, /Modo operativo/);
assert.match(optimizedTasks, /const cleanerView = isCleaner\(\)/);
assert.doesNotMatch(optimizedTasks, /userRole === 'cleaner'/);
console.log('supervision-ui-contract-tests: OK');
