import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {readFileSync} from 'node:fs';
import {PGlite} from '@electric-sql/pglite';

const output=await build({stdin:{contents:`
export * from './supabase/functions/_shared/trashSacks';
export * from './supabase/functions/_shared/laundryBagRequirements';
export * from './src/components/properties/forms/propertyStockConsumption';
export * from './src/features/financial/financialSource';
export * from './src/features/financial/financialModel';
`,resolveDir:process.cwd(),loader:'ts'},bundle:true,platform:'node',format:'esm',write:false});
const api=await import(`data:text/javascript;base64,${Buffer.from(output.outputFiles[0].text).toString('base64')}`);
const product={id:'sack',name:'Sacos de basura 100 L',sku:api.TRASH_SACK_SKU,is_active:true,is_consumable:true,sede_id:'s'};
assert.equal(api.isTrashSack({name:'BOLSAS DE BASURA 30L'}),false);
assert.equal(api.isManagedAmenityProduct(product),false);
assert.equal(api.getLegacyFieldForStockProduct(product),null);
const property={numeroCocinas:2,sede_id:'s',stock_property_consumption_rules:[{is_active:true,quantity_per_cleaning:2,stock_products:product}]};
assert.equal(api.buildDefaultStockConsumptions([product],property).sack,2);
assert.equal(api.buildInitialStockConsumptions([product],[],property).sack,2);
assert.equal(api.buildInitialStockConsumptions([product],[{product_id:'sack',quantity_per_cleaning:0}],property).sack,0);
assert.equal(api.buildInitialStockConsumptions([product],[],null,1).sack,1);
assert.equal(api.trashSackQuantity(property,'2026-10-08'),0);
assert.equal(api.trashSackQuantity(property,'2026-10-09'),2);
assert.equal(api.trashSackQuantity({...property,sede_id:'other'},'2026-10-09'),0);
assert.ok(api.bagRequirementsChanged({amenities:{}},{amenities:{trashSacks100L:2}}));
assert.equal(api.bagRequirementsChanged({amenities:{}},{amenities:{trashSacks100L:0}}),false);
const task={id:'t',date:'2026-10-09',type:'limpieza-turistica',status:'pending',propiedad_id:'p',cliente_id:'c',cleaner_id:'w',cleaner:'Worker',start_time:'10:00',end_time:'11:00',task_assignments:[]};
const prop={id:'p',nombre:'Local test',cliente_id:'c',coste_servicio:50,duracion_servicio:60};
const rules=[{property_id:'p',quantity_per_cleaning:2,product}];
const service=date=>api.buildServices([{...task,date}],[prop],[],[],'2026-10-08',rules)[0];
assert.equal(service('2026-10-08').quantities.trashSack100L,0);
assert.equal(service('2026-10-09').quantities.trashSack100L,2);
assert.equal(api.calculateService(service('2026-10-09'),api.newSettings()).costs.supplies,20);
assert.equal(api.calculateService(service('2026-10-08'),{...api.newSettings(),adjustments:{t:{quantities:{trashSack100L:10}}}}).costs.supplies,0);
assert.equal(api.applyFinanceRules(service('2026-10-09'),{...api.newSettings(),policies:[{clientId:'c',propertyId:'',consumables:false}]}).quantities.trashSack100L,0);
assert.equal(api.applyFinanceRules({...service('2026-10-09'),type:'check-in'},api.newSettings()).quantities.trashSack100L,0);
const oldQuantities=Object.fromEntries(api.QUANTITY_ITEMS.filter(x=>x.id!=='trashSack100L').map(x=>[x.id,0]));
assert.doesNotThrow(()=>api.readSettings({...api.newSettings(),adjustments:{old:{reviewed:true,quantities:oldQuantities}}}));

// Exact opening SQL in disposable PostgreSQL; no network or production data.
const db=new PGlite();
await db.exec(`
create table sedes(id uuid primary key);
create table stock_warehouses(id uuid primary key,sede_id uuid,name text,is_active boolean);
create table properties(id uuid primary key,sede_id uuid,numero_cocinas int);
create table stock_products(id uuid primary key default gen_random_uuid(),sede_id uuid,category_id uuid,name text,sku text,unit_of_measure text,is_consumable boolean,is_active boolean,sort_order int,description text,unique(sede_id,sku));
create table stock_property_consumption_rules(property_id uuid,product_id uuid,warehouse_id uuid,quantity_per_cleaning numeric,is_active boolean,notes text,unique(property_id,product_id));
create table stock_levels(product_id uuid,warehouse_id uuid,current_quantity numeric,cost_per_unit numeric,unique(product_id,warehouse_id));
create table stock_movements(product_id uuid,warehouse_id uuid,movement_type text,quantity numeric,previous_quantity numeric,new_quantity numeric,reason text,unit_cost_at_movement numeric);
insert into sedes values('1e0759ec-5e63-4edd-9dad-e493c715bbba');
insert into stock_warehouses values('af1ff0bf-414a-4d64-8298-06b1a3b7ab82','1e0759ec-5e63-4edd-9dad-e493c715bbba','Simón Bolívar',true);
insert into properties values('00000000-0000-0000-0000-000000000001','1e0759ec-5e63-4edd-9dad-e493c715bbba',2);
`);
const opening=readFileSync('scripts/trashSacksOpening.sql','utf8');
await db.exec(opening);
assert.equal(Number((await db.query('select current_quantity from stock_levels')).rows[0].current_quantity),500);
assert.equal(Number((await db.query('select quantity_per_cleaning from stock_property_consumption_rules')).rows[0].quantity_per_cleaning),2);
await db.exec('update stock_property_consumption_rules set quantity_per_cleaning=0; update stock_levels set current_quantity=499;');
await db.exec(opening);
assert.equal(Number((await db.query('select current_quantity from stock_levels')).rows[0].current_quantity),499);
assert.equal(Number((await db.query('select quantity_per_cleaning from stock_property_consumption_rules')).rows[0].quantity_per_cleaning),0);
assert.equal((await db.query('select * from stock_movements')).rows.length,1);
await db.exec(`
create type stock_item_kind as enum ('laundry','amenity','other');
create table stock_categories(id uuid, name text, kind stock_item_kind);
create table laundry_share_links(id uuid,token text,is_active boolean,expires_at timestamptz,snapshot_task_ids uuid[]);
create table tasks(id uuid,propiedad_id uuid,date date);
alter table properties add column codigo text;
insert into stock_categories values('a76bb11c-aecf-47fc-bb3e-e57f159d708c','CONSUMIBLES','amenity');
insert into tasks values('00000000-0000-0000-0000-000000000008','00000000-0000-0000-0000-000000000001','2026-10-08'),('00000000-0000-0000-0000-000000000009','00000000-0000-0000-0000-000000000001','2026-10-09');
insert into laundry_share_links values(gen_random_uuid(),'local-fixture',true,null,array['00000000-0000-0000-0000-000000000008'::uuid,'00000000-0000-0000-0000-000000000009'::uuid]);
update stock_property_consumption_rules set quantity_per_cleaning=2;
`);
await db.exec(readFileSync('scripts/trashSacksDateGuards.sql','utf8'));
const visible=(await db.query("select * from get_public_laundry_stock_consumptions('local-fixture')")).rows;
assert.equal(visible.length,1);
assert.equal(visible[0].task_id,'00000000-0000-0000-0000-000000000009');
assert.equal(Number(visible[0].quantity),2);
assert.equal((await db.query("select * from get_public_laundry_stock_consumptions('invalid-token')")).rows.length,0);
// Exercise the actual deployed estimate engine with only its clock fixed for tomorrow.
await db.exec(`
alter table tasks add column sede_id uuid default '1e0759ec-5e63-4edd-9dad-e493c715bbba';
alter table tasks add column end_time time default '12:00';
alter table tasks add column type text default 'limpieza-turistica';
alter table tasks add column status text default 'pending';
alter table properties add column cliente_id uuid default '00000000-0000-0000-0000-000000000002';
alter table properties add column is_active boolean default true;
alter table properties add column default_stock_warehouse_id uuid;
alter table stock_warehouses add column is_default boolean default false;
alter table stock_levels add column id uuid default gen_random_uuid();
alter table stock_movements add column id uuid default gen_random_uuid();
alter table stock_movements add column task_id uuid;
alter table stock_movements add column property_id uuid;
create table clients(id uuid,sede_id uuid,is_active boolean);
insert into clients values('00000000-0000-0000-0000-000000000002','1e0759ec-5e63-4edd-9dad-e493c715bbba',true);
create table stock_sede_settings(sede_id uuid,estimated_amenities_enabled boolean,estimated_amenities_started_at timestamptz);
insert into stock_sede_settings values('1e0759ec-5e63-4edd-9dad-e493c715bbba',true,'2026-10-01');
create table stock_estimated_amenity_runs(task_key uuid unique,sede_id uuid,last_attempt_at timestamptz,next_retry_at timestamptz,issue_code text,complete boolean);
create table stock_estimated_amenity_entries(task_key uuid,product_id uuid,state text default 'applied',sede_id uuid,property_id uuid,warehouse_id uuid,quantity numeric,unit_cost_at_consumption numeric,scheduled_end_at timestamptz,movement_id uuid);
create table stock_estimated_amenity_issues(task_key uuid,product_id uuid,sede_id uuid,issue_code text,last_seen_at timestamptz,resolved_at timestamptz,unique(task_key,product_id));
`);
const guarded=readFileSync('scripts/trashSacksDateGuards.sql','utf8');
const estimate=guarded.slice(guarded.indexOf('CREATE OR REPLACE FUNCTION public.process_due_estimated_amenities'),guarded.lastIndexOf('COMMIT;'));
await db.exec(estimate.replaceAll('now()',"TIMESTAMPTZ '2026-10-10 14:00:00+02'"));
await db.query('select process_due_estimated_amenities(100)');
assert.equal(Number((await db.query('select current_quantity from stock_levels')).rows[0].current_quantity),497);
const entries=(await db.query('select * from stock_estimated_amenity_entries')).rows;
assert.equal(entries.length,1);assert.equal(entries[0].task_key,'00000000-0000-0000-0000-000000000009');
assert.equal(Number(entries[0].unit_cost_at_consumption),0.1);
await db.query('select process_due_estimated_amenities(100)');
assert.equal(Number((await db.query('select current_quantity from stock_levels')).rows[0].current_quantity),497);
await db.close();
console.log('PASS sacks: defaults, zero override, independent bags, dates, costs, policies, historical settings, bag reopening, opening stock and safe retry');
