-- Agregar campos para amenities de baño
ALTER TABLE public.properties 
ADD COLUMN jabon_liquido INTEGER NOT NULL DEFAULT 0,
ADD COLUMN gel_ducha INTEGER NOT NULL DEFAULT 0,
ADD COLUMN champu INTEGER NOT NULL DEFAULT 0,
ADD COLUMN acondicionador INTEGER NOT NULL DEFAULT 0,
ADD COLUMN papel_higienico INTEGER NOT NULL DEFAULT 0,
ADD COLUMN ambientador_bano INTEGER NOT NULL DEFAULT 0,
ADD COLUMN desinfectante_bano INTEGER NOT NULL DEFAULT 0,

-- Agregar campos para amenities de cocina  
ADD COLUMN aceite INTEGER NOT NULL DEFAULT 0,
ADD COLUMN sal INTEGER NOT NULL DEFAULT 0,
ADD COLUMN azucar INTEGER NOT NULL DEFAULT 0,
ADD COLUMN vinagre INTEGER NOT NULL DEFAULT 0,
ADD COLUMN detergente_lavavajillas INTEGER NOT NULL DEFAULT 0,
ADD COLUMN limpiacristales INTEGER NOT NULL DEFAULT 0,
ADD COLUMN bayetas_cocina INTEGER NOT NULL DEFAULT 0,
ADD COLUMN estropajos INTEGER NOT NULL DEFAULT 0,
ADD COLUMN bolsas_basura INTEGER NOT NULL DEFAULT 0,
ADD COLUMN papel_cocina INTEGER NOT NULL DEFAULT 0;